### ISSUE TITLE
[469c] UTDM-monsters don't function correctly in team games under new patch.

### ISSUE THREAD

**Issue by evilgrins** [OldUnreal/UnrealTournamentPatches#1183] opened 2023-02-01 19:38 UTC
Put simply: UTDM (Unreal Tournament Deathmatch) monsters, which can be assigned to team games, for whatever reason those on th Blue Team become unresponsive under the new patch. This has never happened before with any previous patch, and its the only reason I've still not gotten the new patch.

I used them in edits for CTF & CTF4 maps; have a little over 350 such maps.

Please fix this issue, and here is a test map for you to see - https://unreal-games.livejournal.com/185703.html

**Comment by OjitroC** [comment] 2023-02-01 22:52
It's the UTDM ScriptedPawns assigned to the Red team that ignore Players (and presumably Bots, though I haven't tested that) on the Blue Team - they will not attack nor will they respond when attacked.

It doesn't happen with 436 or 451 though I'm pretty sure that it happened with one or more of the previous 469 versions.  It certainly happens in 469c Release.

**Comment by OjitroC** [comment] 2023-02-01 23:13
Just tested this in Water Giant with just me, no bots and 
Red DMSkaarjBerserker will attack me when I am on Blue Team
Blue DMSkaarjBerserker will attack me when I am on the Red Team

so it appears to be no longer an issue when using 469c Release - not tested with bots though.

**Comment by SeriousBuggie** [comment] 2023-02-02 00:03
Able reproduce, but only if I am on red team. Blue team work properly.

**Comment by SeriousBuggie** [comment] 2023-02-02 00:23
Any ScriptedPawn equipped with field Team.
This field used for determine attidue in TeamGames:
```unrealscript
/* AttitudeTo()
Returns the creature's attitude towards another Pawn
*/
function eAttitude AttitudeTo(Pawn Other)
{
	if( Other==None )
		return ATTITUDE_Ignore;

	if (Other.bIsPlayer)
	{
		if ( bIsPlayer && Level.Game.bTeamGame && (Other.PlayerReplicationInfo != none) && (Team == Other.PlayerReplicationInfo.Team) )
			return ATTITUDE_Friendly;
```

UTDMWarLord define own Team field. Which [shadowed](https://en.wikipedia.org/wiki/Variable_shadowing) one in ScriptedPawn 

If I edit actor in game and set 1 to ScriptedPawn.Team it start attack me.
Before there be 0, even if I set it to 1 on actor placed on map.

**Comment by SeriousBuggie** [comment] 2023-02-02 00:33
UTDMSkaarjBerserker too define own Team field so there all goes in the same way.
And UTDMT titans - too.

**Comment by SeriousBuggie** [comment] 2023-02-02 00:37
Such code in tick show next log:
```unrealscript
	local ScriptedPawn SP;
	SP = self; 
	log(Level.TimeSeconds @ Self @ Team @ SP.Team);
```
```
ScriptLog: 0.619849 Autoplay.UTDMWarLord1 1 0
ScriptLog: 0.633994 Autoplay.UTDMWarLord1 1 0
ScriptLog: 0.648352 Autoplay.UTDMWarLord1 1 0
```

Mystery with save map where ScriptedPawn.Team set, but not work, explained very easy - shadowed variables not saved. And on restore goes to lastest source, which is not ScriptedPawn.

**Comment by SeriousBuggie** [comment] 2023-02-02 00:45
On v436 log is same:
```
ScriptLog: 60.979263 Autoplay.UTDMWarLord1 1 0
ScriptLog: 60.997223 Autoplay.UTDMWarLord1 1 0
ScriptLog: 61.015892 Autoplay.UTDMWarLord1 1 0
```

Not sure what exact difference. Code in ScriptedPawn.AttitudeTo is same.
Possible this code read Team variable not from ScriptedPawn, but from latest known subclass with this field.

**Comment by SeriousBuggie** [comment] 2023-02-02 01:12
Here mutator for fix this bug:
https://ut99.org/viewtopic.php?t=15704

Can be used with [MutatorsLoader mod](https://ut99.org/viewtopic.php?t=15664) for load it everywhere.

**Comment by SeriousBuggie** [comment] 2023-04-30 08:24
Reproduce:
1. Load in editor [UTDM-test.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/11360869/UTDM-test.zip)
2. Start play as red team

Expected result: Blue skaarj attack you.
Actual result: Blue skaarj ignore you.

You can make `editactor class=ScriptedPawn`, found `Team` under `Hidden - ScriptedPawn`. There be 0 - red team. If you set it to 1, then skaarj start attack you as should.

**Comment by stijn-volckaert** [comment] 2023-04-30 10:37
This "regression" is the result of a fix we applied to the UnrealShare.ScriptedPawn.AttitudeTo function. In 469, the condition that determines the friendliness of a scriptedpawn is this:

```
1308 │     if (Other.bIsPlayer)
1309 │     {
1310 │         if ( bIsPlayer && Level.Game.bTeamGame && (Other.PlayerReplicationInfo != none) && (Team == Other.PlayerReplicationInfo.Team) )
1311 │             return ATTITUDE_Friendly;
```

Note the Level.Game.bTeamGame check. This boolean variable is set to true for _any_ team game type, including UT's TeamGamePlus-based game types.

In 436, the condition was:
```
1182 │     if (Other.bIsPlayer)
1183 │     {
1184 │         if ( bIsPlayer && Level.Game.IsA('TeamGame') && (Team == Other.PlayerReplicationInfo.Team) )
1185 │             return ATTITUDE_Friendly;
```

The Level.Game.IsA('TeamGame') condition always evaluated to false in UT's TeamGamePlus-based game types. This meant that, by default, scriptedpawns such as the UTDM monsters were always aggressive towards players in every team if you fought them in a TeamGamePlus game.

I would argue that 469 is doing the right thing here, and 436 was bugged. However, since there are mods that clearly rely on the bugged behavior, we will disable this bug fix by default in 469d.

**Closed** 2023-05-26 11:34 UTC
Labels: UnrealScript, regression, fixed in the next patch
