### ISSUE TITLE
[469b] Crash on enter to MH-Asmodeus_Aions+SBFix1 after another map

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#247] opened 2021-03-20 08:16 UTC
If I enter to MH-Asmodeus_Aions+SBFix1 after another map UT crash with message:
```
---------------------------
Critical Error
---------------------------
General protection fault!

History: FMallocAnsi::Realloc <- 11B7147C 948719188 FArray <- FArray::Realloc <- 237179797*4 <- UModel::PostLoad <- UObject::ConditionalPostLoad <- (Model MH-Asmodeus_Aions+SBFix1.Model1) <- PostLoadObjects <- UObject::EndLoad <- ULinkerLoad::CreateImport <- IndexToObject <- ULinkerLoad<<UObject <- (LinkerLoad Transient.LinkerLoad200 4649987)) <- FBspSurf<< <- TArray<< <- TTransArray<< <- UModel::Serialize <- LoadObject <- (Model MH-Asmodeus_Aions+SBFix1.Model1 4649987==4649987/6243286 3974834 2089443) <- ULinkerLoad::Preload <- ULevel::Serialize <- LoadObject <- (Level MH-Asmodeus_Aions+SBFix1.MyLevel 4649987==4649987/6243286 6064948 113623) <- ULinkerLoad::Preload <- PreLoadObjects <- UObject::EndLoad <- UObject::StaticLoadObject <- (Engine.Level MH-Asmodeus_Aions+SBFix1.MyLevel MH-Asmodeus_Aions+SBFix1) <- LoadLevel <- UGameEngine::LoadMap <- AttemptLoadPending <- TickPending <- UGameEngine::Tick <- UpdateWorld <- MainLoop
---------------------------
ОК
---------------------------
```
```
---------------------------
Critical Error
---------------------------
General protection fault!

History: FMallocAnsi::Realloc <- 069704C7 1893088440 FArray <- FArray::Realloc <- 473272110*4 <- UModel::PostLoad <- UObject::ConditionalPostLoad <- (Model MH-Asmodeus_Aions+SBFix1.Model1) <- PostLoadObjects <- UObject::EndLoad <- ULinkerLoad::CreateImport <- IndexToObject <- ULinkerLoad<<UObject <- (LinkerLoad Transient.LinkerLoad186 4649987)) <- FBspSurf<< <- TArray<< <- TTransArray<< <- UModel::Serialize <- LoadObject <- (Model MH-Asmodeus_Aions+SBFix1.Model1 4649987==4649987/6243286 3974834 2089443) <- ULinkerLoad::Preload <- ULevel::Serialize <- LoadObject <- (Level MH-Asmodeus_Aions+SBFix1.MyLevel 4649987==4649987/6243286 6064948 113623) <- ULinkerLoad::Preload <- PreLoadObjects <- UObject::EndLoad <- UObject::StaticLoadObject <- (Engine.Level MH-Asmodeus_Aions+SBFix1.MyLevel MH-Asmodeus_Aions+SBFix1) <- LoadLevel <- UGameEngine::LoadMap <- AttemptLoadPending <- TickPending <- UGameEngine::Tick <- UpdateWorld <- MainLoop
---------------------------
ОК
---------------------------
```
Previous map does not matter but it must be.
If I start UT and after that enter to map - no crush happen. Maybe because previous map and play on it consume some memory, so try allocate big piece of memory for this map failed.

Link for map:
https://www.msdatec.de/projects/ut99/index.htm#MH_Asmodeus_Aions_SBFix
https://www.msdatec.de/projects/ut99/maps/MH-Asmodeus_Aions/MH-Asmodeus_Aions+SBFix1.7z
https://www.msdatec.de/projects/ut99/maps/MH-Asmodeus_Aions/MH-Asmodeus_Aions+SBFix.htm

I use Windows. Free memory enough.
Issue reproduce at least two times in different days.

**Comment by stijn-volckaert** [comment] 2021-05-30 12:50
I cannot reproduce this. Is there a specific map that I can play before MH-Asmodeus_Aions+SBFix1 to trigger this crash?

**Comment by SeriousBuggie** [comment] 2021-05-31 19:35
Possible need map which heavy use of fragmented memory. Usually bpak map fit.
Possible something like [MH-EnterToCore](https://unrealarchive.org/maps/unreal-tournament/monster-hunt/E/mh-entertocore_16da5865.html) with all bpak weapons at start.

But i can not able reproduce it locally too. I try with bpack Warehead and TheFifthVortex map. Flood all time with bpak warhead alt fire, but without success.

**Comment by an-eternity** [comment] 2021-06-01 11:32
I also can not reproduce this, with any huge map loaded prior to this one, including MH-(dU)AS-ImperialBaseFinal that was reported for similar issue some time ago.

But the client i used for tests runs "obj garbage" and "objclean" whenever is idle. The amount of memory used remained within 600MB-1200MB.

**Comment by stijn-volckaert** [comment] 2021-07-06 22:34
This is almost certainly the same issue as #485.

**Comment by SeriousBuggie** [comment] 2021-07-15 20:18
Yes. I found same info in log:
```
Log: Empty package sky, linker None
Log: Unloading: Package sky
Log: File sky.unr was already loaded but is incompatible with requested GUID 400CA60344D6C74969B9F38814CFABD5 - Attempting reload
```
Can attach this file if need.

**Comment by stijn-volckaert** [comment] 2022-07-25 18:06
Fixed in 469c-RC2

**Closed by stijn-volckaert** 2022-07-25 18:06 UTC
Labels: bug, fixed in the next patch
