### ISSUE TITLE
[469b] Holding mouse button 4/5 not working when mouse input type is Cursor

### ISSUE THREAD

**Issue by RoelerCoaster** [OldUnreal/UnrealTournamentPatches#297] opened 2021-04-04 22:13 UTC
**UT version**: 469b release
**OS**: Windows 10

**Description**
I have been trying to bind the walking action to the side buttons of my mouse (mouse 4/5), but it doesn't seem to be working properly. I noticed it only happens when I have the mouse input type set to Cursor, with DirectInput and RawInput it works fine.

In more detail:
- Set the mouse input type to Cursor
- Bind the side buttons of the mouse (button 4 or 5) to an action that normally has an effect when holding the button, like walking or fire.
- Now holding the side buttons does not give the desired results. When the walking action is bound, you do not walk slower at all. When fire is bound and you shoot, for example, the minigun, you only shoot once.

Holding of the other mouse buttons (left, right, mousewheel) works properly.

**Comment by stijn-volckaert** [comment] 2021-06-21 15:51
I cannot reproduce this. Buttons 4 and 5 work fine for me, regardless of the input method. Buttons 6 and 7 do not work with cursor input, but this is because of a fundamental limitation of the Win32 API. Could this be a mouse driver issue? Did you remap your side buttons or assign shortcuts to them by any chance?

**Comment by RoelerCoaster** [comment] 2021-06-22 05:15
Buttons 4 and 5 are detected, and do seem to activate the assigned action once, it is just that when holding them down it is as if the buttons are released immediately.

I just tried it again with a fresh mouse-profile (on my mouse software) so no buttons are re-assigned, it has the same behaviour still.

I do not have access to another mouse with side buttons, so I can not completely test if it is mouse driver related. However, I am able to assign one of my keyboard keys to buttons 4/5 using my keyboard software. Holding down the button on my keyboard then shows the same behaviour using Cursor. Switching to DirectInput or RawInput and holding down the reassigned keyboard button works fine.

For completeness:
Mouse is a Logitech G403 Prodigy
Keyboard is a Steelseries Apex 7 TKL

**Comment by SeriousBuggie** [comment] 2021-06-22 06:40
Confirmed for me.
![img](https://user-images.githubusercontent.com/70026933/122875873-82736b00-d33d-11eb-85ce-fa90db0a6fc0.png)
Both message appear directly after press.

Also if I press fast, after 48 presses messages stop appear.
This also can happen after some time even if I not make 48 presses.

**Comment by SeriousBuggie** [comment] 2021-06-22 06:49
@stijn-volckaert What API used in cursor mode?
I can try search tester for this API for distinguish UT bugs from API limitation.
Possible there no any UT bug. Possible API report short press here by some reason.

**Comment by stijn-volckaert** [comment] 2021-06-22 13:18
Our handling of mouse buttons 4 and 5 was incomplete. This will be fixed in 469c

**Comment by stijn-volckaert** [comment] 2022-07-25 18:05
Fixed in 469c-RC2

**Closed by stijn-volckaert** 2022-07-25 18:05 UTC
Labels: Windows, fixed in the next patch
