### ISSUE TITLE
[469b] player rotation often disabled when launching UnrealTournament.exe from command line

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#284] opened 2021-03-28 13:07 UTC
I noticed that when UnrealTournament.exe is launched from command line or from UnrealEd, my player rotation is sometimes only possible horizontally sometimes only vertically, sometimes not possible at all and sometimes normal. I didn't find any regularity, behaviour is not predictable for me. My UnrealTournament.ini an USER.INI are write protected and therefore could not have been changed between.
Example batch file "StartUT.cmd":
`D:\PROGRAMME\UT.469b\SYSTEM\UnrealTournament.exe D:\Programme\UT.469b\Maps\DM-Gothic.unr`

Version 436 works normal when launched from command line.

(Also reported at [UT99.org](https://ut99.org/viewtopic.php?p=127569#p127569).)

**Comment by SeriousBarbie** [comment] 2021-04-21 09:45
I also tried switching to the SYSTEM directory before starting UT but without success:
```
set UTDIR=D:\Programme\UT.469b
cd /D %UTDIR%\System
%UTDIR%\System\UnrealTournament.exe %UTDIR%\Maps\DM-Gothic.unr
```

**Comment by SeriousBuggie** [comment] 2021-04-21 10:08
Never happen to me. And I not able to reproduce.
Now call 10 times in cmd:
`R:\Users\User>W:\UT\System\UnrealTournament.exe W:\UT\Maps\DM-Gothic.unr`
All work fine.

I think it depends from some drivers/hardware/OS settings.

**Comment by SeriousBuggie** [comment] 2021-08-20 20:31
Finally able reproduce it on v469b. Need set mouse input to DirectInput.

As workaround - use `Cursor` or `Raw Input`.

I can not reproduce issue on early beta v469c, so look like issue fixed on it.

**Comment by stijn-volckaert** [comment] 2022-07-24 09:07
At least one player has reported that this issue is still present in v469c-RC2. Unfortunately, I still cannot reproduce the problem, even after starting the game >100 times with different configurations

**Comment by stijn-volckaert** [comment] 2022-07-24 09:11
Is there any additional information you can give us? Which OS are you using? Are you using a single monitor or multiple monitors?

What are your game settings (renderer, resolution, fullscreen/windowed)?

**Comment by an-eternity** [comment] 2022-07-24 11:21
It seems, the value of `WindowedViewportX` in `[WinDrv.WindowsClient]` somehow affects the mouse X-axis control behavior in full screen mode when mouse input mode is set to Cursor and render device is Direct3D 9... When that value is small enough (e.g., less than 1554 for full screen width 3440), X-axis control in this case appears completely broken.
Exactly the same happens with `WindowedViewportY` in `[WinDrv.WindowsClient]`, and then mouse Y-axis control appears broken in full screen mode...

**Comment by SeriousBarbie** [comment] 2022-07-24 20:12
Here it is single monitor in full screen; additional info can be found in the [Inis&Logs.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9176587/Inis.Logs.zip) file.

I can easily reproduce it when I start UT and switch to another window while UT is starting.

**Comment by stijn-volckaert** [comment] 2022-07-26 05:58
I still cannot reproduce this, even with your configurations. I suspect this may be a Windows/driver problem. I'll leave the ticket open for now just in case you find other ways to reproduce the problem

**Comment by an-eternity** [comment] 2022-08-06 07:34
v469c-RC3 - issue not fixed.

Important note: to reproduce this issue RefreshRate setting value in `[D3D9Drv.D3D9RenderDevice]` section must be equal to system default refresh rate, and full screen resolution in game must be also equal to default system resolution, so that to avoid display mode change.
Of course, `WindowedViewportX` and/or `WindowedViewportY` in `[WinDrv.WindowsClient]` must be small enough for this issue to appear.

**Comment by SeriousBuggie** [comment] 2023-08-20 11:35
Please check this issue against latest v469d preview builds.

**Closed** 2023-12-25 10:32 UTC
Labels: Windows, info-needed
