### ISSUE TITLE
[469a] Some issues with model skins / textures

### ISSUE THREAD

**Issue by gattovicentino** [OldUnreal/UnrealTournamentPatches#56] opened 2020-09-28 11:04 UTC
In multiplayer internet/LAN mode, some third party models I use as bots have an issue: they appear green due to missing skin... for some the whole body, for others only the head. 
For instance: "Arab", "Alita", "Sydney", "Bender" and others. I don't know why... and I don't know why only some of them. The aforementioned issue is NOT present in practice mode.
![Shot00000](https://user-images.githubusercontent.com/72017141/94424237-30c0fa00-018a-11eb-96e1-cffd45b0bca3.png)

Another model's skin ("Skorpion") seems "ruined". This Skorpion's issue is present in both multiplayer and practice sessions.
![Shot00008](https://user-images.githubusercontent.com/72017141/94424462-8bf2ec80-018a-11eb-94d0-812de06d1eda.png)

In 436 version all the above mentioned models work perfectly, with their correct skin/textures, in both internet/LAN and practice games.

**Comment by stijn-volckaert** [comment] 2020-09-28 11:52
Which mod are these skins/models part of?

**Comment by gattovicentino** [comment] 2020-09-28 12:19
They are not part of a specific mod, they are separated packages of player (bot) models, made by different people.
In the pictures I was playing with U4E mutator but the issues are still present with no mutator at all.

**Comment by stijn-volckaert** [comment] 2020-09-28 12:23
How do I install these then? I've never used custom models or skins before.

**Comment by gattovicentino** [comment] 2020-09-28 12:37
Many models are available on some sites, for example:
http://medor.no-ip.org/index.php?dir=Skins/
(Bender is there).

About the Scorpion model, I think I've downloaded from www.ut99.org.

**Comment by SeriousBuggie** [comment] 2020-09-28 12:46
> How do I install these then? I've never used custom models or skins before.

As usual - copy files in folders (System, Textures).
For use on server need list custom model in `ServerPackages`.
Proper .int file allow choose new skins/models on Player setup UWindow.

**Comment by stijn-volckaert** [comment] 2020-09-28 13:01
I just tried the Bender model on a 469a LAN server with the 469a client and saw no issues. Is this the setup you're testing with as well?

**Comment by gattovicentino** [comment] 2020-09-28 13:14
> I just tried the Bender model on a 469a LAN server with the 469a client and saw no issues. Is this the setup you're testing with as well?

So... I've copied my UT 436 folder to another place and applied 469a patch. I did it two times (the first try, installing 469 patch from .ZIP, the second, installing the patch from .EXE). Both 469a installations have these issues. In UT 436 installation the issues are not present.

**Comment by SeriousBuggie** [comment] 2020-09-28 13:42
Please provide links or upload here zip versions of affected skins/models. UMOD is not good for testing.

Bender is UMOD on medor.

**Comment by gattovicentino** [comment] 2020-09-28 17:13
> Please provide links or upload here zip versions of affected skins/models. UMOD is not good for testing.
> 
> Bender is UMOD on medor.

I don't know if I can find .zip versions, because most of them where distributed as UMOD files and I installed them years ago (but I can try to find manually their files inside UT subfolders and zip them by myself... at least for some models, to examine the issue). 
I have found problems in at least 25 different models/skins. I am absolutely sure they all work in v.436 because I've just checked each of them, one by one.

**Comment by SeriousBuggie** [comment] 2020-09-28 17:40
> but I can try to find manually their files inside UT subfolders and zip them by myself... at least for some models, to examine the issue

This will be better because for "years ago" can happens anything with files. Maybe its damaged, but in not important for v436 parts. If this is true, we never can reproduce your issue without your files.

**Comment by gattovicentino** [comment] 2020-09-28 18:58
> > but I can try to find manually their files inside UT subfolders and zip them by myself... at least for some models, to examine the issue
> 
> This will be better because for "years ago" can happens anything with files. Maybe its damaged, but in not important for v436 parts. If this is true, we never can reproduce your issue without your files.

Yes, it's true.
So, here you are a link to a zip with some of those files (It was impossible to attach it directly here because its size is 52mb and github limit is 10):   https://mega.nz/file/iuwFgYTa#6K8elyRcBHMyMGskAknsRP0CxV9CmtVTpLtRruTvLfA

I've chosen these models:

- Alita (this model appears completely green in v469a, missing skin)

- Bender (only its head is green, missing skin. The body is normal).

- ObiWan  Kenobi (a different issue: you can choose old face (Alec Guinness) or young one (Ewan McGregor) but in v469 it shows young face even if you choose the old one).

- Angel (his face is black instead of green, even in practice session, not only in multiplayer).

- Santa (in multiplayer mode, the skin of his face appears in the back of the head, instead of in the front. In practice mode, it appears with two faces... front and back!).

- Scorpion and SubZero (both of them have the same issue, a "ruined" skin, as shown in one of the pictures uploaded by me at the beginning of this post.

Inside the zip file there is also a screenshot showing a critical error that occurs sometimes (never seen on v436), I don't know if it's related to models/skins issues, but it maybe so.

Some models from a mod called NeoCairo, that I use as bots in normal DM and MH games, are not shown in v469... their names appear if I click F1 during the game, but they seem not to be there. 
I didn't include them into the zip file, because they need the whole NeoCairo mod to work.

**Comment by SeriousBuggie** [comment] 2020-09-28 19:19
Can confirm on Angel.
D3D9:
![scr_1601320643](https://user-images.githubusercontent.com/70026933/94476010-920fba00-01d8-11eb-901f-6e7e3aa5377e.png)
OpenGL:
![scr_1601320671](https://user-images.githubusercontent.com/70026933/94476045-9b008b80-01d8-11eb-84e8-19fa6a587bfb.png)
XOpenGL:
![scr_1601320698](https://user-images.githubusercontent.com/70026933/94476066-a489f380-01d8-11eb-8d9d-ee6510a9d68a.png)

About Scorpion: Look like it is related to #26.

**Comment by SeriousBuggie** [comment] 2020-09-28 19:29
Santa skin with two faces on all renders in v469a.
And near same in v436, just back side more red. Look like something damaged.
v436 D3D9:
![scr_1601321249](https://user-images.githubusercontent.com/70026933/94477002-eff0d180-01d9-11eb-9f4b-720f0cec083a.png)
v469a D3D9:
![scr_1601321296](https://user-images.githubusercontent.com/70026933/94477031-f8e1a300-01d9-11eb-9a47-cc0b2b721456.png)

**Comment by SeriousBuggie** [comment] 2020-09-28 19:42
> ObiWan Kenobi (a different issue: you can choose old face (Alec Guinness) or young one (Ewan McGregor) but in v469 it shows young face even if you choose the old one).

Reproduced for me. In D3D9. In v436 fine, in v469a used new face, even if selected old one.

**Comment by gattovicentino** [comment] 2020-09-28 19:48
I forgot to mention that in all tests I used xopengl as renderer :) but I see that some of the issues are reproduced using D3D9 as well.

**Comment by stijn-volckaert** [comment] 2020-09-28 20:05
Can't reproduce the problem with Santa. This one looks the same to me in v436. Both 436 and 469a have the face on the back if you set Team to "None". The screenshot above is one where Santa's team is set to Red.

**Comment by gattovicentino** [comment] 2020-09-28 20:23
> Can't reproduce the problem with Santa. This one looks the same to me in v436. Both 436 and 469a have the face on the back if you set Team to "None". The screenshot above is one where Santa's team is set to Red.

Correct. It's the same in v436 here too... it was my mistake, sorry, I remembered it worked fine (maybe because I saw it with color team set to red... or confusing with another model, since I tried more than 300!) but Santa has problems in v436 too.

**Comment by stijn-volckaert** [comment] 2020-09-28 20:26
The Scorpion model is broken due to XOpenGLDrv. Most other skins seem fine to me, except for Angel. Angel's face is completely black when you set her team to none. I'm investigating now.

**Comment by stijn-volckaert** [comment] 2020-09-28 20:28
The missing skins in Multiplayer games seem to come from some anti-skinhack protection UTPG added. I'll either throw it out or modify it.

**Comment by gattovicentino** [comment] 2020-09-28 20:40
Fine! The causes of some of the issues have been identified, very good :)

**Comment by stijn-volckaert** [comment] 2020-09-28 20:47
Could you upload your server's UnrealTournament.ini and User.ini please?

**Comment by SeriousBuggie** [comment] 2020-09-28 21:43
> Both 436 and 469a have the face on the back if you set Team to "None". The screenshot above is one where Santa's team is set to Red.

Yep. My mistake. Check now and you right.

**Comment by stijn-volckaert** [comment] 2020-09-28 22:09
The scorpion bug will be fixed in 469b.

**Comment by SeriousBuggie** [comment] 2020-09-28 22:42
Off-topic:
@stijn-volckaert, maybe you tag all issues where you answer 
> will be fixed in 469b.

With same some tag?
Because it be very handful goes to this tag and check every issue for fix when 469b out.

**Comment by gattovicentino** [comment] 2020-09-29 10:46
> Could you upload your server's UnrealTournament.ini and User.ini please?

Here you are the files and another issue about skins: as you can see in the picture, in v469 some skins don't work and many characters (bots) appear identical because UT shows the default TMale2Bot configuration instead of the selected custom skins. I attached (inside the zip file) the files of those skins (characters from Star Trek and Spiderman et cetera).

![Shot00012](https://user-images.githubusercontent.com/72017141/94548650-549b4300-0251-11eb-8ae3-cc7389a3cb34.png)
[UT.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5298334/UT.zip)

**Comment by stijn-volckaert** [comment] 2020-09-29 10:51
Are you running a mapvoter or gametype that adds all of the skin and model packages to the serverpackages list?

**Comment by gattovicentino** [comment] 2020-09-29 11:30
> Are you running a mapvoter or gametype that adds all of the skin and model packages to the serverpackages list?

At the moment I play sometimes with human friends (and bots together) in LAN. I can't add all necessary serverpackages in unrealtournament.ini because the server crashes on startup (on any UT version, 469a too), so I am using a separate .txt files and I copy/paste serverpackage lines to unrealtournament.ini depending on what I want to load/run. Valhalla Avatar helps if humans only are playing, but with bots it's more complicated. It would be fantastic if I could put hundreds of serverpackages lines in unrealtournament.ini but I don't know if it's a matter of memory or some engine limit.

**Comment by CacoFFF** [comment] 2020-10-01 11:42
Each ServerPackage adds a bunch of resources such as names to the network translation table, as well as increase the data required on the initial communication (causing many possible issues at join time)
For example, each of these packages share a lot of common names with each other.

**Comment by gattovicentino** [comment] 2020-10-01 16:29
> Each ServerPackage adds a bunch of resources such as names to the network translation table, as well as increase the data required on the initial communication (causing many possible issues at join time)
> For example, each of these packages share a lot of common names with each other.

Yes, of course it's very heavy, but it would be nice if there was a chance to make it work on modern hardware and updated software (patch).

**Comment by gattovicentino** [comment] 2020-10-12 09:42
> > Are you running a mapvoter or gametype that adds all of the skin and model packages to the serverpackages list?
> 
> At the moment I play sometimes with human friends (and bots together) in LAN. I can't add all necessary serverpackages in unrealtournament.ini because the server crashes on startup (on any UT version, 469a too), so I am using a separate .txt files and I copy/paste serverpackage lines to unrealtournament.ini depending on what I want to load/run. Valhalla Avatar helps if humans only are playing, but with bots it's more complicated. It would be fantastic if I could put hundreds of serverpackages lines in unrealtournament.ini but I don't know if it's a matter of memory or some engine limit.

Should I open a new separate thread regarding this ServerPackages issue, or not?
(Since this thread was opened to describe another issue)

**Comment by gattovicentino** [comment] 2021-03-12 17:59
Just to confirm that all the issues mentioned above, with models/skins, are still there in 469b.

**Comment by gattovicentino** [comment] 2021-03-13 15:03
> 
> 
> Here you are the files and another issue about skins: as you can see in the picture, in v469 some skins don't work and many characters (bots) appear identical because UT shows the default TMale2Bot configuration instead of the selected custom skins. I attached (inside the zip file) the files of those skins (characters from Star Trek and Spiderman et cetera).
> 
> ![Shot00012](https://user-images.githubusercontent.com/72017141/94548650-549b4300-0251-11eb-8ae3-cc7389a3cb34.png)
> [UT.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5298334/UT.zip)

This specific issue with custom skins of **TMale2Bot** skins not showing (**SoldierSkins3.trek** and **SoldierSkins_Borg.borg**, for instance) is still present in v.469b, but in multiplayer mode only. 
In practice mode everything is OK).

So, default TMale2Bot skins are shown in multiplayer games... and the correct custom skins (Star Trek characters) in practice mode.

**Closed** 2023-05-26 11:35 UTC
Labels: UnrealScript, regression, fixed in the next patch
