### ISSUE TITLE
[469c] No Weaponhand-Model when using OpenGL Renderer?

### ISSUE THREAD

**Issue by CaptainCoward** [OldUnreal/UnrealTournamentPatches#1170] opened 2023-01-22 01:18 UTC
I feel stupid and it might be me, but the WeaponHand seems to be always hidden when using the OpenGL renderer (that isn't the case when using XOpenGL). I even deleted my User.ini and Unrealtournament.ini because i thought it might be some setting (since i didn't play UT for quite a while) but the Issue remains: The Gun Model remains hidden although it is set to Right, Left or Center in the Options.

**Comment by an-eternity** [comment] 2023-01-25 08:58
Is it always hidden, or in some cases it is still visible (on such maps as DM-Phobos or CTF-Face)?
What is v469c revision/compile date?
If a GPU is by AMD, what driver version is it?

**Comment by SeriousBuggie** [comment] 2023-01-25 11:44
> where i find the Compile date i'll provide that as well.

Inside UnrealTournament.log, near start.

**Comment by an-eternity** [comment] 2023-01-25 12:00
GitHub release page has the latest version to the moment (latest one date is Oct 29 2022).

It could be same issue as this: https://github.com/OldUnreal/UnrealTournamentPatches/issues/996
If yes, this means AMD still has not fixed that bug in their drivers.
Currently i keep version 22.6.1, because further versions have problems (this problem is not the only one...).
I have not installed/tested version 22.11.2 yet, will do it a bit later, then will post my results here (most likely all of those problems will be still there not fixed, as in every previous version after 22.6.1).

**Comment by CaptainCoward** [comment] 2023-01-25 21:22
In case the compile date still matters: (Init: Compiled: Oct 29 2022 10:10:27).  I guess there isn't much more info i can provide at this point.

**Comment by an-eternity** [comment] 2023-01-26 06:56
Installed/tested version 22.11.2 - bug is still there:
![Shot00123_](https://user-images.githubusercontent.com/72374425/214774933-a6a7ca8d-6a61-4e4b-866f-1c846166025f.jpg)

**Comment by stijn-volckaert** [comment] 2023-05-27 08:43
Definitely a duplicate of #996

**Closed** 2023-05-29 03:08 UTC
Labels: duplicate, rendering
