### ISSUE TITLE
[469b] ZoneVelocity in a gravity zone affects players differently depending on their framerate limit

### ISSUE THREAD

**Issue by dizzy-egg** [OldUnreal/UnrealTournamentPatches#366] opened 2021-05-02 02:23 UTC
In the BunnyTrack map CTF-BT-Reincarnation, in the spawn room there is a cylinder/pillar which makes players fly up into the air. The cylinder is a gravity zone with an increased ZoneVelocity designed to launch/boost players far enough to land on a distant platform.

**Issue:** Players are boosted differently depending on their frame rate limit.

With a configured limit of `0`, and a reading of `399` FPS via `timedemo 1`, players are *not* boosted powerfully enough to reach the platform.

With a limit of `60`, the same player is boosted far more powerfully and can reach the platform.

**Comment by dizzy-egg** [comment] 2021-05-02 02:36
Interesting addition: on the BunnyTrack.net BT servers there's a command called `!speed` which shows the vertical/horizontal speed of the player at the bottom of the screen.

With a lower FPS limit, the maximum speeds reached by the player are notably higher.

**Comment by stijn-volckaert** [comment] 2022-05-30 11:36
Confirmed duplicate of #147. 469c will not have a full fix for this problem, but it will be mitigated to a large extent.

**Closed by stijn-volckaert** 2022-05-30 11:36 UTC
Labels: duplicate, fixed in the next patch, physics, high-prio
