### ISSUE TITLE
[469b] UWindow combobox not select previous values when opened firstly

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#388] opened 2021-05-07 03:00 UTC
Reproduce:
1. Start UT.
2. Open Dialog for create practice session.
![img](https://user-images.githubusercontent.com/70026933/117391724-39846600-aef9-11eb-91d7-40a3ccfaefef.png)
3. Open maps combo box.
![img](https://user-images.githubusercontent.com/70026933/117391761-4c973600-aef9-11eb-80ec-4a7e2dff818b.png)

Expected result: List already scroll to selected map.
Actual result: List scrolled to top (not scrolled).

**Comment by SeriousBuggie** [comment] 2021-05-07 03:34
Fix:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/UWindow/UWindowComboControl.uc#L186
```
function DropDown()
{
	bListVisible = True;
	EditBox.SetEditable(False);
	List.ShowWindow();
}
```
replace to
```
function DropDown()
{
	local int Index;

	Index = GetSelectedIndex();
	if (Index >= 0)
		List.VertSB.Pos = Index;

	bListVisible = True;
	EditBox.SetEditable(False);
	List.ShowWindow();
}
```
This change affect all drop down in game. Include:
- select voice pack
- select player model
- and so on

**Comment by claudio-luis** [comment] 2021-05-24 13:33
Simplified version of the suggestion above:
```unrealscript
function DropDown()
{
	List.VertSB.Pos = Max(0, GetSelectedIndex());
	bListVisible = True;
	EditBox.SetEditable(False);
	List.ShowWindow();
}
```

**Comment by Feralidragon** [comment] 2021-05-24 13:39
Simplified version of the suggestion above:
```unrealscript
function DropDown()
{
	List.VertSB.Pos = Max(0, GetSelectedIndex());
	bListVisible = True;
	EditBox.SetEditable(False);
	List.ShowWindow();
}
```

**Comment by SeriousBuggie** [comment] 2021-05-24 13:47
> Simplified version of the suggestion above:

This code not equals.
Let's assume `GetSelectedIndex()` return `-1`.
My code prefer old position of `List.VertSB.Pos`.
Your code just reset it to `0`.

Real example:
You open Combobox which open earlier.
Now value disappear, but list already scrolled.
In my case list open on old position where be old item before.
In your case list reset scroll to top, which is not user-friendly.

**Comment by Feralidragon** [comment] 2021-05-24 14:46
But then that means that `GetSelectedIndex()` should be fixed instead.
Such a method should always return the index of the selected value, without exception.

The only case it should return something like `-1` is when the list is empty.
Goes to show the mess that UWindows is overall...

**Comment by SeriousBuggie** [comment] 2021-05-24 15:00
> But then that means that `GetSelectedIndex()` should be fixed instead.
> Such a method should always return the index of the selected value, without exception.

if `bCanEdit == True` then in such combobox you can input custom text and `GetSelectedIndex()` not able find it in list of suggestions.

**Comment by Feralidragon** [comment] 2021-05-24 16:34
At that point one has to wonder about what `GetSelectedIndex()` should actually mean then.

If the text is editable and can save the custom input value, as a different value from the list, then `GetSelectedIndex()` should return `-1` indeed (but only after the input is set), at which point the list should indeed return to the start if opened again, which would be the expected behavior (holding a previous state for too long is also bad UX), otherwise if the input value must match an existing value, unless the value matches an existing value then `GetSelectedIndex()` should return the currently held index, since it hasn't really changed.

But at this point I guess we would start to diverge from the scope of this specific issue, and open the Pandora's box which is UWindow in general, so to settle this for now I think your original suggestion may be indeed the best change for now, with maybe a discussion around how this stuff as a whole should work as a separate discussion. :)

**Closed** 2021-07-02 09:55 UTC
Labels: UnrealScript, enhancement
