### ISSUE TITLE
[469b] Items disappearing and menu artefact on xopengl renderer

### ISSUE THREAD

**Issue by badoshk** [OldUnreal/UnrealTournamentPatches#780] opened 2022-04-05 20:31 UTC
Better shown in video:
[https://youtu.be/bi2XSbKC1Jo](url)

Issue only occurs with xopengl renderer
On Windows 10 Pro
CPU: AMD ryzen 5 3600
GPU: RTX2070

unrealtournament.ini settings:

[XOpenGLDrv.XOpenGLRenderDevice]
Description=NVIDIA GeForce RTX 2070/PCIe/SSE2
NoDrawSimple=False
NoDrawTile=False
NoDrawGouraudList=False
NoDrawGouraud=False
NoDrawComplexSurface=False
NoBuffering=False
UseOpenGLDebug=False
UseHWClipping=False
UseHWLighting=False
UseBindlessTextures=True
SyncToDraw=False
UsePersistentBuffers=False
GenerateMipMaps=False
UseBufferInvalidation=False
NoAATiles=True
DetailTextures=True
MacroTextures=True
BumpMaps=True
GammaCorrectScreenshots=True
UseAA=True
UseTrilinear=True
UsePrecache=True
AlwaysMipmap=True
ShareLists=True
NoFiltering=False
HighDetailActors=True
Coronas=True
ShinySurfaces=True
VolumetricLighting=True
MaxAnisotropy=16.000000
LODBias=0.000000
GammaOffsetScreenshots=0.700000
DebugLevel=2
NumAASamples=8
RefreshRate=75
DescFlags=1
UseVSync=On
OpenGLVersion=Core

**Comment by Mantha065** [comment] 2022-04-15 02:19
I too have this same issue.

unrealtournament.ini settings:
[XOpenGLDrv.XOpenGLRenderDevice]
Description=GeForce GTX 1060 3GB/PCIe/SSE2
NoDrawSimple=False
NoDrawTile=False
NoDrawGouraudList=False
NoDrawGouraud=False
NoDrawComplexSurface=False
NoBuffering=False
UseOpenGLDebug=False
UseHWClipping=False
UseHWLighting=False
UseBindlessTextures=True
SyncToDraw=False
UsePersistentBuffers=False
GenerateMipMaps=False
UseBufferInvalidation=False
NoAATiles=True
DetailTextures=True
MacroTextures=True
BumpMaps=True
GammaCorrectScreenshots=True
UseAA=True
UseTrilinear=True
UsePrecache=True
AlwaysMipmap=False
ShareLists=True
NoFiltering=False
HighDetailActors=True
Coronas=True
ShinySurfaces=True
VolumetricLighting=True
MaxAnisotropy=4.000000
LODBias=0.000000
GammaOffsetScreenshots=0.700000
DebugLevel=2
NumAASamples=4
RefreshRate=60
DescFlags=1
UseVSync=Adaptive
OpenGLVersion=Core

**Comment by alsosed** [comment] 2022-04-15 06:34
https://github.com/OldUnreal/UnrealTournamentPatches/issues/637

**Comment by stijn-volckaert** [comment] 2022-04-15 09:35
This is indeed a duplicate of bug #637

You can download the fixed XOpenGLDrv.dll [here](https://github.com/OldUnreal/UnrealTournamentPatches/releases/download/v469b/XOpenGL-469b-Fix2.zip)

**Closed by stijn-volckaert** 2022-04-15 09:35 UTC
Labels: bug, duplicate, rendering, fixed in the next patch
