### ISSUE TITLE
[469d] Add a window prompt when trying to connect to a server with no free slots.

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1476] opened 2023-12-11 14:47 UTC
When you try to connect to a server that has no free slots, it will say "Connection failed, Rejected by server". It would be nice if a window could pop up informing that the server is full and letting you reconnect as a spectator.

Concept idea:
![Screenshot_60](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/41218348-bb58-4595-aa9c-ea653319c7c6)

**Comment by SeriousBuggie** [comment] 2023-12-11 19:14
Not all servers allow you connect as spectators, and there can be too no free slots.
Or it can be opposite. You try join as spectator, and server refuse it. So need implement it in both ways.

However this already discussed here:
https://github.com/OldUnreal/UnrealTournamentPatches/issues/194

Conclusion - we can't implemented such without break some mods, which is not an option.

Duplicate of #194

**Closed by SeriousBuggie** 2023-12-11 19:14 UTC
