### ISSUE TITLE
[469b] Fire from stinger on OpenAL make flood in log

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#282] opened 2021-03-28 02:24 UTC
When I fire from stinger with primary fire I get next flood in logs:
```
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
Warning: ALAudio: PlaySound alSourcef setting error: Invalid Value
```
It happen for relatively short press fire button. Not single shot, but few of them.

**Comment by TankBeef** [comment] 2021-04-13 16:14
Oh, now I remember. Don't now if there is correlation with this issue I opened, which I have been unable to reproduce. https://github.com/OldUnreal/UnrealTournamentPatches/issues/302
But I did get that exact message flood after it occured, although I do not use the stinger mutator. But I am on OpenAL.

**Comment by SeriousBuggie** [comment] 2022-06-29 07:23
Confirmed, fixed for latest v469c preview.

**Comment by stijn-volckaert** [comment] 2022-07-25 18:06
Fixed in 469c-RC2

**Closed by stijn-volckaert** 2022-07-25 18:06 UTC
Labels: bug, audio, fixed in the next patch
