### ISSUE TITLE
[469c-RC4] Small graphical bug with geometry lines visible through weapons muzzle flash & light sources

### ISSUE THREAD

**Issue by r2rX** [OldUnreal/UnrealTournamentPatches#1099] opened 2022-10-20 10:39 UTC
Hey all,

Firstly, it's a pleasure to play UT99 natively in Linux with this amazing project. In honor of that, I've been sinking some time into it and, fortunately, I've only encountered one small bug.

It seems that geometry lines become visible when seen through sprites (i.e weapons muzzle flash or light coronas). Here are some screenshots to show-case this.

![ut_1](https://user-images.githubusercontent.com/18622885/196926076-2b216f01-3794-45a3-8dda-3b9b8ea48db3.png)
![ut_2](https://user-images.githubusercontent.com/18622885/196926211-d4dcd699-c39e-4af7-90f3-6682d14035ed.png)
![ut_3](https://user-images.githubusercontent.com/18622885/196926289-74b7814d-7a3b-43ee-95a6-e53188344504.png)

Tests were done on Fedora 36 KDE, AMD RX 6800M w/ Mesa 22.3.0-git (either on OpenGL or XOpenGL) with the 64bit executable of the game. Any fellow Linux/AMD users encounter this as well?

I thought to bring it up here first but if it's determined to be a driver issue, I'll open an issue tracker on Mesa git.

**Comment by an-eternity** [comment] 2022-10-20 11:44
There are 2 workarounds:
1. Downgrade driver to last stable version.
2. Use 'NoAATiles=False' renderer setting.

https://github.com/OldUnreal/UnrealTournamentPatches/issues/965

**Comment by r2rX** [comment] 2022-10-20 14:45
Thanks for the info, @an-eternity . Disabling NoAATiles does indeed placate the issue. Considering this happens with the Windows driver for AMD as well, it seems to be a common between their respective OpenGL implementations. I'll issue a report on Mesa git.

**Comment by r2rX** [comment] 2022-10-20 15:35
Issue report submitted on [mesa git](https://gitlab.freedesktop.org/mesa/mesa/-/issues/7537).

**Comment by an-eternity** [comment] 2022-10-20 16:17
A little note: driver version for Windows where this (and some other OpenGL-related issues) have been introduced is 22.7.1.
This issue does not present in version 22.6.1.
Nevertheless, i prefer to keep version 22.5.1 (that unlike 22.6.1 has status 'recommended') to avoid another possible issues that may probably exist in 22.6.1 too (considering recent information that AMD is rewriting their drivers).

**Comment by r2rX** [comment] 2022-10-20 16:21
Thanks for letting me know. I'll update the mesa tracker to give a more accurate report.

**Comment by stijn-volckaert** [comment] 2022-10-23 10:49
Confirmed duplicate of #965. Unfortunately, there's not much we can do about this other than recommend that people downgrade to an earlier AMD driver.

**Closed by stijn-volckaert** 2022-10-23 10:49 UTC
Labels: duplicate, invalid, rendering

**Comment by r2rX** [comment] 2022-10-23 12:21
All good. I'll post any updates in #965.

**Comment by r2rX** [comment] 2022-10-27 10:16
Just letting Linux & AMD users know that mesa commit [19326](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/19326/commits) fixes the issue. If any AMD & Windows users want to, try report this to the Windows driver team and reference this commit.

**Comment by an-eternity** [comment] 2023-01-26 07:15
It seems, now this bug is fixed in AMD drivers for Windows too (if i test it properly, with version 22.11.2 - no such artifacts anymore).
