### ISSUE TITLE
[469d RC2] Dynamic fonts should not be referenced in package saving

### ISSUE THREAD

**Issue by OjitroC** [OldUnreal/UnrealTournamentPatches#1446] opened 2023-11-08 22:21 UTC
When trying to run a Saved game (in default UT and when using OldSkool) I get this error

_Log: Failed import: Font Font Editor.DynamicFont1 (file ../System/Editor.u)
Warning: Failed to load save1.usa: Can't find Font in file Font Editor.DynamicFont1..
Warning: Failed to load "Level None.MyLevel": Can't find Font in file Font Editor.DynamicFont1.._

See https://ut99.org/viewtopic.php?t=16066 for more info.

**Comment by SeriousBuggie** [comment] 2024-03-26 06:42
Can you reproduce this issue in next steps?
1. Start UT.
2. Run `start MH-XV-KingJoshCity2v1`
3. Start game.
4. Run `savegame 4`
5. Close UT.
6. Start UT again.
7. Run `start ..\Save\Save4.usa`

I can't reproduce on our internal test builds for 469e.

**Comment by SeriousBuggie** [comment] 2024-04-01 03:01
After set gui and font scaling able reproduce issue:
![img](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/d1d2f0c0-2b3f-4ebc-9685-945579aabd87)

```
Log: Failed import: Font Font Editor.DynamicFont4 (file ../System/Editor.u)
Warning: Failed to load ..\Save\Save4.usa: Can't find Font in file Font Editor.DynamicFont4..
Warning: Failed to load "Level None.MyLevel": Can't find Font in file Font Editor.DynamicFont4..
```

So workaround is turn off gui scale before save I guess,

**Comment by SeriousBuggie** [comment] 2024-04-01 04:30
What Font scaling you use?
If override not enable - enable it and set lover level from you see, until issue not gone.

**Comment by SeriousBuggie** [comment] 2024-04-01 04:32
Issue can be caused too big fonts. It take too much memory, so some allocations can fail and this can produce memory corruption on save game.

**Comment by CortexReaver** [comment] 2024-12-03 06:50
Is this bug only apparent on ICBIND render? Because I never have it while playing Operation NaPali on XOpenGL.

**Comment by CortexReaver** [comment] 2024-12-03 08:13
> This is a bug with the font objects that get dynamically created not being marked transient, it has nothing to do with the actual renderer, and has since been fixed. It should work as expected in 469e.

Yeah, I've done a little experimenting already to figure this out. In my case this bug is only apparent in one specific mod and in one specific place: https://youtu.be/zZ77mD7nX5s

**Comment by CortexReaver** [comment] 2024-12-04 12:10
this error is still present in 469e

**Comment by SeriousBuggie** [comment] 2024-12-04 15:32
Please upload saves - before this happen and after. Also please make sshot of your settings. First tab about Video. And attach your UnrealTournament.ini if that possible.

**Comment by SeriousBuggie** [comment] 2024-12-04 18:18
Also please ensure you test it properly:
1. Saves which not load with such error broken and can't be loaded.
2. Fixes ensure such saves not created anymore.

So proper testing it is not try load broken save - such saves will never be load. that can't be fixed.
Proper testing - try make broken save. If you can't do such anymore, then fix work.

**Comment by CortexReaver** [comment] 2024-12-05 06:38
I found What the reason was: stationary machine gun. After I used it saves become broken - you can load ANY save perfectly fine, but cannot save anywhere anymore (even if you try to play another mod).
[Save.zip](https://github.com/user-attachments/files/18018483/Save.zip)

**Comment by stijn-volckaert** [comment] 2024-12-05 11:11
I have pushed an improved fix that will be included in the next testing builds

**Closed by stijn-volckaert** 2024-12-05 11:11 UTC
