### ISSUE TITLE
[469c] OpenGL surface selections in Ued are bad

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1329] opened 2023-07-21 21:22 UTC
Selecting surfaces in Ued with OpenGL is not usable. The selection with OpenGL appears to be a big blue solid where you can barely see the texture behind.

Here is a GIF comparison between OpenGL selection and xOpenGL selection:

![OpenGL-selection](https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/b29dd2cc-3f4c-42bf-972f-26660899cc3c)

As you can see xOpenGL selection is much better, its more subtle and the transparency is great, you can see the texture properly. With OpenGL, you can barely see any changes you do to the texture, such as performing basic tasks like scale/rotation/pan.

**Comment by SeriousBuggie** [comment] 2023-07-21 21:30
Duplicate of #823 ?

**Closed** 2023-08-11 16:57 UTC
