### ISSUE TITLE
[469c-RC2] UnrealEd cannot save file

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#855] opened 2022-06-10 11:19 UTC
![UnrealEd_Failed_to_save_file](https://user-images.githubusercontent.com/81397053/173052777-6103dfe0-780b-465b-8442-af83849b74f6.jpg)
Steps to reproduce:
1) Try to open any map where one dependent file is missing.
2) Keep UnrealEd open and move the missing file to its proper place.
3) Repeat step (1). Now UnrealEd loads the map.
4) Try to save the map: the above messages appears and map is not saved.
Editor.log has no helpful entries.

v436 also does NOT save the map but without any hint or warning.

PS: Why aren't files of type "7z" allowed?
[TestNoneSaveableMap.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/8878348/TestNoneSaveableMap.zip)

**Comment by SeriousBarbie** [comment] 2022-06-10 11:23
Maybe related to https://github.com/OldUnreal/UnrealTournamentPatches/issues/548

**Comment by SeriousBuggie** [comment] 2022-07-31 16:05
This happen, because on failed load package (map in this case) happen resource leak. In this case leaked file lock.
So any attempt save or remove such package will fail, since UnrealEd still hold exclusive lock to file.

Duplicate of #578

**Closed** 2023-08-20 11:18 UTC
Labels: UnrealEd
