### ISSUE TITLE
[469b] When increasing the gui scaling factor, it is impossible to play

### ISSUE THREAD

**Issue by Sergiut99** [OldUnreal/UnrealTournamentPatches#742] opened 2022-02-25 07:19 UTC
When i increase this option (gui scaling factor) in patch 469b, the Tournament launch tab with bots in the game disappears. We can't run a tournament Ladder with bots.
In the old version 436, this tab is visible...
windows 7 64 pro

[UMenu.UMenuRootWindow]
ConfiguredGUIScale=1.750000
AutoGUIScale=False
LookAndFeelClass=UMenu.UMenuBlueLookAndFeel

![scale](https://user-images.githubusercontent.com/100404282/155671442-5312580c-222d-43d8-9438-8e2bc069538a.jpg)
![scale2](https://user-images.githubusercontent.com/100404282/155671466-b27d0721-8f16-4d54-98bc-16a55e886ab1.jpg)

**Comment by SeriousBuggie** [comment] 2022-02-25 07:43
Duplicate of #99

**Closed** 2022-03-24 15:10 UTC
Labels: duplicate, fixed in the next patch
