### ISSUE TITLE
Support(error) for old no SSE2 System Pentium III\AthlonXp

### ISSUE THREAD

**Issue by YoshiKill** [OldUnreal/UnrealTournamentPatches#1677] opened 2024-11-30 13:17 UTC
Hello, i have issues with UT patch, its not work in my win xp Pentium III, as i guess its not support processor with out sse2. 
So my request is any chance to add support of sse1 system? Or may be is some version of game or patch is steel support multiplayer with sse1 system?

**Comment by SeriousBuggie** [comment] 2024-11-30 13:34
Duplicate of #587

**Closed by SeriousBuggie** 2024-11-30 13:34 UTC
