### ISSUE TITLE
Issues with BotPack.u

### ISSUE THREAD

**Issue by Riccardoman** [OldUnreal/UnrealTournamentPatches#193] opened 2021-01-16 15:38 UTC
![DM-Hyperion](https://user-images.githubusercontent.com/74624503/104816084-171aef80-5819-11eb-8884-fa00c5968603.jpg)

Getting this error while trying to load DM-Hyperion

**Comment by SeriousBuggie** [comment] 2021-01-17 04:25
Duplicate of #51.

**Closed** 2021-01-17 09:22 UTC
