### ISSUE TITLE
[469b] UnrealEd crash on 3D preview with USoftwareRenderDevice::DrawComplexSurface

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#764] opened 2022-03-17 09:42 UTC
Reproduce:
1. Open UnrealEd.
2. Set Software render on viewport,
3. Set textured view in viewport.
4. Open [DM-XV-BBST-Airport-v1.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/8283503/DM-XV-BBST-Airport-v1.zip)
5. Try fly around,

Expected result: no crash.
Actual result: crash:
```
History: USoftwareRenderDevice::DrawComplexSurface <- URender::DrawFrame <- URender::DrawWorld <- 
UEditorEngine::Draw <- (Cam=U2Viewport0,Flags=1993 <- UWindowsViewport::Repaint <- UEditorEngine::Tick
SE(C0000005) @ 6B30233B
fl=0 rec=0 n=21027124 i[0]=0 i[1]=0
eax=0140e288 ebx=0e4949dc ecx=00000000 edx=ffffffff esi=00000000 edi=0140e288 eip=6b30233b
ebp=0140e0b4 esp=0140dde8 cs=0023 ds=002b es=002b fs=0053 gs=002b flags=00010213
 <- UpdateWorld
```

**Comment by SeriousBuggie** [comment] 2022-03-17 09:47
Look like issue caused by Broken textures in MyLevel.

If used D3D9, then no crash on simple fly.

But next test make crash even on D3D9.

Reproduce:
1. Open [DM-XV-BBST-Airport-v1.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/8283503/DM-XV-BBST-Airport-v1.zip) in UnrealEd.
2. Start new map.
3. Extract cube.
4. Select all surface.
5. Try select first texture in MyLevel (with visible AllGroups).

Expected result: fill with texture.
Actualresult: crash:
```
History: USoftwareRenderDevice::DrawComplexSurface <- URender::DrawFrame <- URender::DrawWorld <- 
UEditorEngine::Draw <- (Cam=U2Viewport2,Flags=1993 <- UWindowsViewport::Repaint <- UEditorEngine::RedrawLevel <- 
UEditorEngine::Exec <- (POLY SET TEXTURE=MyLevel.bla_mocca) <- FEditorHitObserver::ClickHBrowserTexture <- UViewport::ExecuteHits <- UEditorEngine::Click <- WM_BUTTONUP <- UWindowsViewport::ViewportWndProc (Message=WM_LBUTTONUP)
```
You can even use wireframe view - this not prevent crash,

**Comment by SeriousBuggie** [comment] 2022-03-17 09:48
Only 3 testures from MyLevel here is work. All other make crash.

**Comment by SeriousBuggie** [comment] 2022-03-17 09:49
Possible related to #540

**Comment by stijn-volckaert** [comment] 2022-03-25 14:03
Confirmed. It looks like the solid textures in MyLevel are saved without mipmap data. It is not clear to me if this is allowed by the UPackage spec, but both UTPT and wotgrealExporter just create and fill mips with the Palette[0] color. I've pushed a fix for 469c that does the same thing.

**Comment by stijn-volckaert** [comment] 2022-07-25 17:50
Fixed in 469c-RC2

**Closed by stijn-volckaert** 2022-07-25 17:50 UTC
Labels: bug, rendering, fixed in the next patch
