### ISSUE TITLE
[469b] Translucent textures disappear sometimes in DX9/GL

### ISSUE THREAD

**Issue by lafoxxx92** [OldUnreal/UnrealTournamentPatches#610] opened 2021-11-28 21:50 UTC
![image](https://user-images.githubusercontent.com/34402711/143787394-b41152bf-68da-4dca-8f68-b31d3af50806.png)
![image](https://user-images.githubusercontent.com/34402711/143787400-2a8ea4e2-3c46-418d-be46-3ae8eb1b731a.png)
![image](https://user-images.githubusercontent.com/34402711/143787411-6ff61e19-5241-45eb-906d-02086a3f27c4.png)

**Comment by lafoxxx92** [comment] 2021-11-28 21:59
Seems like it doesn't depend which version is used. Same in v436

**Comment by CacoFFF** [comment] 2021-12-06 14:02
The problem is in the level, not the render device.
What you're seeing is a bad surface on the BSP tree.

**Comment by stijn-volckaert** [comment] 2021-12-29 09:24
Thanks for the report. As @CacoFFF said, the map should be fixed instead. There is not much we can do on the renderer side.

**Closed by stijn-volckaert** 2021-12-29 09:24 UTC
Labels: invalid, rendering
