### ISSUE TITLE
[496c] crash/segfault with NW3 mutator

### ISSUE THREAD

**Issue by ahrib** [OldUnreal/UnrealTournamentPatches#1154] opened 2023-01-07 01:48 UTC
Using Nali Weapons 3 with the map CTF-Face-SE causes a segfault within 1-5 minutes of gameplay and the game will crash and terminate.

This occurs with 469c of the patch. Version 469b of the patch runs without issue. Please see attached logs

to reproduce:
play for 1-5 min with the following settings
map: CTF-Face-SE
mutator: [Nali Weapons 3 mutator](https://www.moddb.com/mods/nali-weapons-3/downloads/nali-weapons-3-client-zip-version)

System/Game info:

    Uneal Tournament version: 469c 
    OS: macOS 13.1 (22C65)
    Model Name: MacBook Pro
    Model Identifier: MacBookPro18,3
    Model Number: MKGQ3X/A
    Chip: Apple M1 Pro
    Total Number of Cores: 10 (8 performance and 2 efficiency)
    Memory: 16 GB

Log files:

[469c UnrealTournament.log with segfault](https://github.com/OldUnreal/UnrealTournamentPatches/files/10365270/UnrealTournament.469c.log)

[469b UnrealTournament.log running without issue](https://github.com/OldUnreal/UnrealTournamentPatches/files/10365271/UnrealTournament.469b.log)

**Comment by TankBeef** [comment] 2023-01-07 22:40
Just finished playing 10 minutes CTF-Face-SE with NW3, and no issues. But I am on Win 10. I see you are on a MacBook.

**Comment by an-eternity** [comment] 2023-01-08 00:23
We test v469c with NWIII a lot, in Linux and in Windows, no such issues so far. With this map - no issues too.
It could be something related specifically to v469c macOS build.

**Comment by ahrib** [comment] 2023-01-08 03:34
Thanks @TankBeef  and @an-eternity. I had a couple friends test on Windows and they had no issue also.
Agree looks to be macOS specific.

**Comment by Feralidragon** [comment] 2023-01-08 18:42
Just checked your logs, and it seems that the problem is this:
```
Error: MultiMAmmo CTF-Face-SE.MultiMAmmo7 (Function NWCoreVIII.NaliAmmo.Sleeping.EndState:0068) Accessed array 'Touching' out of bounds (0/0)
Error: MultiMAmmo CTF-Face-SE.MultiMAmmo7 (Function NWCoreVIII.NaliAmmo.Sleeping.EndState:0068) Accessed array 'Touching' out of bounds (1/0)
Error: MultiMAmmo CTF-Face-SE.MultiMAmmo7 (Function NWCoreVIII.NaliAmmo.Sleeping.EndState:0068) Accessed array 'Touching' out of bounds (2/0)
Error: MultiMAmmo CTF-Face-SE.MultiMAmmo7 (Function NWCoreVIII.NaliAmmo.Sleeping.EndState:0068) Accessed array 'Touching' out of bounds (3/0)
Error: MultiMAmmo CTF-Face-SE.MultiMAmmo6 (Function NWCoreVIII.NaliAmmo.Sleeping.EndState:0068) Accessed array 'Touching' out of bounds (0/0)
Error: MultiMAmmo CTF-Face-SE.MultiMAmmo6 (Function NWCoreVIII.NaliAmmo.Sleeping.EndState:0068) Accessed array 'Touching' out of bounds (1/0)
Error: MultiMAmmo CTF-Face-SE.MultiMAmmo6 (Function NWCoreVIII.NaliAmmo.Sleeping.EndState:0068) Accessed array 'Touching' out of bounds (2/0)
Error: MultiMAmmo CTF-Face-SE.MultiMAmmo6 (Function NWCoreVIII.NaliAmmo.Sleeping.EndState:0068) Accessed array 'Touching' out of bounds (3/0)
```

The `Touching` array was a fixed array up until 469b with 4 entries, however starting at 469c this array became dynamic, and can now have any number of entries.

To keep compatibility with mods using the array (such as NW3) this array has been set up in a bit of a special way in order to guarantee that it always had at least 4 accessible entries, even if the array doesn't have any items.

This works with WIndows and Linux, but it seems that for some reason this isn't working in Mac (as seen in the logs above), leading eventually to the segfault crash.

I could fix the mod itself, because using the `Touching` array directly is and has always been a bad way of getting the touching actors, given that there is the `TouchingActors` iterator which is the correct way of doing it (which would be the fix on my side in this case), however this is a big and rather widespread mod, thus doing a new release that justifies the 100+MB download (over 200MB decompressed) and new install in servers, in a game like this, would require me to include a lot more fixes and even potentially throw in some additions in order to make it worthwhile to everyone, and I am currently not planning to do any of that, as I am busy with other projects.

This also means that other mods that also do the same that I am doing, which is actually fairly common, will eventually lead to the same crash as well, with NW3 maybe triggering it more quickly due to the amount of actors it spawns and the amount of process it does and such, so this needs to be fixed in a new game patch regardless.

Therefore, for now, you can keep a 469b install on the side for mods that cause segfaults like this, and wait for a new patch version with the fix for this. :)

**Closed** 2023-05-26 11:34 UTC
Labels: bug, macOS, fixed in the next patch
