### ISSUE TITLE
[469c-RC2] [Galaxy] Extraneous noise when using PulseGun

### ISSUE THREAD

**Issue by Masterkent** [OldUnreal/UnrealTournamentPatches#950] opened 2022-07-23 16:15 UTC
This noise appears quite often with the Galaxy audio subsystem:
https://www.youtube.com/watch?v=GS3DLroeSys

**Comment by an-eternity** [comment] 2022-07-23 18:03
It is old known issue, and happens not only when using PulseGun...
But this driver is considered to be "deprecated", so it is unlikely will be fixed.

**Comment by Masterkent** [comment] 2022-07-23 19:44
There is no such issue in 436. And at this moment I can't see any decent alternatives to this "deprecated" subsystem for playing with headphones. With ALAudio, you have either wrong stereo effect (when HRTF is disabled) or poor sound quality (when HRTF is enabled). With Cluster, some sounds are played at wrong volume.

**Comment by OjitroC** [comment] 2022-07-23 19:49
I reported this in issue 169.  AFAIR it was a 'bug' introduced by the updated Galaxy for 469b - I don't think it was present in 469a and, as already noted, it is certainly not present in 436 or 451 using Galaxy.

**Comment by an-eternity** [comment] 2022-07-24 03:41
It was definitely not present in v469a nor in any earlier versions. It is a regression bug introduced since v469b.
It's been almost 2 years we are waiting for this bug to be fixed, but it seems there are certain obstacles that prevent it to happen... 
So, as already noted - it is unlikely will be fixed. Though, the fact issue #169 still doesn't have "won't fix" tag indicates small chance solution will be found some day exists...

Also, can confirm, in my hardware/software test environments Galaxy produces nicer sound too, comparing with available alternatives... But it is complicated to be objective in this matter, since they all handle the sounds in a different ways, it may happen that familiar/habitual way is being perceived as nicer and more correct, while actually correct way is being perceived as wrong one just because it is not that familiar...

**Comment by stijn-volckaert** [comment] 2022-07-24 08:28
Confirmed duplicate. Let's continue the discussion in #169

**Closed by stijn-volckaert** 2022-07-24 08:28 UTC
Labels: bug, duplicate
