### ISSUE TITLE
[469a] DM-SikUT_1 map crashing

### ISSUE THREAD

**Issue by AtifArshad1995** [OldUnreal/UnrealTournamentPatches#175] opened 2020-12-03 06:40 UTC
Hello folks. I am using the 469a patch and for the most part it is working great. However I am seeing a crash on this map which I used to run fine on patch 436.

http://www.mapraider.com/maps/unreal-tournament/3300/DM-SikUT_1
When I start the map, the game immediately (or sometimes a few seconds after the map loads) becomes "not responding" and the game just hangs. The game doesn't close even with task manager and I have to restart the PC.

**Comment by ZeroKhan1** [comment] 2020-12-08 16:37
Confirmed. The cause are the custom textures in the map. For some reason, if you load map in unrealed in wireframe mode it works. But as soon as you turn on textured mode and one of the custom textures become visible, unrealed freezes. Map causes game to freeze during loading screen. It must be something wrong with the texture.

**Comment by stijn-volckaert** [comment] 2020-12-08 17:00
The download link doesn't work for me

**Comment by ZeroKhan1** [comment] 2020-12-08 17:09
https://unrealarchive.org/maps/unreal-tournament/deathmatch/S/dm-sikut_1_f0fb7682.html

**Comment by OjitroC** [comment] 2020-12-11 08:46
In case it is of interest or relevance, I can run this map fine in 469b and in UEd 2.2 with D3D9.  The  only custom texture in the map is DeveloperT.utx and this renders OK in UEd. So the problem is probably not with the texture per se.

**Comment by CacoFFF** [comment] 2020-12-12 12:57
I am unable to reproduce in my system (Win32, Nov 11 build, UTGLR OpenGLDrv with UsePrecache=True)

**Comment by an-eternity** [comment] 2020-12-12 13:24
In some maps client crashes at start only if it was the first start, if prior to this it already was started at least on 1 other map, this crash will not happen then.
`Assertion failed: Defaults.Num()==GetPropertiesSize() [File:c:\gamedev\utpg\core\inc\UnClass.h] [Line: 585]`
`Windows GetLastError: Not enough storage is available to process this command. (8)`

**Comment by ZeroKhan1** [comment] 2020-12-12 19:29
The crash isn't caused by textures. It's something else. Importing the map and rebuilding with no textures at all still crashes the editor. As soon as it finished rebuilding lights it freezes editor.

**Comment by ZeroKhan1** [comment] 2021-03-11 15:41
469b fixed that crash. Whatever was causing it to crash has been fixed in 469b.

**Closed** 2021-03-11 16:23 UTC
Labels: fixed for 469b
