### ISSUE TITLE
Suggestion: adjustable font in UnrealEd's code window

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1429] opened 2023-10-27 11:15 UTC
A search didn't give results, so I ask: is it possible to make the font (size) in UnrealEd's code window adjustable? We are all getting older and eyes don't get better…

**Comment by SeriousBuggie** [comment] 2023-10-27 13:58
Duplicate of #1317

**Closed by SeriousBuggie** 2023-10-27 13:58 UTC

**Comment by SeriousBarbie** [comment] 2023-10-27 14:41
I knew I already mentioned that. xD
