### ISSUE TITLE
[469b] Unable to scroll trough all texture....stuck.

### ISSUE THREAD

**Issue by iamadeadpixel** [OldUnreal/UnrealTournamentPatches#526] opened 2021-08-21 14:43 UTC
as for example.
botpack texture pack contains tons of textures.
i notice sudenly that i was unable to scroll trough all the texture.
the scrollbar is missing on it.
it is available on all other classes.

i had this isue on the stock version Ued to, not sure if this is a windows 10 problem that couses this.

**Comment by NeonKnightOA** [comment] 2021-08-23 11:43
Stock version as in v436, not v469b/c?

**Comment by spatieman** [comment] 2021-08-23 13:52
yes, 436 has this isue, and the 469b version to, (is there a C ???)
cant test it if it is on win7/xp to  for 469x ,and compatibility mode is a no go not working.

**Comment by stijn-volckaert** [comment] 2021-08-24 11:32
I cannot reproduce this problem on Windows 10/Unreal Tournament 469b. Can you give us some additional information? What are your texture browser settings?

Is your texture browser docked? What size have you selected for the textures (i.e., how many pixels + fixed or variable size)? Is your texture browser maximized? Which renderer are you using for the texture browser?

**Comment by SeriousBuggie** [comment] 2022-06-13 10:26
Not able reproduce it even on v469b. On v469c there be few fixes for this scroll, so possible issue solved for you too.

Anyway, wait for v469c out, for check on your environment.

**Comment by SeriousBuggie** [comment] 2023-01-03 11:29
Please check for v469c and report about results.

**Comment by SeriousBuggie** [comment] 2024-12-23 13:41
Can't reproduce this issue on 469d, e. So will close it.
If you can reproduce it on 469e - feel free reopen it again.

**Closed by SeriousBuggie** 2024-12-23 13:41 UTC
Labels: UnrealEd, info-needed
