### ISSUE TITLE
[469b] Playerhand which holds the weapon goes over the GUI

### ISSUE THREAD

**Issue by Engineer9736** [OldUnreal/UnrealTournamentPatches#729] opened 2022-01-31 21:17 UTC
With some weapons the hand which holds the weapon goes over the GUI.

In case of minigun it's easy to reproduce. Don't know about the other weapons (yet).
![Shot00023](https://user-images.githubusercontent.com/22099136/151874397-f29e619c-2acc-476d-ae78-9b5a6ad7fbb9.png)
![Shot00022](https://user-images.githubusercontent.com/22099136/151874403-e846a640-3315-40e2-8a7d-c25ceae9549b.png)

https://user-images.githubusercontent.com/22099136/151874484-155751fc-86e5-4e07-821c-56fa6b851b7c.mp4

**Comment by Engineer9736** [comment] 2022-01-31 21:21
Same issue with Flak canon and the bio blubber gun. Cheatcode 'loaded' (gives all weapons) is useful for easy testing of this.

![Shot00024](https://user-images.githubusercontent.com/22099136/151874885-42add0dd-bfb3-4664-b997-c2387173bceb.png)
![Shot00025](https://user-images.githubusercontent.com/22099136/151874895-83b0a713-fa88-45f5-8264-b118918c29db.png)

**Comment by Engineer9736** [comment] 2022-02-09 16:51
I see now that this is a duplicate of https://github.com/OldUnreal/UnrealTournamentPatches/issues/5

But i guess my report a good reminder that the issue is still there 1.5 years later.

**Comment by stijn-volckaert** [comment] 2022-02-15 08:33
Indeed. Unfortunately, this is harder to fix than you would expect. I'm going to close this issue since we already had a duplicate of it.

**Closed by stijn-volckaert** 2022-02-15 08:33 UTC
Labels: bug, duplicate, rendering
