### ISSUE TITLE
[469a] bots not performing Godlike in Server

### ISSUE THREAD

**Issue by no0nehere** [OldUnreal/UnrealTournamentPatches#85] opened 2020-10-05 08:33 UTC
Hi there , 
Iam trying to setup a server with 4 Godlike Bots , however they never seem to go past average/skilled level
even though I set the Difficulty in User.ini to 7
when I go online to play I get the following;
![image001](https://user-images.githubusercontent.com/72378011/95057117-343c1e80-0752-11eb-8de7-dde8f28863aa.png)
![image002](https://user-images.githubusercontent.com/72378011/95057125-356d4b80-0752-11eb-8cb7-634819b62adc.png)
![image003](https://user-images.githubusercontent.com/72378011/95057130-3605e200-0752-11eb-8b16-5d42b2a98a19.png)
Bots are average skill level even though set to maximum difficulty.

**Comment by gargul03** [comment] 2020-10-05 12:10
As for `User.ini`:
- `User.ini` difficulty doesn't work for servers, 
what works for servers is to add `?Difficulty=7` parameter to your server's bat script.
- not sure whether this is an issue, or this is just how the game works
- also this happens in earlier versions of UT99 as well for ex 451b, so this is not a 469a specific only issue.


As for the `admin command` thing:

- I'm not sure.

**Comment by no0nehere** [comment] 2020-10-06 00:09
nah doesn't work unfortunately;

`Executing Class Engine.ServerCommandlet
Unreal engine initialized
Browse: DM-Tutorial?Team=0?game=Botpack.DeathMatchPlus?mutator=MapVoteX106k.MapVoteX?Difficulty=7
LoadMap: DM-Tutorial?Team=0?game=Botpack.DeathMatchPlus?mutator=MapVoteX106k.MapVoteX?Difficulty=7`

Still Skilled Bots appear on Server.

**Comment by gargul03** [comment] 2020-10-06 06:04
Well, I must admit that I had no time to check in `469a` but `?Difficulty=7` definately works for me in `451b` server, perhaps you could check whether it works for you in `451b` as well, if it does work then perhaps there is an issue in 469a, but if it does not work for you in 451b neither, that means the issue most probably is at your side.

**Comment by no0nehere** [comment] 2020-10-07 03:33
I run a 469a Server and have never been able to get bots to perform at any other level then skilled/average
its as if , its preset.
perhaps in 469a we could address this problem and be able to freely set bots skill-levels to anything between 1~7
we have a `MultiServer` type setup where Bots are supposedly adjusted depending on `GameType` being played.
for example `InstaGib` / `ComboGib` they should be lower `Difficulty` then say CTF/DM

**Comment by gargul03** [comment] 2020-10-07 07:25
I've checked in 469a right now and `?Difficulty=7` works for me, bots are on godlike.

**Comment by no0nehere** [comment] 2020-10-08 03:16
Could you check in your server browser that they are indeed GodLike?
This time round by browser reports that they are GodLike.
![Godlike](https://user-images.githubusercontent.com/72378011/95410888-a3e42080-0981-11eb-83a3-6fe8e36fd541.png)

**Comment by an-eternity** [comment] 2020-10-08 04:18
![server-test_bot-difficulty](https://user-images.githubusercontent.com/72374425/95414361-61492680-0936-11eb-8568-b0309e8bbcf0.jpg)
What was the solution?

**Comment by gargul03** [comment] 2020-10-08 09:25
> no0nehere : Could you check in your server browser that they are indeed GodLike?

Sure: they are skilled, in both 436 & 469a clients.

**Comment by gargul04** [comment] 2020-10-14 13:00
For me `user.ini` difficulty setting does not work for servers.
What works for me is adding`?Difficulty=7` parameter in server bat command, it works in both `451b` and `469a`

> no0nehere : Could you check in your server browser that they are indeed GodLike?

Sure, it's showing "Skilled".

**Comment by garry-ut99** [comment] 2020-10-20 08:00
Setting difficulty in User.ini doesn't work for me,
what works for me is to add `?Difficulty=7` to a server command line bat, it works both in 451b & 469a.

> https://github.com/OldUnreal/UnrealTournamentPatches/issues/85#issuecomment-705304707 : no0nehere : Could you check in your server browser that they are indeed GodLike?

I've checked and it shows "Skilled".

**Comment by SeriousBuggie** [comment] 2021-03-07 20:53
I can't understand what exactly the problem is.

1. Bots do not play like godlike, while in the settings is godlike?

2. Bots play like godlike, but the server list says they are not godlike?

You are relying on the information from the browser as correct, but the information from the server console is incorrect.

While everything can be the other way around. So first you need to find out how bots actually play in order to understand what the problem is.

**Comment by SeriousBuggie** [comment] 2021-03-07 21:23
I make small test. Improved DM-Deck16][ for bots started as multiplayer server. 4 min players (1 human + 3 bots).
One try with Godlike bots. Second with Skilled bots.
Before start match I checked Browser for LAN games. Both say me "Skilled" in Bots skills.
Godlike setup:
![scr_1615152098](https://user-images.githubusercontent.com/70026933/110255354-e4c97b00-7f9b-11eb-840e-d9e00c69e0c4.png)
Skilled Setup:
![scr_1615152134](https://user-images.githubusercontent.com/70026933/110255367-f6ab1e00-7f9b-11eb-831f-2a862ece5585.png)
First be not easy. Second be easy.
So I can say no any problem with bots skills.
Exists problem for report properly value to clients.

**Comment by an-eternity** [comment] 2021-03-07 22:11
To get it "Godlike", Difficulty in 'ChallengeBotInfo' must be 11...

**Comment by SeriousBuggie** [comment] 2021-03-07 22:41
Look at this code https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/DeathMatchPlus.uc#L240
```
	if ( Difficulty >= 4 )
	{
		bNoviceMode = false;
		Difficulty = Difficulty - 4;
	}
	else
	{
		if ( Difficulty > 3 )
		{
			Difficulty = 3;
			bThreePlus = true;
		}
		bNoviceMode = true;
	}
```
And on this: https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/DeathMatchPlus.uc#L816
```
	if ( Difficulty >= 4 )
	{
		bNoviceMode = false;
		Difficulty = Difficulty - 4;
	}
	else
	{
		if ( Difficulty > 3 )
		{
			Difficulty = 3;
			bThreePlus = true;
		}
		bNoviceMode = true;
	}
```
But report skill very straight:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/DeathMatchPlus.uc#L1512
```
	if(MinPlayers > 0)
		Resultset = ResultSet$"\\botskill\\"$class'ChallengeBotInfo'.default.Skills[Difficulty];
``` 
First thing about "Ladder" so it about UT played in campaign. Not our case.
Second thing about servers. Our case.

As we see `Difficulty` prepared and changed for internal use.
So for proper send to clients need reassemble it back from piece, or (better) use original value.
Original values before transformations:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/DeathMatchPlus.uc#L814
```
Difficulty = BotConfig.Difficulty;
```

So for fix need change line:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/DeathMatchPlus.uc#L1512
```
Resultset = ResultSet$"\\botskill\\"$class'ChallengeBotInfo'.default.Skills[Difficulty];
```
to
```
Resultset = ResultSet$"\\botskill\\"$class'ChallengeBotInfo'.default.Skills[BotConfig.Difficulty];
```

In best tradition of UT code stuff duplicated so you need also change line:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/TeamGamePlus.uc#L887
```
		Resultset = ResultSet$"\\botskill\\"$class'ChallengeBotInfo'.default.Skills[Difficulty];
```
to
```
		Resultset = ResultSet$"\\botskill\\"$class'ChallengeBotInfo'.default.Skills[BotConfig.Difficulty];
```

**Comment by an-eternity** [comment] 2021-03-08 06:54
Yes...
Also, i wonder what was an idea of the lines 823..827, and how that code should normally look like...

**Comment by SeriousBuggie** [comment] 2021-03-08 12:37
Look like this Code written when `Difficulty` be `float`, not a `byte`. So 3.5 is be legal value. But with time it changed to `byte` and code copied. It can be rewritten as:
```
	bNoviceMode = Difficulty < 4;
	if ( !bNoviceMode )
		Difficulty = Difficulty - 4;
```
But, in general, original code work same but look more cryptic ans contain unused parts.

About `bThreePlus` read comment here:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/Bot.uc#L48
```
var		bool		bThreePlus;		// high skill novice
```
Only one usage:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/Bot.uc#L779
```
		if ( bThreePlus )
			MaxDesiredSpeed = 1;
		else
			MaxDesiredSpeed = 0.5 + 0.1 * skill;
```
Currently `bThreePlus` never can be true, but this is does not matter because line above located inside `if ( bNovice )` block.

**Comment by an-eternity** [comment] 2021-03-08 15:19
Understood, everything is clear now.

**Comment by stijn-volckaert** [comment] 2021-03-29 09:30
Merged Buggie's fixes for 469c.

**Comment by an-eternity** [comment] 2021-03-30 18:54
Admins that run XServerQuery will also have to update it to [version 2.04 fixed by Deaod](https://ut99.org/viewtopic.php?f=34&t=6061&start=15), since it was a copy-pasted bug in XServerQuery.

**Closed** 2021-07-08 14:03 UTC
Labels: UnrealScript, bug, fixed in the next patch
