### ISSUE TITLE
[469c] Improvement: add timestamp to log messages

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1115] opened 2022-11-07 12:28 UTC
Most log messages are without a time stamp; recently I found in server's log

> [02:10:03] Received 8 packets from (IP removed)
[02:10:03] (IP removed)  is blocked for  5  seconds
[02:10:03] Last Packet: \status\

with a time stamp, but without a date.
So it would be nice if all log messages would have a (full) time stamp in ISO format like 2022-11-07 13:26:02. Optimal would be if format could be given in an INI file.

**Comment by stijn-volckaert** [comment] 2023-05-27 08:36
Duplicate of #643

**Closed by stijn-volckaert** 2023-05-27 08:36 UTC
Labels: duplicate, enhancement
