### ISSUE TITLE
[469a] XOpenGL: Operation Na-Pali weapon bar renders incorrectly

### ISSUE THREAD

**Issue by DerTodIstEinDandy** [OldUnreal/UnrealTournamentPatches#74] opened 2020-10-03 23:51 UTC
Mod: Operation Na-Pali
With XOpenGL driver:
![Shot00003](https://user-images.githubusercontent.com/5481435/95003702-4dc25680-05ea-11eb-96bd-65aa51dc4caa.png)

With OpenGL driver:
![Shot00004](https://user-images.githubusercontent.com/5481435/95003856-777c7d00-05ec-11eb-8ed9-feb20988e54d.png)

System: Windows 10 x64
GPU:  GeForce GTX 1060

XOpenGL config:

```
[XOpenGLDrv.XOpenGLRenderDevice]
AlwaysMipmap=False
ShareLists=False
DetailTextures=True
MacroTextures=True
BumpMaps=True
DescFlags=0
Description=GeForce GTX 1060 6GB/PCIe/SSE2
Coronas=True
ShinySurfaces=True
VolumetricLighting=True
RefreshRate=60
UseSinglePass=True
UseTrilinear=True
UsePrecache=False
NoFiltering=False
LODBias=0.000000
GammaCorrectScreenshots=False
GammaOffsetScreenshots=0.700000
MaxAnisotropy=8.000000
HighDetailActors=True
UseOpenGLDebug=False
DebugLevel=1
UseAA=False
NumAASamples=4
NoAATiles=True
UseBufferInvalidation=False
NoBuffering=False
GenerateMipMaps=False
OpenGLVersion=Core
NoDrawSimple=False
NoDrawTile=False
NoDrawGouraudList=False
NoDrawGouraud=False
NoDrawComplexSurface=False
UseHWClipping=False
UseHWLighting=False
UseBindlessTextures=False
SyncToDraw=False
UsePersistentBuffers=False
UseVSync=Off
```

**Comment by Chamberly** [comment] 2020-10-04 09:16
Just to confirm the mod, you got it from here, correct? https://www.moddb.com/mods/operation-na-pali

**Comment by DerTodIstEinDandy** [comment] 2020-10-04 20:05
More likely, from here, some years ago: https://unrealarchives.com/operation-na-pali/
onp130nu.zip, the non-umod version

For the record, the same issue was reported here as well: https://www.oldunreal.com/cgi-bin/yabb2/YaBB.pl?num=1600846518/16#16

**Comment by stijn-volckaert** [comment] 2020-10-05 18:38
This is almost certainly a duplicate of issues #44 #29 #38 #60. This issue will be fixed in 469b

**Closed** 2021-03-10 23:26 UTC
Labels: duplicate, rendering, fixed in the next patch
