### ISSUE TITLE
SIGSEGV while "./ucc-bin-x86 compress relicsbindings.u"

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1674] opened 2024-11-27 12:48 UTC
Just installed OldUnreal-UTPatch469eRC2-Linux-x86, tried to compress newer files and ended with multiple SIGSEGV.
`./ucc-bin-x86 compress relicsbindings.u`

WARNING: using preference directory: /home/ut99/.utpg/System/
WARNING: Using system ini file: /home/ut99/ut-server/h2971201/8888/System/UnrealTournament.ini
WARNING: Using user ini file: /home/ut99/.utpg/System/User.ini
=======================================
ucc.exe: UnrealOS execution environment
Copyright 1999 Epic Games Inc
=======================================

Executing Class IpDrv.CompressCommandlet
Compressing relicsbindings.u (582 bytes)
stage 0: 0.000045 secs
Used 4 threads.

Developer Backtrace:
[ 1]  /home/ut99/ut-server/h2971201/8888/System/Core.so(_Z12HandleSignali+0xca) [0xf784076a]
[ 2]  linux-gate.so.1(__kernel_sigreturn+0) [0xf7f04560]
[ 3]  /home/ut99/ut-server/h2971201/8888/System/Engine.so(_ZN9FCodecBWT6EncodeER8FArchiveS1_P12FCodecNotify+0x386) [0xf7b54d56]
[ 4]  /home/ut99/ut-server/h2971201/8888/System/Engine.so(_ZN10FCodecFull4CodeER8FArchiveS1_iiM6FCodecFiS1_S1_P12FCodecNotifyES4_+0x376) [0xf7b53866]
[ 5]  /home/ut99/ut-server/h2971201/8888/System/Engine.so(_ZN10FCodecFull6EncodeER8FArchiveS1_P12FCodecNotify+0xc3) [0xf7b53253]
[ 6]  /home/ut99/ut-server/h2971201/8888/System/IpDrv.so(_ZN19UCompressCommandlet4MainEPKw+0x776) [0xf73aed66]
[ 7]  ./ucc-bin-x86() [0x804cfb5]
[ 8]  /lib/i386-linux-gnu/libc.so.6(+0x21519) [0xf741f519]
[ 9]  /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0x93) [0xf741f5f3]
[10]  ./ucc-bin-x86() [0x804c5a2]
Signal: SIGSEGV [segmentation fault]
Aborting.

Executing UObject::StaticShutdownAfterError
Signal: SIGSEGV [segmentation fault]

History: FCodecBWT::Encode <- FCodecFull::Code <- FCodecFull::Encode <- UCompressCommandlet::Main

Exiting due to error
Segmentation fault (core dumped)

**Comment by SeriousBuggie** [comment] 2024-11-27 14:03
That will be fixed for next test build.
However make .uz file for this .u files is bad idea. It will crash 436 clients.
More info :https://github.com/OldUnreal/UnrealTournamentPatches/issues/656

Proper solution - not compress it and put last into packages list on the server.

**Closed** 2024-11-27 14:06 UTC
Labels: bug

**Comment by SeriousBarbie** [comment] 2024-11-27 14:30
My solution is to compare sizes AFTER compression and remove UZ if it is bigger than uncompressed.

**Comment by SeriousBarbie** [comment] 2024-11-27 14:39
Compression of
`System/relicsbindings.u
System/OldUnreal469c.u
System/Fire.u
System/de.u`
also fail.

**Comment by SeriousBuggie** [comment] 2024-11-27 19:27
Can't reproduce:
```
Executing Class IpDrv.CompressCommandlet
Compressing relicsbindings.u (582 bytes)
stage 0: 0.000035 secs
Used 12 threads.
stage 1: 0.001474 secs
stage 2: 0.000044 secs
stage 3: 0.000282 secs
Total: 0.001835 secs
Compressed relicsbindings.u -> relicsbindings.u.uz (115%)
```
```
Executing Class IpDrv.CompressCommandlet
Compressing OldUnreal469c.u (9469 bytes)
stage 0: 0.000094 secs
Used 12 threads.
stage 1: 0.001976 secs
stage 2: 0.000297 secs
stage 3: 0.000504 secs
Total: 0.002871 secs
Compressed OldUnreal469c.u -> OldUnreal469c.u.uz (42%)
```
```
Executing Class IpDrv.CompressCommandlet
Compressing Fire.u (19278 bytes)
stage 0: 0.000117 secs
Used 12 threads.
stage 1: 0.002469 secs
stage 2: 0.000472 secs
stage 3: 0.000674 secs
Total: 0.003732 secs
Compressed Fire.u -> Fire.u.uz (32%)
```
```
Executing Class IpDrv.CompressCommandlet
Compressing de.u (72169 bytes)
stage 0: 0.000297 secs
Used 12 threads.
stage 1: 0.003782 secs
stage 2: 0.001434 secs
stage 3: 0.001661 secs
Total: 0.007174 secs
Compressed de.u -> de.u.uz (26%)
```
Ensure you use latest test build. Which is 838 right now.
