### ISSUE TITLE
[469a] Xconsole is not working anymore

### ISSUE THREAD

**Issue by nurps** [OldUnreal/UnrealTournamentPatches#198] opened 2021-01-23 12:05 UTC
http://www.unrealize.co.uk/index.php?files

**Comment by stijn-volckaert** [comment] 2021-01-24 11:09
I use XConsole myself and have never had any issues with it. Is it installed correctly (i.e., did you set it as the console type in UnrealTournament.ini)?

**Comment by nurps** [comment] 2021-01-24 11:11
I assume it is since it worked before the update. Odd.

**Comment by nurps** [comment] 2021-01-24 11:48
Ok tried on a different server, there it works, so the server must have changed something.

**Comment by alsosed** [comment] 2021-01-26 10:50
> 
> 
> Ok tried on a different server, there it works, so the server must have changed something.

Servers on which NewNet or UTPure is installed can block third-party consoles

**Comment by Chamberly** [comment] 2021-01-30 05:05
I use xConsole a lot and I do not have any issue. Tell me which server to check out.

**Comment by stijn-volckaert** [comment] 2021-01-30 13:16
I'm going to close this one for now as we cannot reproduce the problem. Feel free to comment if you have new information

**Closed by stijn-volckaert** 2021-01-30 13:16 UTC
Labels: invalid
