### ISSUE TITLE
[469c] OSX/Mac version crashes, Assertation Failed Message

### ISSUE THREAD

**Issue by cash68** [OldUnreal/UnrealTournamentPatches#1240] opened 2023-04-22 15:46 UTC
Followed the read me, this is the error I get:

"Assertion failed: GetPropertiesSize()>=sizeof(UObject) [File:/Users/stijn/UnrealTournament/Core/Src/UnClass.cpp] [Line: 1241]

History: UClass::Serialize <- LoadObject <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::Preload <- ULinkerLoad::CreateExport <- IndexToObject <- ULinkerLoad<<UObject <- ULevelBase::Serialize <- ULevel::Serialize <- LoadObject <- ULinkerLoad::Preload <- PreLoadObjects <- UObject::EndLoad <- UObject::StaticLoadObject <- LoadLevel <- UGameEngine::LoadMap <- UGameEngine::Init <- InitEngine <- main"

Not sure what any of this means.   Running a Mac Pro 5.1 running Mojave.

**Comment by stijn-volckaert** [comment] 2023-05-02 09:01
This is most likely a duplicate of #453. You always get this error if the game attempts to load an outdated version of one of the base .u packages. Did you accidentally copy the entire System folder of an older game version into ~/Library/Application Support/UnrealTournament?

**Closed** 2023-05-27 08:50 UTC
Labels: info-needed
