### ISSUE TITLE
[469b] Game startup with a non default map, no x axis mouse control

### ISSUE THREAD

**Issue by n0cc3r** [OldUnreal/UnrealTournamentPatches#712] opened 2022-01-12 18:09 UTC
I use Deck 16 as my starting map, mouselook on, there is just turning around, but no look up/down.

**Comment by SeriousBuggie** [comment] 2022-01-12 18:58
Need more info for reproduce issue. Possible need show you settings about input in UT.

**Comment by n0cc3r** [comment] 2022-01-12 19:09
What input settings exactly, from ut.ini or user.ini?

**Comment by SeriousBuggie** [comment] 2022-01-12 19:11
This ones:
![img](https://user-images.githubusercontent.com/70026933/149206188-13f04402-3480-4f97-8992-5581f4117dd9.png)

**Comment by n0cc3r** [comment] 2022-01-12 19:16
There you go

![ss](https://user-images.githubusercontent.com/8649691/149206753-e7032c53-b545-474e-b468-854cabaa24a8.jpg)

**Comment by SeriousBuggie** [comment] 2022-01-12 19:19
What about different input, like `Cursor` and other?
What about different smoothing?

**Comment by Engineer9736** [comment] 2022-01-12 22:14
I've noticed this as well a few weeks ago when i was developing a mutator. I used a batch script to remove my .u file, ucc make the new one, and start UT with it for fast development cycles.

I just tested it and got it reproduced right away. If you put this in a batch file like UnrealTournamentDeck.bat

UnrealTournament.exe DM-Deck16][

Double click the bat file, and you'll see what n0cc3r meant.

**Comment by SeriousBuggie** [comment] 2022-01-12 22:35
I make `test_bug.bat` inside `System`, put into it `UnrealTournament.exe DM-Deck16][`, double click on it and no any problem with mouse. both axis work as should.

**Comment by Engineer9736** [comment] 2022-01-12 22:51
I’ll have a look tomorrow whether i can find some more details on reproducing it. If i don’t forget it at least.

**Comment by SeriousBuggie** [comment] 2022-01-12 23:07
Well. I able reproduce it on v469b, but only if use DirectInput. On other types - no issue.
Also on v469c I not able reproduce it. So look like issue fixed for v469c.

**Comment by SeriousBuggie** [comment] 2022-01-13 10:45
Duplicate of #284

**Comment by n0cc3r** [comment] 2022-01-14 10:53
I used now "cursor" instead of DirectInput, it works.

Actually this is not "exactly" a duplicate of #284 
Pardon me, i did not mean to start MP or SP with a map, i was talking about starting the game using 

[URL]
LocalMap=DM-Deck16][.unr
instead of the intro map

**Comment by SeriousBuggie** [comment] 2022-01-14 12:08
I think this not make big difference with specify map name in command line.

I think important is instant start map, so (possible) break some order of initialization for DirectInput and one axis is broken. Anyway need wait release v469c for check it fixed for you, or not.

**Comment by Engineer9736** [comment] 2022-01-14 13:32
Do you maybe know when to expect the v469c release (just a rough estimate)? 🙂

**Comment by an-eternity** [comment] 2022-07-22 00:38
Either wrong title or wrong description here...
No X-axis mouse control means - no turning around, but not "no look up/down".

X-axis mouse control bug is still not fixed. It occurs randomly at startup even if startup map is set to default CityIntro map and Mouse Input mode is set to Cursor.
For now player has 2 ways to bypass this bug:
1. Try to restart (may need to do this several times).
2. Minimize/maximize several times.

Is this going to be fixed before v469c final release?

**Comment by stijn-volckaert** [comment] 2022-07-24 09:04
Duplicate of #284. We will continue the discussion there

**Closed by stijn-volckaert** 2022-07-24 09:04 UTC
Labels: bug, duplicate, Windows
