### ISSUE TITLE
[469c-RC4] the skins are displayed twice on the player windows

### ISSUE THREAD

**Issue by Letylove49** [OldUnreal/UnrealTournamentPatches#1038] opened 2022-08-28 17:24 UTC
![Shot00169](https://user-images.githubusercontent.com/110738647/192087734-c669c6b3-cd26-4b4e-938f-45bc6b67bac5.png)
I notice with the patch 469c RC4 the skins are displayed twice  and others are not displayed at all anymore.
This works properly with RC3.

Opengl : here my setting i hope that willl help you

`OpenGLDrv.OpenGLRenderDevice]
NoAATiles=True
NumAASamples=4
UseAA=True
SmoothMaskedTextures=False
UseShaderGamma=True
FrameRateLimit=0
UtiliserMultiDrawArrays=True
UtiliserGouraud469=Vrai
ShaderAlphaHUD=True
DetailMax=2
RefreshRate=0
MaxAnisotropy=0
Use16BitTextures=Faux
UseHDTextures=True
UtiliserTrilinéaire=Vrai
UsePrecache=True
UsePalette=True
OneXBlending=False
GammaCorrectScreenshots=Faux
GammaOffsetBlue=0.000000
GammaOffsetGreen=0.000000
GammaOffsetRed=0,000000
GammaOffset=0.100000
LODBias=0,000000
DescFlags=1
Description=
DebugBits=-1
VolumetricLighting=False
ShinySurfaces=True
Coronas = Vrai
HighDetailActors=True
DetailTextures=True
AlwaysMipmap=True
SwapInterval=1
SmoothMasking=True
ColorCorrectionMode=UseFramebuffer
ContextType=AutoDetect
UtiliserLightmapAtlas=True
UtilisationGeométrie=Faux
ForceNoSmooth=Faux `

**Comment by SeriousBuggie** [comment] 2022-09-26 11:11
Duplicate of #1025

**Closed** 2022-10-24 00:43 UTC
Labels: bug, duplicate, fixed in the next patch
