### ISSUE TITLE
More context for Undo/Redo options

### ISSUE THREAD

**Issue by Neob91** [OldUnreal/UnrealTournamentPatches#1566] opened 2024-04-22 06:55 UTC
It would be nice if the Undo and Redo options said what it is that you're redoing (e.g. "Undo clip brush", "Undo move Light" or "Redo subtract").

**Comment by SeriousBuggie** [comment] 2024-04-22 08:04
Duplicate of #1205

**Closed by SeriousBuggie** 2024-04-22 08:04 UTC
