### ISSUE TITLE
[469a] unrealed crash when deleting many actors

### ISSUE THREAD

**Issue by zero-khan** [OldUnreal/UnrealTournamentPatches#143] opened 2020-10-31 03:12 UTC
unrealed crashes or takes way too much time to delete too many actors. Select thousands of brushes or actors, it takes too much time to delete.

**Comment by SeriousBuggie** [comment] 2020-10-31 08:05
Not crash for me. But really long action. On the contrary, adding actors is more faster. Or hiding them. Or set property to its.

Maybe some things run not optimal.

**Comment by SeriousBuggie** [comment] 2020-10-31 09:14
Now got crash:
```
---------------------------
Critical Error
---------------------------
Assertion failed: Result!=LB_ERR [File:C:\GameDev\utpg\Window\Inc\Window.h] [Line: 4512]

History: WListBox::FindItemChecked <- FTreeItem::GetRect <- FTreeItem::Redraw <- FPropertyItem::OnItemSetFocus <- WProperties::SetItemFocus <- WProperties::OnSize <- WM_SIZE <- MessagePump <- MainLoop
---------------------------
ОК   
---------------------------
```
Attempt delete 411 SpecialEvent.

**Comment by CacoFFF** [comment] 2020-10-31 12:56
If you're deleting NavigationPoints, then you may have to wait a bit more, the editor in v469 does ReachSpec cleanup when navigation points are removed.
This was done to prevent crashes due to mappers removing paths and not rebuilding their path network.

**Comment by CacoFFF** [comment] 2020-10-31 13:28
But I did find that the editor is already performing a standard general cleanup for each deleted actor...
So if we delay the cleanup to the very end of bulk deletion... everything takes less than half a second to delete.
Thanks for the report.

**Comment by CacoFFF** [comment] 2020-10-31 13:30
Note: for specific unrealed crashes (where you get a message) please open a new bug report.

**Comment by SeriousBuggie** [comment] 2020-11-05 13:25
Speed of delete fixed in v469b. Confirmed.

**Closed** 2021-03-10 23:24 UTC
Labels: UnrealEd, fixed for 469b
