### ISSUE TITLE
[win][469a] XOpenGL performance issues / lags / delays / fps drops both in-game and in the menu

### ISSUE THREAD

**Issue by garry-ut99** [OldUnreal/UnrealTournamentPatches#114] opened 2020-10-15 21:15 UTC
As per this incident: https://ut99.org/viewtopic.php?p=123376#p123376

I have no intention of spamming.
Just recreating the issue to keep integrity of the bug tracker.
The original thread link shows now 404: https://github.com/OldUnreal/UnrealTournamentPatches/issues/49
Can't restore comments coz nobody remembers them, 
but it was a long thread: 25 comments,
from several people experiencing the issue,
and the thread / issue has been labeled as `video` + `fixed for 469b`

One of players experiencing the issue:

> https://ut99.org/viewtopic.php?p=123270#p123270 : Raynor :
 Additionally I noticed framerate can take noticeable dip during some situations like when you gib foes with combos (could be my aging hardware, but still it's rock solid with Chris Dohnal's OpenGL 3.7)

**Comment by garry-ut99** [comment] 2020-11-02 08:49
@SeriousBuggie @stijn-volckaert 
- I know this is rather fixed, but it's important and big issue, would you guys mind to recreate (some of) your comments, after github doing shit here
- I rememeber SeriousBuggie doing some benchmarks wherein he got FPS drops on some map and also talking about 1 sec lag with compatibility enabled
- unfortunately I don't rememebr stijn-volckaert's comments, perhaps he does remember

**Comment by SeriousBuggie** [comment] 2020-11-05 15:05
Need test all things from scratch.

As I test lists in UWindows in v469b - all better. When list visible FPS drop near 5 from 60, not 30 from 60.

All other stuff I think need be recreate as separte issues if still exists.

In general I think in v469b most mentioned things is improved. So better close this issue after public out v469b and open new ones per problem if some things happen.

**Comment by garry-ut99** [comment] 2020-11-05 16:43
No one knows for sure whether it has been a single / same problem affecting all aspects of the game or if it were different / separate issues, hence I don't want to spam issue tracker with similiar performance issues in case they turn out to be the same / single issue nor I want to open (spam) a new issue exclusively for 469b, given the fact the root of the issue\s  has been in 469a. I will create separate issues only if the developers decide so.

**Comment by SeriousBuggie** [comment] 2020-11-05 17:18
Because you not know what going on, best assumption is "this is different issues" if few conditions met:
1. no things pointed "this is same issue":  same error messages, crash on same place and so on.
2. need different steps for reproduce.

**Comment by garry-ut99** [comment] 2020-11-06 08:50
> Because you not know what going on, best assumption is:

Then why the admin hasn't asked us to separate these problems into separate reports ... and has been continuing in the same thread ... perhaps he hasn't been sure either.

**Closed** 2021-03-10 23:25 UTC
Labels: bug, fixed for 469b, video

**Comment by garry-ut99** [comment] 2021-03-19 13:38
With patch 469b, someone still has issues:

> Alcoholodeck16 : https://ut99.org/viewtopic.php?f=1&t=14127&start=135#p127336 : I still have performance issues with XOpenGL. I still get brutal FPS Drops on Win 10, RX 480 and Intel i5 4460. Maybe i should go back to utglr. I wonder if this is actually an AMD issue. OpenGL performance doesn't seem as good as it used to be.

and the reply:

> Gustavo6046 : https://ut99.org/viewtopic.php?f=1&t=14127&start=135#p127337 : XOpenGL uses newer OpenGL versions (3.0+), which replace the standard conventional pipeline of 3D rendering with a purely shader-based one. When Unreal Tournament was written, shaders weren't a thing. I fear XOpenGL is not optimized for shader-based rendering, even though it uses primarily that (as it has to, to enjoy the more modern features of OpenGL 3.0 and above). I do vividly remember Anth commenting on the renderer not being very well optimized.
> 
> It does still come with the updated OpenGLDrv, if I recall correctly. True and tested, and most importantly, fast :>

**Comment by garry-ut99** [comment] 2021-03-20 12:31
Another person having issues:

> Eternity : https://ut99.org/viewtopic.php?f=1&t=14127&start=180#p127466 : 
> 
> > Alcoholodeck16 wrote:
> > I still have performance issues with XOpenGL. I still get brutal FPS Drops on Win 10, RX 480 and Intel i5 4460. Maybe i should go back to utglr. I wonder if this is actually an AMD issue. OpenGL performance doesn't seem as good as it used to be. 
> 
> With RX 480 no one OGL or XOGL driver works well enough - in the best case it works without random lags, but performance is relatively low always.
> D3D9 driver should be used instead, the one from the latest v469b works perfectly.

**Comment by stijn-volckaert** [comment] 2021-03-22 01:45
We are still working on optimizations for XOpenGLDrv. People with mid- to high-end GPUs will see some pretty substantial performance improvements in the next version. We will probably release a snapshot of XOpenGLDrv on GitHub well before the next patch so you can get a chance to check it out.

That said, XOpenGL is still significantly slower than UTGLR OpenGLDrv, and this is not going to change soon. Our upcoming version is, however, much faster than UTGLR D3D9Drv.
