### ISSUE TITLE
[469a] Trying to Spawn specific bots into online match failing.

### ISSUE THREAD

**Issue by no0nehere** [OldUnreal/UnrealTournamentPatches#91] opened 2020-10-07 13:37 UTC
Hi there, Offiline I can spawn specific bots using the following bind,
`set input NumPad0 addbotnamed Arachne|addbotnamed Malakai`
however if I use this bind online as follows;
`set input NumPad0 admin addbotnamed Arachne|admin addbotnamed Malakai` then only on rare occasions will these specific bots spawn on the server.

**Comment by stijn-volckaert** [comment] 2020-10-08 14:08
Confirmed. However, I see no difference between offline and online play. You can only spawn each bot once, even if you have removed it from the game.

**Comment by SeriousBuggie** [comment] 2021-03-07 23:21
Can not reproduce issue on usual MP server:
```
Buggie became a server administrator.
> admin addbotnamed Malakai
Malakai entered the game.
You were killed by Malakai!
Buggie ate Malakai's burning plasma death.
Malakai drew first blood!
> admin addbotnamed Cali
Cali entered the game.
> admin addbotnamed Arachne
Arachne entered the game.
> admin addbotnamed Tamerlane
Tamerlane entered the game.
Tamerlane ate Cali's burning plasma death.
Cali was smacked down by Tamerlane's Rocket Launcher.
Tamerlane was smacked down by Malakai's Rocket Launcher.
```
Same for dedicated MP server:
```
Buggie became a server administrator.
> addbotnamed Malakai
Can't added named bots from client.
> admin addbotnamed Malakai
Malakai entered the game.
> admin addbotnamed Cali
Cali entered the game.
> admin addbotnamed Arachne
Arachne entered the game.
> admin addbotnamed Tamerlane
Tamerlane entered the game.
```
In code I not any problems with this stuff.

Also you must understand how this thing work:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/TournamentPlayer.uc#L85
```
exec function AddBotNamed(string BotName)
{
	if ( Level.NetMode == NM_Client )
	{
		ClientMessage("Can't added named bots from client.");
		return;
	}

	if ( DeathMatchPlus(Level.Game) != None )	
		DeathMatchPlus(Level.Game).BotConfig.DesiredName = BotName;
	Level.Game.ForceAddBot();
}
```
So on run your command desired bot name stored in special field and call function for add bot.
Later:
https://github.com/Slipyx/UT99/blob/f2ebd703845075a2d667e8e3f2f71a5e7f187610/Botpack/ChallengeBotInfo.uc#L194
```
function int ChooseBotInfo()
{
	local int n, start;

	if ( DesiredName != "" )
	{
		for ( n=0; n<32; n++ )
			if ( BotNames[n] ~= DesiredName )
			{
				DesiredName = "";
				return n;
			}
		DesiredName = "";
	}
```
When chooses info for bot, script pick up this name and use it for find in bots configs.
So when you type this message on server you must sure about presence this name in bot config array.

If there no such name then this name simple ignored and appear random bot.

**Comment by SeriousBuggie** [comment] 2021-03-07 23:29
I even try reproduce issue use your bind commands. With thought "maybe problem in how sended 'admin bla-bla' command with pipe..."

Nope. Still same result. When I press NumPad0 on MP server appear two bots: Arachne and Malakai.

**Comment by SeriousBuggie** [comment] 2021-03-08 00:03
Also, as Anth write, each config after usage marked as used and not used anymore.

Exactly happens next:
1. When config used ConfigUsed bit is set. Bot enter to game.
2. When bot exit from server this bit not cleared.
3. If you try add bot with ConfigUsed bit set name of bot replaced to "Bot" but other config used.
4. If all 32 bot configs used, then all next bots will use last 32 config.

So if you try add Cali twice, you get second Cali same as Cali but with name "Bot" instead of "Cali".
If you try do this in third time then appear random bot because "Cali" name not found in config list (previously "Cali" now with name "Bot").

When you call your command on real server possible situation this bot already be on this match but kicked out by enter player.
If players often in/out to server possible use all bots config at all. All next Botss will be with name "Bot" and appended numbers, if appears few of them in one time.

As solution of this issue flag ConfigUsed can be cleared when bot destroyed.
But IDK need this or no.
Clear this flags can lead to reuse bots configs. Without that each new bot is "fresh" and this make rotation of bots.

**Comment by SeriousBuggie** [comment] 2021-03-08 00:17
```
function Destroyed()
{
	if (DeathMatchPlus(Level.Game) != None)
	{
		for ( n=0; n<32; n++ )
			if ( DeathMatchPlus(Level.Game).BotConfig.BotNames[n] == PlayerReplicationInfo.PlayerName )
			{
				DeathMatchPlus(Level.Game).BotConfig.ConfigUsed[n] = 0;
				break;
			}
	}
	Super.Destroyed();
}
```
Such code (not tested) can be added to Bot.uc for clear flag ConfigUsed when bot destroyed.
But even with this fix, if you try add same bot twice when it not exit then name in config will be changed to "Bot" and you can not add this bot by previous name.

In other cases it must work fine and allow enter same bots later.

**Comment by SeriousBuggie** [comment] 2021-03-24 03:22
Tested. All work fine.
```
> AddBotNamed Cali
Cali entered the game.
> KillAll Bot
> AddBotNamed Cali
Cali entered the game.
> KillAll Bot
> AddBotNamed Cali
Cali entered the game.
> KillAll Bot
> AddBotNamed Cali
Cali entered the game.
> Kick Cali
Buggie kicked Cali  from DM-1on1-Deck16][.unr
> AddBotNamed Cali
Cali entered the game.
> Kick Cali
Buggie kicked Cali  from DM-1on1-Deck16][.unr
> AddBotNamed Cali
Cali entered the game.
> KillAll Bot
```

**Closed** 2021-03-29 08:50 UTC
Labels: UnrealScript, bug

**Comment by stijn-volckaert** [comment] 2021-03-29 09:32
Fixed Buggie's patch for the upcoming 469c patch
