### ISSUE TITLE
[469c] Ued feature is *destroying* texture alignment

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1304] opened 2023-06-28 10:34 UTC
This is a very serious issue for me, countless times this Ued feature has completely destroyed my texture alignments. The feature I'm talking about is clicking Alt+LMB on a brush (or actor). Keep in mind, I'm talking about an existing feature of Ued that is also present in 436, I will break it down how it works so we can properly understand the damage it is causing when its used with the Vertex Edit tool.

Alt+LMB is an old Ued feature. How does it work: You first need to select an actor, then click on it using Alt+LMB - this will bring up the Properties window. I suppose this feature is implemented as a shortcut to open Properties window easier. That sounds great, however if you make a specific but common combination with the Vertex Edit tool, it will destroy your texture alignment even if you have not moved a single vertex during the process.

How to reproduce:
1. Open VertexEditIssue.unr in Ued [VertexEditIssue.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/11892969/VertexEditIssue.zip)
2. Turn off Texture Lock (reproducing this issue also works with Texture lock ON, but its more noticeable with it OFF)
3. Select Vertex Edit tool
4. Select the yellow subtracted brush
5. Click on a random vertex, if the vertex is white that means you've selected it.
6. Hold down Alt and press LMB on a random brush "line" (not a vertex).
7. Rebuild the level

Result: Texture alignment is destroyed. We have not moved a single vertex.

Reproduce example video with Texture Lock OFF:

https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/96f97a78-cfd5-4454-9a4e-d95d8a40ddf9

Reproduce example video with Texture Lock ON:

https://github.com/OldUnreal/UnrealTournamentPatches/assets/58362332/82bc8f8b-b683-4674-88bc-faac08c3d736

In the first video example, texture alignment is severely destroyed.
Second example with Texture Lock ON, some of the alignments (like Rotation and Scale) are preserved. However, the Position of the alignments is destroyed.

**Comment by SeriousBuggie** [comment] 2023-10-19 23:02
Duplicate of #1161

This exactly same issue. You not need move any vertex for toggle. You just need editor think you do this. Click mouse with hold ctrl, alt or shift, count as such change, even if there no actual movement of vertex.

**Closed by SeriousBuggie** 2023-10-19 23:02 UTC
Labels: UnrealEd, internal-pf
