### ISSUE TITLE
[469c-RC4] key-mapped taunt, failing...

### ISSUE THREAD

**Issue by thiagoobr** [OldUnreal/UnrealTournamentPatches#1073] opened 2022-09-19 03:45 UTC
hi,

i send taunt "TOMA!" the third time it works, twice he fails....

video erro exemple:

https://youtu.be/cnZUqlzOFEM

**Comment by SeriousBuggie** [comment] 2022-09-19 05:32
Duplicate of #278

**Comment by stijn-volckaert** [comment] 2022-10-23 16:56
Confirmed duplicate of #278. This issue will be fixed in the release version of 469c

**Closed by stijn-volckaert** 2022-10-23 16:56 UTC
Labels: bug, duplicate, fixed in the next patch
