### ISSUE TITLE
[469c] XOpenGL is too dark!

### ISSUE THREAD

**Issue by noskill24** [OldUnreal/UnrealTournamentPatches#1208] opened 2023-03-03 18:56 UTC
Maximum brightness:

![image](https://user-images.githubusercontent.com/35011774/222803741-59624a49-de83-4346-81fc-0322d213b773.png)

**Comment by SeriousBuggie** [comment] 2023-03-23 11:41
In future updates, such options be accessible in game from what I know. Special button with additional options.

**Comment by garry-ut99** [comment] 2023-04-18 19:15
> Yes, I confirm... This video driver is very dark by default.

Me too confirm.

**Comment by stijn-volckaert** [comment] 2023-05-27 08:49
Confirmed duplicate of #1002

**Closed by stijn-volckaert** 2023-05-27 08:49 UTC
Labels: enhancement, rendering
