### ISSUE TITLE
[469c] Checkbox for Full Screen in UT99

### ISSUE THREAD

**Issue by UBIr4** [OldUnreal/UnrealTournamentPatches#1016] opened 2022-08-14 21:11 UTC
**Show FullScreen**
![sshot-1](https://user-images.githubusercontent.com/93230125/184554839-0300f0f3-7556-44a8-9529-29092e35d724.png)
One more request:

In UT99 will you have this checkbox to show in full screen? Because I thought the idea in unreal was very good and I think it has to have pro ut as well.

**Comment by stijn-volckaert** [comment] 2022-10-24 00:47
Duplicate of #42. This is definitely something we want to implement, but we haven't gotten around to it yet

**Closed by stijn-volckaert** 2022-10-24 00:47 UTC
Labels: duplicate, enhancement, UnrealScript
