### ISSUE TITLE
UnrealEd2.2: Pressing F2 launches the web browser with an invalid URL

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1321] opened 2023-07-16 08:47 UTC
Accidentally I pressed F2 in editor, and the web browser opens the URL
`https://www.oldunreal.com/cgi-bin/yabb2/YaBB.pl?board=UnrealEDTwoPointTwo`
But the server oldunreal.com responses with an HTTP Error 404.

**Comment by SeriousBuggie** [comment] 2023-07-16 10:43
Duplicate of #1224

**Closed** 2023-07-16 10:43 UTC

**Comment by SeriousBarbie** [comment] 2023-07-16 10:49
Damn, I knew there was something similar, and I searched here for "LaunchURL" what is shown in log, but without success…
