### ISSUE TITLE
[UEd] [Feature Req] "Align and Distribute" actors and/or brushes

### ISSUE THREAD

**Issue by dizzy-egg** [OldUnreal/UnrealTournamentPatches#1661] opened 2024-11-12 01:53 UTC
It would be incredibly useful to have the ability to "align and distribute" actors and/or brushes in the editor. At least in the 2D viewports.

Example: you have a big room and a bunch of lights. You want to distribute the lights evenly along one wall of the room. Doing this manually (repositioning each light) may take several minutes of tedious work.

With options to "align horizontally"/"align vertically" and "distribute horizontally"/"distribute vertically" this would take seconds.

Illustration:
![image](https://github.com/user-attachments/assets/76714a05-c23c-4106-8528-c88c5885dfd7)

**Comment by SeriousBarbie** [comment] 2024-11-12 09:57
I do such by selecting them and changing the location property.

**Comment by SeriousBuggie** [comment] 2024-11-12 11:50
As mention above, you can edit for all items only one coordinate for share same axis.

For equal distribution with interval same items, you can use Array tool, which allow you duplicate items. 

Also this is Duplicate of https://github.com/OldUnreal/UnrealTournamentPatches/issues/1235
So I goes close it.

**Closed by SeriousBuggie** 2024-11-12 11:50 UTC
Labels: enhancement, UnrealEd
