### ISSUE TITLE
[469c-RC2] XOpenGL missing texture detail

### ISSUE THREAD

**Issue by mkardi** [OldUnreal/UnrealTournamentPatches#955] opened 2022-07-24 12:15 UTC
I noticed with XOpenGL renderer I am missing fine detail on close up texture surfaces.
It is properly rendered with OpenGL but simply does not exist with XOpenGL.

I have included few examples and my configuration - is this bug or am I missing something?

Platform:
Debian Linux 11 64-bit

```
[XOpenGLDrv.XOpenGLRenderDevice]
Description=AMD RENOIR (DRM 3.46.0, 5.18.0-0.bpo.1-amd64, LLVM 11.0.1)
NoDrawSimple=False
NoDrawTile=False
NoDrawGouraudList=False
NoDrawGouraud=False
NoDrawComplexSurface=False
NoBuffering=False
UseOpenGLDebug=False
UseHWClipping=False
UseHWLighting=False
UseBindlessTextures=False
MaxBindlessTextures=4096
UseShaderDrawParameters=True
UsePersistentBuffers=False
GenerateMipMaps=True
UseBufferInvalidation=False
NoAATiles=True
DetailTextures=True
MacroTextures=True
BumpMaps=True
ParallaxVersion=None
GammaCorrectScreenshots=False
UseAA=True
UseTrilinear=True
UsePrecache=True
AlwaysMipmap=True
ShareLists=True
NoFiltering=False
HighDetailActors=True
Coronas=True
ShinySurfaces=True
VolumetricLighting=True
SimulateMultiPass=False
MaxAnisotropy=16.000000
LODBias=0.000000
GammaOffsetScreenshots=0.700000
DebugLevel=3
NumAASamples=4
RefreshRate=0
DescFlags=1
UseVSync=Off
OpenGLVersion=Core
UseLightmapAtlas=True
```
```

[OpenGLDrv.OpenGLRenderDevice]
UseLightmapAtlas=False
NoAATiles=True
NumAASamples=2
UseAA=True
UseShaderGamma=False
SwapInterval=0
UseMultiDrawArrays=True
UseDrawGouraud469=True
ShaderAlphaHUD=False
DetailMax=2
RefreshRate=60
MaxAnisotropy=16
Use16BitTextures=False
UseHDTextures=True
UseTrilinear=True
UsePrecache=True
AlwaysMipmap=True
UsePalette=True
OneXBlending=False
GammaCorrectScreenshots=False
GammaOffsetBlue=0.000000
GammaOffsetGreen=0.000000
GammaOffsetRed=0.000000
GammaOffset=0.000000
LODBias=0.000000
DetailTextures=True
DescFlags=1
Description=
HighDetailActors=True
Coronas=True
ShinySurfaces=True
VolumetricLighting=True
```

With OpenGL
![opengl_1](https://user-images.githubusercontent.com/81050091/180646413-7e22afdb-5707-42af-aa71-b57f4772e4f6.jpg)
![opengl_2](https://user-images.githubusercontent.com/81050091/180646421-b078842c-b13f-4cb6-9954-b1ce3a1522ff.jpg)

With XOpenGL
![xopengl_1](https://user-images.githubusercontent.com/81050091/180646423-28f751bc-a4bd-4058-a928-2739c2fa4ba2.jpg)
![xopengl_2](https://user-images.githubusercontent.com/81050091/180646425-8b8d36c8-16e4-43cf-9dce-8c14782e149b.jpg)

**Comment by stijn-volckaert** [comment] 2022-07-25 08:39
Duplicate of #11

**Closed by stijn-volckaert** 2022-07-25 08:39 UTC
Labels: duplicate

**Comment by sn260591** [comment] 2022-07-26 08:47
XOpenGL has a new option `DetailMax` that defaults to 0. Setting it to 2 solves the problem.
Looks like #11 has already been resolved.
