### ISSUE TITLE
UT won't launch on my Mac (Sequoia)

### ISSUE THREAD

**Issue by jdm0** [OldUnreal/UnrealTournamentPatches#1667] opened 2024-11-19 00:01 UTC
Installed UT-GOTY per instructions. Launching "UnrealTournament.app" produces an error dialog that says "Failed to enter Entry: Can't find file Entry." (see screenshot). The file "Entry.unr.uz" is right where it's supposed to be in my user Library folder ("~/Library/Application Support/Unreal Tournament/Maps"). Help?

![UT - Failed to enter Entry - Can't find file Entry](https://github.com/user-attachments/assets/4a79f6a5-d32e-41ad-b109-18c356b9f890)

I'm using a 2023 Mac mini, M2 Pro, running macOS Sequoia 15.1.

**Comment by SeriousBuggie** [comment] 2024-11-19 00:06
Duplicate of https://github.com/OldUnreal/UnrealTournamentPatches/issues/1665

We update setup guide. Please run last step (unpack maps). That must fix your issue.

**Closed by SeriousBuggie** 2024-11-19 00:06 UTC

**Comment by jdm0** [comment] 2024-11-19 00:18
Ah, I see. Thanks. FYI, I followed the instructions that appear here…

- https://github.com/OldUnreal/UnrealTournamentPatches/blob/master/README.md

…which do not include the final step of unpacking the map files.

**Comment by SeriousBuggie** [comment] 2024-11-19 00:23
Yes. I update it recently.
