### ISSUE TITLE
Reproducable General Protection Fault - kickers?

### ISSUE THREAD

**Issue by shai-ut99** [OldUnreal/UnrealTournamentPatches#1081] opened 2022-09-27 02:24 UTC
If I join a 469c server (Linux) running [BT-!nekoDungeon-EZ](http://www.i4games.eu/maps/CTF-BT-%21nekoDungeon-EZ) with a 436 client (Windows), I bomb out to the desktop with this message each time, immediately upon connecting:

![CriticalError](https://user-images.githubusercontent.com/37757505/192416836-4c4e4e4a-4818-485d-9f95-52ee232ee4f5.png)

If I join a 469c server running that map with a 469c client (Windows) there is no error.

If I join the same map on a 451 server (Windows) with my 436 client (Windows), there is no error.

**Comment by SeriousBuggie** [comment] 2022-09-27 05:06
Duplicate of #1079

**Comment by shai-ut99** [comment] 2022-09-28 01:10
Ah, sorry @SeriousBuggie, I didn't realise it was a connected issue. I'll close this ticket in that case.

**Closed** 2022-09-28 01:10 UTC
