### ISSUE TITLE
[469c-RC3] Editor: selecting 2 or more actors results in blank struct components

### ISSUE THREAD

**Issue by Feralidragon** [OldUnreal/UnrealTournamentPatches#1004] opened 2022-08-07 19:24 UTC
Check the following test map:
[TestPS.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/9277346/TestPS.zip)

Selecting any 2 or more actors results in the properties window to have `struct` property components to be blank (except the first one), despite being of the same exact value between them ( `0` or `0.000000` , for example).

This does not seem to happen with other types of properties.

This is demonstrated below:

![ued_selection_01](https://user-images.githubusercontent.com/6334764/183307794-e9b162b2-997f-4c33-b6cd-2a7807a7820a.jpg)
![ued_selection_02](https://user-images.githubusercontent.com/6334764/183307797-c6a1fa58-47bb-42b6-a6ed-0e9119d8da75.jpg)
![ued_selection_03](https://user-images.githubusercontent.com/6334764/183307798-12485598-ccae-4b34-b90a-b28d22c677a9.jpg)

**Comment by SeriousBuggie** [comment] 2022-08-07 21:31
Duplicate of #270.
But very good detailed.

**Closed** 2023-05-27 08:29 UTC
Labels: bug, duplicate, UnrealEd
