### ISSUE TITLE
[469b] JumpBoots jump distance and/or height affected by changes in FPS limit

### ISSUE THREAD

**Issue by dizzy-egg** [OldUnreal/UnrealTournamentPatches#367] opened 2021-05-02 02:28 UTC
In a similar vein to #366, it seems that the jump distance and/or jump height of JumpBoots is affected by changes to the player's frame rate.

With an uncapped FPS limit the player cannot jump as far as usual.

With a capped FPS limit of 60, the player can jump "normally" i.e. further and higher than with no FPS limit.

A good example of this is the BunnyTrack map CTF-BT-ForMoli-v3 (a.k.a. CTF-BT-(bar)ForMoli-v3). At checkpoint position `Loc="-7788.899902,-17391.09375,-2260.199951"` there are jump boots which allow players to cross a large gap. It's not possible to cross the gap with 469b and a frame rate limit of 0.

**Comment by dizzy-egg** [comment] 2021-05-02 02:37
Interesting addition: on the BunnyTrack.net BT servers there's a command called `!speed` which shows the vertical/horizontal speed of the player at the bottom of the screen.

With a lower FPS limit, the maximum horizontal speed reached by the player while jumping with the jump boots is notably higher: from about `420` with no FPS limit to `512` with an FPS limit of `20`.

**Comment by SeriousBuggie** [comment] 2021-05-02 06:50
Try use `slomo` with different setting. Possible related to #147

**Comment by stijn-volckaert** [comment] 2022-05-30 11:36
Confirmed duplicate of #147. 469c will not have a full fix for this problem, but it will be mitigated to a large extent.

**Closed by stijn-volckaert** 2022-05-30 11:36 UTC
Labels: duplicate, fixed in the next patch, physics, high-prio

**Comment by SeriousBuggie** [comment] 2023-06-11 09:31
Reproduce:
1. Run map locally: [testJumpLength.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/11714286/testJumpLength.zip)
2. Jump with boots while hold forward key pressed without change direction by mouse.

Test results for fps limited to 60:
```
ScriptLog: Jump in 2.071800 for distance 895.672852 max height 500.199951
ScriptLog: Jump in 2.072556 for distance 896.169373 max height 501.199951
ScriptLog: Jump in 2.071739 for distance 828.951111 max height 501.199951
ScriptLog: Jump in 2.071732 for distance 885.319702 max height 501.199951
ScriptLog: Jump in 2.072075 for distance 904.686707 max height 501.199951
ScriptLog: Jump in 2.075340 for distance 895.200378 max height 501.199951
ScriptLog: Jump in 2.071640 for distance 895.515564 max height 501.199951
ScriptLog: Jump in 2.071594 for distance 904.507324 max height 501.199951
ScriptLog: Jump in 2.075012 for distance 829.141418 max height 501.199951
ScriptLog: Jump in 2.071991 for distance 895.606750 max height 501.199951
ScriptLog: Jump in 2.071602 for distance 895.746460 max height 501.199951
ScriptLog: Jump in 2.072708 for distance 895.803711 max height 501.199951
ScriptLog: Jump in 2.074615 for distance 904.507080 max height 501.199951
ScriptLog: Jump in 2.071564 for distance 901.514954 max height 501.199951
ScriptLog: Jump in 2.071579 for distance 895.916382 max height 501.199951
```

Test result with fps not limited (300-500):
```
ScriptLog: Jump in 2.059174 for distance 836.053955 max height 501.484253
ScriptLog: Jump in 2.056168 for distance 840.634827 max height 500.520508
ScriptLog: Jump in 2.061600 for distance 830.583984 max height 500.490234
ScriptLog: Jump in 2.056198 for distance 834.783630 max height 500.695801
ScriptLog: Jump in 2.055542 for distance 831.177307 max height 500.563599
ScriptLog: Jump in 2.057007 for distance 828.376160 max height 500.548950
ScriptLog: Jump in 2.058304 for distance 834.373291 max height 501.557007
ScriptLog: Jump in 2.056992 for distance 835.034729 max height 500.472534
ScriptLog: Jump in 2.059097 for distance 840.192444 max height 501.804565
ScriptLog: Jump in 2.055679 for distance 833.481689 max height 501.684692
ScriptLog: Jump in 2.057037 for distance 839.940491 max height 501.635376
ScriptLog: Jump in 2.056091 for distance 839.701599 max height 501.530396
ScriptLog: Jump in 2.058990 for distance 854.806274 max height 501.648071
ScriptLog: Jump in 2.053085 for distance 837.739014 max height 501.543701
ScriptLog: Jump in 2.055557 for distance 854.499146 max height 500.643433
```

**Comment by SeriousBuggie** [comment] 2023-06-11 09:33
Tracker code:
```unrealscript
class Tracker expands Info;

var PlayerPawn PP;
var float StartTime, MaxZ;
var vector StartPoint;

const NotJumped = -65536.0;

function Tick(float Delata) {
	if (PP == None) {
		foreach AllActors(class'PlayerPawn', PP)
			if (PP.Player != None)
				break;
		if (PP == None)
			return;
	}
	if (PP.Velocity.Z == 0 && PP.Physics == PHYS_Walking && PP.Base != None) { // on ground
		if (MaxZ != NotJumped) {
			Log("Jump in" @ (Level.TimeSeconds - StartTime) @ 
				"for distance" @ VSize(PP.Location - StartPoint) @ 
				"max height" @ (MaxZ - PP.Location.Z));
			MaxZ = NotJumped;
		}
		StartTime = Level.TimeSeconds;
		StartPoint = PP.Location;
	} else { // must be in air
		MaxZ = Max(MaxZ, PP.Location.Z);
	}
}
```
