### ISSUE TITLE
[Feature Request] Add Windowed Fullscreen

### ISSUE THREAD

**Issue by drradio** [OldUnreal/UnrealTournamentPatches#1681] opened 2024-12-04 10:26 UTC
Please add windowed fullscreen mode (or windowed borderless), that is created by using a normal window without any decorations (borders, bars, etc), not by switching video mode.

**Comment by SeriousBuggie** [comment] 2024-12-04 11:43
Duplicate of #1364

**Closed by SeriousBuggie** 2024-12-04 11:43 UTC
