### ISSUE TITLE
[469b] walk jump on edge physics bug

### ISSUE THREAD

**Issue by Mellesp** [OldUnreal/UnrealTournamentPatches#288] opened 2021-03-28 19:14 UTC
After installing the latest v469b patch, I've been getting this physics bug when doing a walk jump close to edges: https://streamable.com/fcn2hs

**Comment by stijn-volckaert** [comment] 2021-03-29 14:27
Can you describe what the bug is here? I have no idea what is supposed to happen here.

Furthermore, can you give us any info on the test setup? Is this a single player game or online game? If it's an online game, which game version does the server run?

**Comment by sebveigli** [comment] 2021-04-02 21:10
I'm not OP, but we are apart of the BunnyTrack community, and this is where the issue was found.

Typically we have a walk jump bind (walking|jump) set in order to minimize air time when traversing platforms. Since 469, there is this strange behavior now where hitting this bind too close to the edge of a platform will fire you out in a weird direction, rather than straight ahead - as if you're clipping against the edge of the platform. 

We have only played with this online and is where the issue occurs. 

From our testing, a client running 469a/b on a 436 server doesn't exhibit this behavior. However that same client running on a 469b server does. 436 clients on a 469b server don't seem to have that issue. 

I would have to verify all the different combinations, but that should be right, but it should be fairly easily reproducible on 469 client and server.

**Comment by klepto** [comment] 2021-04-03 10:04
Steps to reproduce this glitch:
- You have to have moderately high fps (120 and above).
- Use a walk jump bind, input order doesn't matter so either "walking | jump" or "jump | walking".
- Approach the any edge and use the bind to jump from the tip of the edge.

What seems to happen is that game puts you into a walking state for a brief period of time before executing the jump. Walking state prevents you walking off edges, which in result stops all your forward momentum and makes your jump behave in unpredictable manner.

This does not happen on servers using older patch versions (451 and below) or clients with older patch versions. This only happens if you use both 469 client and are playing on 469 server.

**Comment by klepto** [comment] 2021-04-03 10:10
Including more clear demonstration of this, first 3 jumps are with the glitch in question and last 3 jumps are without it:
https://streamable.com/k33nvn

**Comment by stijn-volckaert** [comment] 2021-12-29 21:45
This will be fixed in 469c

**Comment by stijn-volckaert** [comment] 2022-07-25 18:06
Fixed in 469c-RC2

**Closed by stijn-volckaert** 2022-07-25 18:06 UTC
Labels: bug, UnrealScript, fixed in the next patch, physics
