### ISSUE TITLE
[469b] Log errors on using the in-game voice menu

### ISSUE THREAD

**Issue by OjitroC** [OldUnreal/UnrealTournamentPatches#236] opened 2021-03-14 17:47 UTC
Running 469b (release) with EXUOpenGL and Galaxy, when I open the in-game voice menu the UnrealTournament.Log is filled (1.3MB for a short game) with the following lines (these are the first six which then repeat ad nauseam) 

ScriptWarning: SpeechChildWindow Transient.SpeechChildWindow1 (Function UTMenu.SpeechChildWindow.BeforePaint:01B4) Accessed None 'OptionButtons'
ScriptWarning: SpeechChildWindow Transient.SpeechChildWindow1 (Function UTMenu.SpeechChildWindow.BeforePaint:01C9) Accessed None 'OptionButtons'
ScriptWarning: SpeechChildWindow Transient.SpeechChildWindow1 (Function UTMenu.SpeechChildWindow.BeforePaint:01E9) Accessed None 'OptionButtons'
ScriptWarning: SpeechChildWindow Transient.SpeechChildWindow1 (Function UTMenu.SpeechChildWindow.BeforePaint:01F1) Attempt to assign variable through None
ScriptWarning: SpeechChildWindow Transient.SpeechChildWindow1 (Function UTMenu.SpeechChildWindow.BeforePaint:0203) Accessed None 'OptionButtons'
ScriptWarning: SpeechChildWindow Transient.SpeechChildWindow1 (Function UTMenu.SpeechChildWindow.BeforePaint:020B) Attempt to assign variable through None

As a matter of interest, is there any way you can incorporate a log truncation feature to reduce log entries to unique entries rather than having the same lines repeat endlessly?

The voice menu now extends beyond the bottom of the screen - for a screenshot see this https://ut99.org/viewtopic.php?f=1&t=14127&p=127269#p127269

**Comment by SeriousBuggie** [comment] 2021-03-14 18:35
Need more info for reproduce issue.
Also this can be duplicate of #237 at least in first part.

But I am not sure about flood log because my messages not about `Accessed None` but about index overflow.
So you definitely need provide voice pack and steps for reproduce this flood in logs.

About 
> voice menu now extends beyond the bottom of the screen

This must be another issue. Please do not mess all in one issue, because it is make hard manage it.

**Comment by OjitroC** [comment] 2021-03-14 19:59
To reproduce both the log errors and the overlapping voice menu
1 Download and install the voice pack from the link in issue 237
2 run the game
3 Screen resolution 1920 x 1080
4 Enable GUI Scaling 
5 Set the GUI Scale at 1.75
6 Start a DM (you don't need bots) in any map
7 Press V to open the voice menu
8 The voice menu should extend beyond the bottom of the screen as shown in the screenshot linked above.
9 Press 0 to activate the sound at 0 which is largely off-screen and you should get the log errors.

Note : Up/down keyboard keys don't work for me in the Voice menu so I can't move down below sound 9.

I assume the inability to access the sounds below 9 in the menu because the menu is off screen AND I can't move down the memu keys causes the Script Warnings that flood the log (multiple identical warnings are such a pain!).

**Comment by SeriousBuggie** [comment] 2021-03-14 20:10
For menu off-screen I create separate issue: #238

**Comment by SeriousBuggie** [comment] 2021-03-14 20:15
Can not reproduce flood in logs with fix from issue 237. So I think it is fixed.
Press numbers from off-screen work fine. Arrow down too.

**Comment by stijn-volckaert** [comment] 2022-07-25 18:07
Fixed in 469c-RC2

**Closed by stijn-volckaert** 2022-07-25 18:07 UTC
Labels: bug, fixed in the next patch
