### ISSUE TITLE
[469a] UT singleplayer campaign menus slightly extend beyond top/bottom in 3840x2160 

### ISSUE THREAD

**Issue by Xon2** [OldUnreal/UnrealTournamentPatches#166] opened 2020-11-17 20:04 UTC
Tested on opengl and directx 11 renderers (i can't get 3840x2160 to work with xopengl). When navigating through the singleplayer tournament campaign menus ("Start Unreal Tournament") the menu background extends slightly beyond the bottom and top of the screen. This is fine up to 2560x1440, but 3200x1800 and 3840x2160 draw beyond the screen.

**Comment by SeriousBuggie** [comment] 2021-03-08 00:30
Possible duplicate of #99

**Closed** 2022-07-28 11:22 UTC
Labels: bug, duplicate, UnrealScript, fixed in the next patch
