### ISSUE TITLE
[469c-RC2] OpenGL rendering artifacts

### ISSUE THREAD

**Issue by mkardi** [OldUnreal/UnrealTournamentPatches#965] opened 2022-07-25 21:18 UTC
Patch: 469c-RC2
Platform: Debian Linux 11
Renderer: OpenGL

Kinda hard to describe, but OpenGL produces weird wireframe like rendering artifacts when there are lots of effects such as explosions from rocket launcher and shock rifle.
Did not notice such issue with 469b

```
[OpenGLDrv.OpenGLRenderDevice]
VolumetricLighting=True
ShinySurfaces=True
Coronas=True
HighDetailActors=True
DetailTextures=True
SmoothMasking=True
ColorCorrectionMode=UseFramebuffer
ContextType=AutoDetect
UseLightmapAtlas=True
NoAATiles=True
NumAASamples=4
UseAA=True
UseShaderGamma=False
SwapInterval=0
UseStaticGeometry=False
UseDrawGouraud469=True
ShaderAlphaHUD=False
DetailMax=3
RefreshRate=0
ForceNoSmooth=False
MaxAnisotropy=16
Use16BitTextures=False
UseHDTextures=True
UseTrilinear=True
UsePrecache=False
AlwaysMipmap=True
OneXBlending=False
GammaCorrectScreenshots=False
GammaOffsetBlue=0.000000
GammaOffsetGreen=0.000000
GammaOffsetRed=0.000000
GammaOffset=0.000000
LODBias=0.000000
DescFlags=1
Description=
```
![ut469c_opengl_issue1](https://user-images.githubusercontent.com/81050091/180875633-032a1acf-e0ee-4c89-9ffb-0b9376500351.jpg)

![ut469c_opengl_issue2](https://user-images.githubusercontent.com/81050091/180875652-b6a42088-f07b-4593-a9f7-99bac38a1efd.jpg)

**Comment by CacoFFF** [comment] 2022-07-25 22:39
Maybe the new Framebuffer+anti-aliasing feature doesn't work in all configurations.
If you turn off anti-aliasing (UseAA=0) do you still see the lines?

**Comment by CacoFFF** [comment] 2022-07-25 22:40
Also, what GPU and drivers is this happening on?

**Comment by mkardi** [comment] 2022-07-25 23:27
Disabling AA indeed fixed issue, but it seems rather workaround..

Graphics is AMD Ryzen 5700G APU
Driver is xserver-xorg-video-amdgpu 19.1.0-2

**Comment by guitronimo** [comment] 2022-07-26 01:51
I also noticed some Artefacts with OpenGL and will check if i can reproduce them and see if AA 0 fixes this. 
Sometimes it looked like Z Fighting to me. It was literally a texture that looked like it cant decide if its visible or not in that fighting issue you see artefacts like these.

**Comment by CacoFFF** [comment] 2022-07-26 23:15
In Linux we're applying anti-aliasing using a framebuffer, the code works in most platforms (windows, raspbian and most linux)... obviously by looking at the screenshots you can see that there is no multisampling going on at all, all edges look pixelated.

So we either figure out if there's an alternate way to make AA work in that configuration, or to do more checks to disable it if the driver doesn't support it.

**Comment by an-eternity** [comment] 2022-07-29 06:21
Tested this APU recently in Windows 10/11 - it worked with no such issue.
Probably issue is up to driver used in Linux...

**Comment by 10-p** [comment] 2022-07-30 13:46
An eerily similar bug is present in the newly released windows driver https://www.reddit.com/r/Amd/comments/wabgn3/opengl_msaa_wireframe_bug_in_2271_driver/

This bug occurs in the Steam Deck as well.

**Comment by CacoFFF** [comment] 2022-07-30 16:21
Oh my goodness, I remember seeing news about AMD rewriting their drivers recently.
This is indeed exactly what's going on here.

Someone with a reddit account could post this issue over there too.

**Comment by an-eternity** [comment] 2022-08-02 11:31
After graphics driver update to version 22.7.1, with several different AMD GPU's, integrated and discrete, getting such pictures as this:

![amd_v22-7-1_ogl-bug](https://user-images.githubusercontent.com/72374425/182364258-87a66f84-6c0b-4dbb-b089-c5bfe26f1fff.png)

**Comment by CacoFFF** [comment] 2022-08-02 15:03
As an ugly workaround, set:
`NoAATiles=False` in your settings.

**Comment by an-eternity** [comment] 2022-08-26 21:53
Driver version 22.5.1 was the last 'good' one.
Downgrade to that version fixes not only this, but also several other OpenGL problems (which didn't have any even ugly workarounds) introduced since version 22.7.1.

It seems, have to keep version 22.5.1 (for a while), because problems set of version 22.7.1+ makes OGL/XOGL practically not usable.

**Comment by uralets** [comment] 2022-08-27 06:58
> Driver version 22.5.1 was the last 'good' one.
> Downgrade to that version fixes not only this, but also several other
> OpenGL problems (which didn't have any even ugly workarounds)
> introduced since version 22.7.1.
> It seems, have to keep version 22.5.1 (for a while), because problems
> set of version 22.7.1+ makes OGL/XOGL practically not usable.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID:
> ***@***.***>

you probably meant to say 22.1.5 and 22.1.7

anyway I don't have any significant problems with OGL with either
(besides the skybox rendering issue, which manifests with XOGL as well
for me)

**Comment by an-eternity** [comment] 2022-08-29 23:44
Version 22.5.1: https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-5-1

Further versions have transparent textures problems in antialiasing mode, first person view inventory draw problems (invalid Z ordering), synchronization problems (huge lags in vsync/adaptive-vsync modes, weird visual issues in async mode when framerate reaches too high values such as 1000-2000 - e.g. rotating skybox stops rotating).

**Comment by stijn-volckaert** [comment] 2022-10-23 10:50
I suspect this will get fixed in a future driver, so we're not going to automatically apply workarounds.

**Closed by stijn-volckaert** 2022-10-23 10:50 UTC
Labels: invalid, wontfix, rendering

**Comment by uralets** [comment] 2022-10-23 10:54
"Version 22.5.1: https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-5-1"

so it's not even about Mesa after all. Most ppl would use Mesa driver (amdgpu, radeonsi, r600) with a Radeon GPU on Linux.
Though the problems might be shared ofc.

**Comment by r2rX** [comment] 2022-10-27 10:16
Just letting Linux & AMD users know that mesa commit [19326](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/19326/commits) fixes the issue. If any AMD & Windows users want to, try report this to the Windows driver team and reference this commit.
