### ISSUE TITLE
[469c-RC4] Can't hear taunts immediately after saying something in chat

### ISSUE THREAD

**Issue by unrealtitle99** [OldUnreal/UnrealTournamentPatches#1041] opened 2022-08-30 22:55 UTC
If I try to taunt immediately after saying something in chat, I do not hear the taunt.  If I delay the taunt after saying something, I can hear the taunt.

**Comment by SeriousBuggie** [comment] 2022-08-30 23:46
Duplicate of #278

**Comment by stijn-volckaert** [comment] 2022-09-01 07:38
Confirmed duplicate

**Closed by stijn-volckaert** 2022-09-01 07:38 UTC
Labels: bug, duplicate, audio, fixed in the next patch
