### ISSUE TITLE
Please keep originals' filenames cases

### ISSUE THREAD

**Issue by xDShot** [OldUnreal/UnrealTournamentPatches#839] opened 2022-05-22 16:40 UTC
After unpacking patch zip on top of Steam installation I get same targetted files with different cases on Linux and other environments with file systems' cases insensitivity. For ex. I get both BotPack.u (old) and Botpack.u (new)

**Comment by xDShot** [comment] 2022-05-22 16:44
So far I only found BotPack

**Comment by SeriousBuggie** [comment] 2022-05-22 20:37
Duplicate of #256

**Closed** 2022-05-23 12:22 UTC
Labels: duplicate, wontfix, installer
