### ISSUE TITLE
[469b] AS-FoT-OrionsCursePart1 Crash

### ISSUE THREAD

**Issue by TankBeef** [OldUnreal/UnrealTournamentPatches#230] opened 2021-03-13 01:21 UTC
This crash is different from the Spaceport one, the 469b patch solved that one and now works flawless so far, so i closed it. The AS-FoT-OrionsCursePart1 tested on 436, no issues. On 469a and 469b it freezes, have to ctrl alt delete. I have attached the log file, there are lines that repeat themselves. I am using Windows 10. For example:

Log: IntroDude AS-FoT-OrionsCursePart1.IntroDude7 (State Botpack.IntroDude.IntroDude:0053) PlayAnim: Sequence 'stand' not found in Mesh 'WarlordM'
Log: SludgeBarrel AS-FoT-OrionsCursePart1.SludgeBarrel1 (State UnrealI.SludgeBarrel.Animate:000D) LoopAnim: Sequence 'Swirl' not found in Mesh 'barrel2M'

[AS-FoT-OrionsCursePart1 Crash.log](https://github.com/OldUnreal/UnrealTournamentPatches/files/6133886/AS-FoT-OrionsCursePart1.Crash.log)

**Comment by stijn-volckaert** [comment] 2021-03-13 11:40
Is there a particular point in the map where this crash happens? So far, I have not been able to reproduce it.

**Comment by TankBeef** [comment] 2021-03-13 13:12
> Is there a particular point in the map where this crash happens? So far, I have not been able to reproduce it.

No, it is random. I test it with 10 bots for the recommended player count. I noticed I forgot to remove all mutators before generating the log, so I will try again tonight, but the crash still occurs without them. This particular line comes up often:
ScriptWarning: FNBASTeamTrigger AS-FoT-OrionsCursePart1.FNBASTeamTrigger30 (Function AS-FoT-OrionsCursePart1.FNBASTeamTrigger.IsRelevant:00D9) Accessed None 'PlayerReplicationInfo'

**Comment by OjitroC** [comment] 2021-03-13 18:26
I've just tried it with 469b (release), Galaxy and EXUOpenGL and it works fine.  

I don't get this 

Log: OpenGL Error: GL_INVALID_ENUM (please report this bug)

or this

Log: Breadth path list overflow from PathNode230
Log: Breadth path list overflow from PathNode230
Log: Breadth path list overflow from PathNode230
Log: Breadth path list overflow from PathNode230
Log: Breadth path list overflow from PathNode234
Log: Breadth path list overflow from PathNode234

in my log.   

The 'breadth path list overflow' is suspicious and AFAIK used to lead to crashes.

**Comment by OjitroC** [comment] 2021-03-13 18:35
Ooops - tried it again with 11 bots and it froze with this in the log

DevPath: 1000 navigation nodes searched from PathNode652!
Log: Breadth path list overflow from PathNode652

repeated multiple times.

**Comment by TankBeef** [comment] 2021-03-14 00:37
> 
> 
> Ooops - tried it again with 11 bots and it froze with this in the log
> 
> DevPath: 1000 navigation nodes searched from PathNode652!
> Log: Breadth path list overflow from PathNode652
> 
> repeated multiple times.

Not saying there is correlation, but so far I only get the crash with the bots, so I suggest doing the tests with at least the recommended amount of them.

**Comment by TankBeef** [comment] 2021-03-14 00:53
I have just retested, this time with no mutators and with bots. Attached log, this one has way more repeated lines, plenty of the overflow with different numbers.
[
[AS-FoT-OrionsCursePart1 Crash No Mutators.log](https://github.com/OldUnreal/UnrealTournamentPatches/files/6135883/AS-FoT-OrionsCursePart1.Crash.No.Mutators.log)
](url)

**Comment by OjitroC** [comment] 2021-03-14 09:09
The key differences between the 436 log and the 469b log are
1 Get "DevPath: 1000 navigation nodes searched from PathNode" entries in 436 but fewer (which may in part be due to the length of the game played in testing)
2 The "ScriptWarning: FNBASTeamTrigger AS-FNB-FoT-OrionsCursePart1.FNBASTeamTrigger29 (Function AS-FNB-FoT-OrionsCursePart1.FNBASTeamTrigger.IsRelevant:00D9) Accessed None" entry in 436 is "ScriptWarning: FNBASTeamTrigger AS-FoT-OrionsCursePart1.FNBASTeamTrigger19 (Function AS-FoT-OrionsCursePart1.FNBASTeamTrigger.IsRelevant:00D9) Accessed None 'PlayerReplicationInfo'' in 469
3 Get "Log: Breadth path list overflow from InventorySpot1245" in 436 (though just the one entry in the game I played) rather than multiple entries. 

So is there a difference in the way (and the extent to which) 469b searches the navigation network?

**Comment by stijn-volckaert** [comment] 2021-03-14 10:24
Confirmed. The bots can get stuck in an infinite loop in the pathing code.

**Comment by OjitroC** [comment] 2021-03-14 10:29
A quick comparison of ALL the 'Navigation nodes searched' and 'List overflow' entries in the logs :

436 with 12 'players' in a 9 minute game

DevPath: 1000 navigation nodes searched from swJumpPad1!
DevPath: 1000 navigation nodes searched from swJumpPad1!
DevPath: 1000 navigation nodes searched from InventorySpot1011!
DevPath: 1000 navigation nodes searched from InventorySpot1216!
DevPath: 1000 navigation nodes searched from InventorySpot957!
DevPath: 1000 navigation nodes searched from InventorySpot1004!
DevPath: 1000 navigation nodes searched from InventorySpot1066!
DevPath: 1000 navigation nodes searched from InventorySpot1242!
DevPath: 1000 navigation nodes searched from InventorySpot968!
DevPath: 1000 navigation nodes searched from InventorySpot987!
DevPath: 1000 navigation nodes searched from InventorySpot1063!
DevPath: 1000 navigation nodes searched from InventorySpot946!
DevPath: 1000 navigation nodes searched from InventorySpot978!
DevPath: 1000 navigation nodes searched from InventorySpot1065!
DevPath: 1000 navigation nodes searched from PathNode174!
DevPath: 1000 navigation nodes searched from PathNode611!
DevPath: 1000 navigation nodes searched from PlayerStart74!
DevPath: 1000 navigation nodes searched from PlayerStart74!
DevPath: 1000 navigation nodes searched from PlayerStart74!
DevPath: 1000 navigation nodes searched from PlayerStart74!
DevPath: 1000 navigation nodes searched from PlayerStart74!
DevPath: 1000 navigation nodes searched from PathNode82

469b with 12 'players' - game crashing very soon after starting the map

DevPath: 1000 navigation nodes searched from InventorySpot896!
DevPath: 1000 navigation nodes searched from InventorySpot896!
DevPath: 1000 navigation nodes searched from AssaultRandomizer0!

Log: Breadth path list overflow from PathNode652
Log: Breadth path list overflow from PathNode652
Log: Breadth path list overflow from InventorySpot897
Log: Breadth path list overflow from InventorySpot897
Log: Breadth path list overflow from PathNode652
Log: Breadth path list overflow from PathNode652
Log: Breadth path list overflow from InventorySpot897
Log: Breadth path list overflow from InventorySpot896
Log: Breadth path list overflow from PathNode652
Log: Breadth path list overflow from InventorySpot897
Log: Breadth path list overflow from InventorySpot897
Log: Breadth path list overflow from PathNode652
Log: Breadth path list overflow from AssaultRandomizer0
Log: Breadth path list overflow from AssaultRandomizer0
Log: Breadth path list overflow from PathNode652
Log: Breadth path list overflow from PathNode172
Log: Breadth path list overflow from PathNode172
Log: Breadth path list overflow from PathNode652
Log: Breadth path list overflow from PathNode172
Log: Breadth path list overflow from PathNode652

**Comment by TankBeef** [comment] 2021-03-14 15:06
You know, I did not report this earlier because I really thought it was the same issue as Spaceport, but it is not. If you check that log, you wont find any overflow or repeated lines, but there was freezing. I never knew what triggered that crash, but so far with the 469b it has not occured again. It won't hurt to keep an eye on that one, just in case.

**Comment by stijn-volckaert** [comment] 2021-05-28 13:33
We found the bug and although 436 didn't hang here, it also got the pathing completely wrong. The direct cause is the ```AssaultRandomizer2``` navigation point on this map. It has a ```ToggledCost``` of 10000000000.0 (stored as a float). The ```AssaultRandomizer``` class returns this cost in its ```SpecialCost``` event and the bot pathing code calls ```SpecialCost``` to calculate and assign costs to the various nodes in the path network.

The reason why the pathing code hangs is:
1) It does not do any sanity checks on the value returned by ```SpecialCost```
2) It hangs when it encounters a path with a negative cost
3) The ```AssaultRandomizer.SpecialCost``` code performs a float-to-int conversion. In this particular case, the conversion is invalid because the floating-point number is too big to be represented as an integer. The C++ standard does not specify the expected behavior of an invalid conversion. However, after manually inspecting the assembly code in 436 and 469's Core.dlls, we noticed that the compiler we used for 469 generated different conversion code than the one that was used for 436. In 469, floats that are too big to be represented as integers will be cast to a negative number. In 436, they will be cast to 0. Both implementations are valid according to the C++ standard, but the resulting behavior is wrong in both cases. 469 will hang, whereas 436 will steer bots towards a path that should never be chosen.

I will comment again when the bug is fixed.

**Comment by TankBeef** [comment] 2021-06-02 03:51
Excellent. Thanks a lot.

**Comment by NeonKnightOA** [comment] 2021-06-02 06:50
> We found the bug and although 436 didn't hang here, it also got the pathing completely wrong. The direct cause is the `AssaultRandomizer2` navigation point on this map. It has a `ToggledCost` of 10000000000.0 (stored as a float). The `AssaultRandomizer` class returns this cost in its `SpecialCost` event and the bot pathing code calls `SpecialCost` to calculate and assign costs to the various nodes in the path network.
> 
> The reason why the pathing code hangs is:
> 
>     1. It does not do any sanity checks on the value returned by `SpecialCost`
> 
>     2. It hangs when it encounters a path with a negative cost
> 
>     3. The `AssaultRandomizer.SpecialCost` code performs a float-to-int conversion. In this particular case, the conversion is invalid because the floating-point number is too big to be represented as an integer. The C++ standard does not specify the expected behavior of an invalid conversion. However, after manually inspecting the assembly code in 436 and 469's Core.dlls, we noticed that the compiler we used for 469 generated different conversion code than the one that was used for 436. In 469, floats that are too big to be represented as integers will be cast to a negative number. In 436, they will be cast to an incorrect (but in this case positive) value. Both implementations are valid according to the C++ standard, but the resulting behavior is wrong in both cases. 469 will hang, whereas 436 will steer bots towards a path that should never be chosen.
> 
> 
> I will comment again when the bug is fixed.

So basically a mapper error rather than a game error. But yeah, that should be solved code-wise indeed. What about clamping the value of SpecialCost?

**Comment by stijn-volckaert** [comment] 2021-06-03 08:40
The bug is fixed. float-to-int conversions now clamp to the maximum int value and the pathing code now knows how to handle paths with a negative cost.

**Comment by stijn-volckaert** [comment] 2022-07-25 18:07
Fixed in 469c-RC2

**Closed by stijn-volckaert** 2022-07-25 18:07 UTC
Labels: bug, fixed in the next patch
