### ISSUE TITLE
State UnrealShare.ScriptedPawn.TacticalMove:02C3) Accessed None 'Enemy'

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1582] opened 2024-05-29 08:23 UTC
Another unchecked variable ("Enemy") access in:
```
State UnrealShare.ScriptedPawn.TacticalMove {
...
Begin:
	TweenToRunning(0.15);
	Enable('AnimEnd');
	if (Physics == PHYS_Falling)
	{
		DesiredRotation = Rotator(Enemy.Location - Location);
		Focus = Enemy.Location;
		Destination = Enemy.Location;
(more accesses to *Enemy* follow)
```

> KrallElite MH-HellRaiserNEp3v0.KrallElite5 (State UnrealShare.ScriptedPawn.TacticalMove:02C3) Accessed None 'Enemy'

**Comment by SeriousBuggie** [comment] 2024-05-29 10:04
Duplicate of #1484

**Closed by SeriousBuggie** 2024-05-29 10:04 UTC
