### ISSUE TITLE
[469b] UnrealEd: Selecting a window should bring it to top if already open

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#274] opened 2021-03-26 13:37 UTC
The subject tells it already: if I choose any item in UnrealEd from Menu>View that is assigned to a window, is should get on top of all shown windows if it is already open (BringWindowToTop).  (At least I expect this and code it in this way in my programs.)

V436 behaves the same.

**Comment by SeriousBuggie** [comment] 2021-03-26 16:20
Duplicate of #3.

**Comment by stijn-volckaert** [comment] 2021-06-21 09:04
Confirmed. This is a duplicate of #3 (which will be fixed in 469)

**Closed by stijn-volckaert** 2021-06-21 09:04 UTC
Labels: bug, duplicate, UnrealEd
