### ISSUE TITLE
[469b] Blocked walking jump after dodging patch

### ISSUE THREAD

**Issue by BT-goku** [OldUnreal/UnrealTournamentPatches#445] opened 2021-06-11 11:02 UTC
In bunny track mode we often jump and do dodges,
 jump-> dodge or dodge-> jump
 
 below is a short video of what it looks like. it's already the first dodge and jump you can see

 
 https://streamable.com/xx12fr

question from a different barrel:
doesn't this patch increase ping?
I have a feeling that at 436 it drops by 5ms on some servers.

**Comment by SeriousBuggie** [comment] 2021-06-11 13:36
Please:
- For questions use [OldUnreal discord server](https://discord.gg/thURucxzs6).
- Do not mess off-topic questions into one issue. One problem = one issue.
Found new problem - make another issue.

Thank you for understanding.

About video: on which version it recorded? Specify that.
Record video from other version for comparison.

Explain in words what Expected and what Actual result. Why it wrong (if wrong),

**Comment by BT-goku** [comment] 2021-06-12 22:53
so its on 469b release
I did a dodge left + jump you can hear the sound of 2x jump but it didn't do it
I don't have 436 or 451 but since I remember there was no such problem. It came out in patch 469
a lot of BT players can confirm this

**Comment by TankBeef** [comment] 2021-06-13 02:18
> 
> I don't have 436 or 451 but since I remember there was no such problem.
Ok, first of all memory cannot be trusted. I recommend for these reports that you have a second 436 installation
 of UT for comparison, this is what I have. If you are low on hard drive, you can remove most maps and just keep two or three, since it will be for testing only.
Goku, sorry to say your explanation is still not being clear enough, I tried the dodge+jump on both versions, and did not find anything odd or different. If think it would be better to upload video from both versions, so we can see what the issue is.

**Comment by stijn-volckaert** [comment] 2021-12-30 10:46
This is most likely a duplicate of #288 , which will be fixed in 469c

**Comment by stijn-volckaert** [comment] 2022-07-25 18:03
Fixed in 469c-RC2

**Closed by stijn-volckaert** 2022-07-25 18:03 UTC
Labels: duplicate, fixed in the next patch, physics
