### ISSUE TITLE
[Ubuntu18.04][469a] XOpenGL Vsync cannot be turned off

### ISSUE THREAD

**Issue by ut99fan** [OldUnreal/UnrealTournamentPatches#41] opened 2020-09-25 19:08 UTC
Reproduce:

1. Start UT with XOpenGL render.
2. Menu - Options - Preferences.
3. **UnCheck** VSync checkbox.
4. Close Preferences dialog.
5. Restart UT.
6. Enable TimeDemo stats
7. Play game.

Expected result: I expected the Vsync to be actually disabled but does not seem to work
Actual result: Vsync is on or FPS are capped at 60 (not sure how to check)

I also tried to edit **UnrealTournament.ini** section **[SDLDrv.SDLClient]** with the following settings:
```
VSync=False
FPSLimit=200
FrameRateLimit=0.000000
MinDesiredFrameRate=0.000000    
```

Without any luck

System: Ubuntu 18.04 LTS x64
Theme: Default
Video: 1920x1080 on nVidia Quadro M2200 4GB, driver version 390.138
Four monitors 1920x1080 each. Expanded desktop.

**Comment by stijn-volckaert** [comment] 2020-09-25 19:26
This is almost certainly a duplicate of #35. Can you try changing UseVSync to Off under [XOpenGLDrv.XOpenGLRenderDevice] in UnrealTournament.ini?

**Comment by ut99fan** [comment] 2020-09-26 05:37
This is my entire UnrealTournament.ini (see below)
Should I create section called **[XOpenGLDrv.XOpenGLRenderDevice]**
And there should be line:
**UseVSync=Off**

Or what exactly I need to put there?
The existing "VSync=False" did nothing.

```
[URL]
Protocol=unreal
ProtocolDescription=Unreal Protocol
Name=Player
Map=Index.unr
LocalMap=CityIntro.unr
Host=
Portal=
MapExt=unr
SaveExt=usa
Port=7777
Class=Botpack.TMale1

[FirstRun]
FirstRun=469

[PackageRemap]
UnrealShare=UnrealI

[Engine.Engine]
GameRenderDevice=OpenGLDrv.OpenGLRenderDevice
AudioDevice=Cluster.ClusterAudioSubsystem
NetworkDevice=IpDrv.TcpNetDriver
DemoRecordingDevice=Engine.DemoRecDriver
Console=UTMenu.UTConsole
Language=int
GameEngine=Engine.GameEngine
EditorEngine=Editor.EditorEngine
WindowedRenderDevice=SoftDrv.SoftwareRenderDevice
RenderDevice=OpenGLDrv.OpenGLRenderDevice
DefaultGame=Botpack.DeathMatchPlus
DefaultServerGame=Botpack.DeathMatchPlus
ViewportManager=SDLDrv.SDLClient
Render=Render.Render
Input=Engine.Input
Canvas=Engine.Canvas
CdPath=E:
RunCount=44
UpgradedAudioDevice=True

[Core.System]
PurgeCacheDays=30
SavePath=../Save
CachePath=../Cache
CacheExt=.uxx
Paths=../System/*.u
Paths=../Maps/*.unr
Paths=../Textures/*.utx
Paths=../Sounds/*.uax
Paths=../Music/*.umx
Suppress=DevLoad
Suppress=DevSave
Suppress=DevNetTraffic
Suppress=DevGarbage
Suppress=DevKill
Suppress=DevReplace
Suppress=DevSound
Suppress=DevCompile
Suppress=DevBind
Suppress=DevMD5

[Engine.GameEngine]
CacheSizeMegs=4
UseSound=True
ServerActors=IpDrv.UdpBeacon
ServerActors=IpServer.UdpServerQuery
ServerActors=IpServer.UdpServerUplink MasterServerAddress=unreal.epicgames.com MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master0.gamespy.com MasterServerPort=27900
ServerActors=IpServer.UdpServerUplink MasterServerAddress=master.mplayer.com MasterServerPort=27900
ServerActors=UWeb.WebServer
ServerPackages=SoldierSkins
ServerPackages=CommandoSkins
ServerPackages=FCommandoSkins
ServerPackages=SGirlSkins
ServerPackages=BossSkins
ServerPackages=Botpack
ServerPackages=MultiMesh
ServerPackages=Relics
ServerPackages=EpicCustomModels
ServerPackages=TCowMeshSkins
ServerPackages=TNaliMeshSkins
ServerPackages=TSkMSkins
ServerPackages=De
MinClientVersion=432

[WinDrv.WindowsClient]
WindowedViewportX=800
WindowedViewportY=600
WindowedColorBits=32
FullscreenViewportX=1024
FullscreenViewportY=768
FullscreenColorBits=32
Brightness=0.500000
MipFactor=1.000000
UseDirectDraw=True
UseJoystick=False
CaptureMouse=True
StartupFullscreen=True
CurvedSurfaces=False
LowDetailTextures=False
ScreenFlashes=True
NoLighting=False
SlowVideoBuffering=True
DeadZoneXYZ=True
DeadZoneRUV=False
InvertVertical=False
ScaleXYZ=1000.000000
ScaleRUV=2000.000000
MinDesiredFrameRate=30.000000
Decals=True
NoDynamicLights=False
UseDirectInput=False
ParticleDensity=0
NoFractalAnim=False
SkinDetail=High
TextureDetail=High

[XDrv.XClient]
WindowedViewportX=800
WindowedViewportY=600
WindowedColorBits=32
FullscreenViewportX=800
FullscreenViewportY=600
FullscreenColorBits=32
Brightness=0.500000
MipFactor=1.000000
SlowVideoBuffering=False
StartupFullscreen=True
CurvedSurfaces=False
CaptureMouse=True
LowDetailTextures=False
ScreenFlashes=True
NoLighting=False
DeadZoneXYZ=True
DeadZoneRUV=False
InvertVertical=False
ScaleXYZ=1000.0
ScaleRUV=2000.0
MinDesiredFrameRate=30.0

[Engine.Player]
ConfiguredInternetSpeed=20000
ConfiguredLanSpeed=20000

[Audio.GenericAudioSubsystem]
UseFilter=True
UseSurround=False
UseStereo=True
UseCDMusic=False
UseDigitalMusic=False
UseSpatial=False
UseReverb=False
Use3dHardware=False
LowSoundQuality=False
ReverseStereo=False
Latency=40
OutputRate=44100Hz
Channels=32
MusicVolume=160
SoundVolume=200
AmbientFactor=0.7

[Galaxy.GalaxyAudioSubsystem]
UseDirectSound=True
UseFilter=True
UseSurround=True
UseStereo=True
UseCDMusic=False
UseDigitalMusic=True
UseSpatial=False
UseReverb=True
Use3dHardware=True
LowSoundQuality=False
ReverseStereo=False
Latency=40
OutputRate=44100Hz
EffectsChannels=32
DopplerSpeed=9000.000000
MusicVolume=255
SoundVolume=64
AmbientFactor=0.700000

[IpDrv.TcpNetDriver]
AllowDownloads=True
ConnectionTimeout=15.0
InitialConnectTimeout=150.0
AckTimeout=1.0
KeepAliveTime=0.2
MaxClientRate=20000
SimLatency=0
RelevantTimeout=5.0
SpawnPrioritySeconds=1.0
ServerTravelPause=4.0
NetServerMaxTickRate=20
LanServerMaxTickRate=35
DownloadManagers=IpDrv.HTTPDownload
DownloadManagers=Engine.ChannelDownload
MaxConnPerIPPerMinute=5
LogMaxConnPerIPPerMin=False
AllowPlayerPortUnreach=True
LogPortUnreach=False

[IpDrv.HTTPDownload]
RedirectToURL=
ProxyServerHost=
ProxyServerPort=3128
UseCompression=True

[Engine.DemoRecDriver]
DemoSpectatorClass=Botpack.CHSpectator
MaxClientRate=25000
ConnectionTimeout=15.0
InitialConnectTimeout=500.0
AckTimeout=1.0
KeepAliveTime=1.0
SimLatency=0
RelevantTimeout=5.0
SpawnPrioritySeconds=1.0
ServerTravelPause=4.0
NetServerMaxTickRate=60
LanServerMaxTickRate=60

[Engine.GameReplicationInfo]
ServerName=Another UT Server
ShortName=UT Server
AdminName=
AdminEmail=
Region=0
MOTDLine1=
MOTDLine2=
MOTDLine3=
MOTDLine4=

[IpDrv.TcpipConnection]
SimPacketLoss=0
SimLatency=0

[IpServer.UdpServerQuery]
GameName=ut
bTeamInfo=False

[IpDrv.UdpBeacon]
DoBeacon=True
BeaconTime=0.50
BeaconTimeout=5.0
BeaconProduct=ut

[SoftDrv.SoftwareRenderDevice]
Translucency=True
VolumetricLighting=True
ShinySurfaces=False
Coronas=False
HighDetailActors=False
HighResTextureSmooth=True
LowResTextureSmooth=False
FastTranslucency=True

[GlideDrv.GlideRenderDevice]
Translucency=True
VolumetricLighting=True
ShinySurfaces=True
Coronas=True
HighDetailActors=True
DetailBias=-1.500000
RefreshRate=60Hz
DetailTextures=True
FastUglyRefresh=False
ScreenSmoothing=True
Resolution=Default

[MetalDrv.MetalRenderDevice]
Translucency=True
VolumetricLighting=True
ShinySurfaces=True
Coronas=True
HighDetailActors=True
DetailTextures=False

[OpenGLDrv.OpenGLRenderDevice]
ZRangeHack=True
NoAATiles=True
NumAASamples=8
UseAA=True
MaskedTextureHack=True
SmoothMaskedTextures=False
SceneNodeHack=True
FrameRateLimit=60
SwapInterval=0
UseFragmentProgram=True
UseMultiDrawArrays=True
TexDXT1ToDXT3=False
DynamicTexIdRecycleLevel=100
CacheStaticMaps=True
UseTexPool=True
UseTexIdPool=True
UseSSE2=True
UseSSE=True
BufferTileQuads=True
SinglePassDetail=False
SinglePassFog=True
ColorizeDetailTextures=False
DetailClipping=False
DetailMax=2
RefreshRate=60
MaxTMUnits=0
NoFiltering=False
MaxAnisotropy=16
Use16BitTextures=False
UseS3TC=True // Enable higher resolution S3TC textures.
UseAlphaPalette=True
UseTrilinear=True
UsePrecache=True
TextureClampHack=True
UseShaderGamma=True
ShaderGammaCorrectHUD=False
UseDrawGouraud469=True
ShaderAlphaHUD=False
UseHDTextures=True
AlwaysMipmap=False
UsePalette=False
UseZTrick=False
UseSamplerObjects=False
OneXBlending=False
GammaCorrectScreenshots=False
GammaOffsetBlue=0.000000
GammaOffsetGreen=0.000000
GammaOffsetRed=0.000000
GammaOffset=0.000000
LODBias=0.000000
DetailTextures=False
DescFlags=1
Description=
HighDetailActors=False
Coronas=False
ShinySurfaces=False
VolumetricLighting=False

[D3DDrv.D3DRenderDevice]
Translucency=True
VolumetricLighting=False
ShinySurfaces=True
Coronas=True
HighDetailActors=True
UseMipmapping=True
UseTrilinear=False
UseMultitexture=True
UsePageFlipping=True
UsePalettes=True
UseFullscreen=True
UseGammaCorrection=True
DetailTextures=False
Use3dfx=False
UseTripleBuffering=True
UsePrecache=True
Use32BitTextures=False
DescFlags=1
UseTextureCompression=False
Use16BPPTextures=False
dwDeviceId=26522
dwVendorId=4098
Use32BitZBuffer=False
UseVertexFog=False
UseAGPTextures=False
UseVideoMemoryVB=False
UseVSync=False
Description=AMD Radeon HD 7900 Series

[SglDrv.SglRenderDevice]
Translucency=True
VolumetricLighting=False
ShinySurfaces=False
Coronas=True
HighDetailActors=False
ColorDepth=16
DetailTextures=False
FastUglyRefresh=False
TextureDetailBias=Near
VertexLighting=False

[Editor.EditorEngine]
UseSound=True
CacheSizeMegs=6
GridEnabled=True
SnapVertices=True
SnapDistance=10.000000
GridSize=(X=16.000000,Y=16.000000,Z=16.000000)
RotGridEnabled=True
RotGridSize=(Pitch=1024,Yaw=1024,Roll=1024)
GameCommandLine=-log
FovAngleDegrees=90.000000
GodMode=True
AutoSave=False
AutoSaveTimeMinutes=5
AutoSaveIndex=6
C_WorldBox=(R=0,G=0,B=107,A=0)
C_GroundPlane=(R=0,G=0,B=63,A=0)
C_GroundHighlight=(R=0,G=0,B=127,A=0)
C_BrushWire=(R=255,G=63,B=63,A=0)
C_Pivot=(R=0,G=255,B=0,A=0)
C_Select=(R=0,G=0,B=127,A=0)
C_AddWire=(R=127,G=127,B=255,A=0)
C_SubtractWire=(R=255,G=192,B=63,A=0)
C_GreyWire=(R=163,G=163,B=163,A=0)
C_Invalid=(R=163,G=163,B=163,A=0)
C_ActorWire=(R=127,G=63,B=0,A=0)
C_ActorHiWire=(R=255,G=127,B=0,A=0)
C_White=(R=255,G=255,B=255,A=0)
C_SemiSolidWire=(R=127,G=255,B=0,A=0)
C_NonSolidWire=(R=63,G=192,B=32,A=0)
C_WireGridAxis=(R=119,G=119,B=119,A=0)
C_ActorArrow=(R=163,G=0,B=0,A=0)
C_ScaleBox=(R=151,G=67,B=11,A=0)
C_ScaleBoxHi=(R=223,G=149,B=157,A=0)
C_Mover=(R=255,G=0,B=255,A=0)
C_OrthoBackground=(R=163,G=163,B=163,A=0)
C_Current=(R=0,G=0,B=0,A=0)
C_BrushVertex=(R=0,G=0,B=0,A=0)
C_BrushSnap=(R=0,G=0,B=0,A=0)
C_Black=(R=0,G=0,B=0,A=0)
C_Mask=(R=0,G=0,B=0,A=0)
C_WireBackground=(R=0,G=0,B=0,A=0)
C_ZoneWire=(R=0,G=0,B=0,A=0)
EditPackages=Core
EditPackages=Engine
EditPackages=Editor
EditPackages=UWindow
EditPackages=Fire
EditPackages=IpDrv
EditPackages=UWeb
EditPackages=UBrowser
EditPackages=UnrealShare
EditPackages=UnrealI
EditPackages=UMenu
EditPackages=IpServer
EditPackages=Botpack
EditPackages=UTServerAdmin
EditPackages=UTMenu
EditPackages=UTBrowser

[UMenu.UnrealConsole]
RootWindow=UMenu.UMenuRootWindow
UWindowKey=IK_Esc
ShowDesktop=True

[UMenu.UMenuMenuBar]
ShowHelp=True
GameUMenuDefault=UTMenu.UTGameMenu
MultiplayerUMenuDefault=UTMenu.UTMultiplayerMenu
OptionsUMenuDefault=UTMenu.UTOptionsMenu
ModMenuClass=UMenu.UMenuModMenu

[Botpack.ChallengeBotInfo]
Difficulty=1

[Botpack.DeathMatchPlus]
bNoviceMode=True
bHardCoreMode=True
bUseTranslocator=False
bCoopWeaponMode=False
MinPlayers=0
AirControl=0.350000
FragLimit=10
TimeLimit=0
bChangeLevels=False
bMegaSpeed=False
bAltScoring=False
bMultiWeaponStay=True
bForceRespawn=False
bTournament=False
NetWait=10
RestartWait=15
MaxCommanders=0
InitialBots=6
bNoMonsters=False
bHumansOnly=False
bClassicDeathMessages=False
MinFOV=80.000000
MaxFOV=130.000000
MaxNameChanges=0

[Botpack.CTFGame]
bUseTranslocator=True
bCoopWeaponMode=True
GoalTeamScore=3.000000
bNoTeamChanges=False
FriendlyFireScale=0.000000
MaxTeams=2
MaxTeamSize=16
FragLimit=0
TimeLimit=0
bMultiWeaponStay=True
bForceRespawn=False
MaxCommanders=0
bNoMonsters=False
bHumansOnly=False
bClassicDeathMessages=False
MinFOV=80.000000
MaxFOV=130.000000
MaxNameChanges=0

[Botpack.Domination]
bDumbDown=True
bUseTranslocator=True
bCoopWeaponMode=True
GoalTeamScore=100

[Botpack.Assault]
bUseTranslocator=False
bCoopWeaponMode=True
Defenses=3
SavedTime=0.000000
NumDefenses=0
CurrentDefender=0
bDefenseSet=False
bTiePartOne=False
GameCode=
Part=0
bNoTeamChanges=False
FriendlyFireScale=0.000000
MaxTeams=2
GoalTeamScore=30.000000
MaxTeamSize=16
FragLimit=30
TimeLimit=0
bMultiWeaponStay=True
bForceRespawn=False
MaxCommanders=0
bNoMonsters=False
bHumansOnly=False
bClassicDeathMessages=False
MinFOV=80.000000
MaxFOV=130.000000
MaxNameChanges=0

[Botpack.TeamGamePlus]
bBalanceTeams=True
GoalTeamScore=30.000000
bPlayersBalanceTeams=True
bNoTeamChanges=False
FriendlyFireScale=0.000000
MaxTeams=2
MaxTeamSize=16
FragLimit=30
TimeLimit=0
bMultiWeaponStay=True
bForceRespawn=False
bUseTranslocator=False
MaxCommanders=0
bNoMonsters=False
bHumansOnly=False
bCoopWeaponMode=False
bClassicDeathMessages=False
MinFOV=80.000000
MaxFOV=130.000000
MaxNameChanges=0

[Engine.GameInfo]
bLowGore=False
bVeryLowGore=False
bMuteSpectators=False
bNoCheating=True
bAllowFOV=False
bExternalBatcher=False
AutoAim=0.930000
GameSpeed=1.000000
MaxSpectators=2
AdminPassword=
GamePassword=
MaxPlayers=16
ServerLogName=server.log
bLocalLog=True
bWorldLog=True
bBatchLocal=False
DemoBuild=0
DemoHasTuts=0
PlayerViewDelay=1.000000
PlayerSpeechDelay=0.300000
PlayerTauntDelay=2.000000
bLogAdminActions=False
LoginDelaySeconds=0.000000
MaxLoginAttempts=0
ActionToTake=DO_Nothing
IPPolicies[0]=ACCEPT,*
IPPolicies[1]=
IPPolicies[2]=
IPPolicies[3]=
IPPolicies[4]=
IPPolicies[5]=
IPPolicies[6]=
IPPolicies[7]=
IPPolicies[8]=
IPPolicies[9]=
IPPolicies[10]=
IPPolicies[11]=
IPPolicies[12]=
IPPolicies[13]=
IPPolicies[14]=
IPPolicies[15]=
IPPolicies[16]=
IPPolicies[17]=
IPPolicies[18]=
IPPolicies[19]=
IPPolicies[20]=
IPPolicies[21]=
IPPolicies[22]=
IPPolicies[23]=
IPPolicies[24]=
IPPolicies[25]=
IPPolicies[26]=
IPPolicies[27]=
IPPolicies[28]=
IPPolicies[29]=
IPPolicies[30]=
IPPolicies[31]=
IPPolicies[32]=
IPPolicies[33]=
IPPolicies[34]=
IPPolicies[35]=
IPPolicies[36]=
IPPolicies[37]=
IPPolicies[38]=
IPPolicies[39]=
IPPolicies[40]=
IPPolicies[41]=
IPPolicies[42]=
IPPolicies[43]=
IPPolicies[44]=
IPPolicies[45]=
IPPolicies[46]=
IPPolicies[47]=
IPPolicies[48]=
IPPolicies[49]=
IPPolicies[50]=
IPPolicies[51]=
IPPolicies[52]=
IPPolicies[53]=
IPPolicies[54]=
IPPolicies[55]=
IPPolicies[56]=
IPPolicies[57]=
IPPolicies[58]=
IPPolicies[59]=
IPPolicies[60]=
IPPolicies[61]=
IPPolicies[62]=
IPPolicies[63]=
IPPolicies[64]=
IPPolicies[65]=
IPPolicies[66]=
IPPolicies[67]=
IPPolicies[68]=
IPPolicies[69]=
IPPolicies[70]=
IPPolicies[71]=
IPPolicies[72]=
IPPolicies[73]=
IPPolicies[74]=
IPPolicies[75]=
IPPolicies[76]=
IPPolicies[77]=
IPPolicies[78]=
IPPolicies[79]=
IPPolicies[80]=
IPPolicies[81]=
IPPolicies[82]=
IPPolicies[83]=
IPPolicies[84]=
IPPolicies[85]=
IPPolicies[86]=
IPPolicies[87]=
IPPolicies[88]=
IPPolicies[89]=
IPPolicies[90]=
IPPolicies[91]=
IPPolicies[92]=
IPPolicies[93]=
IPPolicies[94]=
IPPolicies[95]=
IPPolicies[96]=
IPPolicies[97]=
IPPolicies[98]=
IPPolicies[99]=
IPPolicies[100]=
IPPolicies[101]=
IPPolicies[102]=
IPPolicies[103]=
IPPolicies[104]=
IPPolicies[105]=
IPPolicies[106]=
IPPolicies[107]=
IPPolicies[108]=
IPPolicies[109]=
IPPolicies[110]=
IPPolicies[111]=
IPPolicies[112]=
IPPolicies[113]=
IPPolicies[114]=
IPPolicies[115]=
IPPolicies[116]=
IPPolicies[117]=
IPPolicies[118]=
IPPolicies[119]=
IPPolicies[120]=
IPPolicies[121]=
IPPolicies[122]=
IPPolicies[123]=
IPPolicies[124]=
IPPolicies[125]=
IPPolicies[126]=
IPPolicies[127]=
IPPolicies[128]=
IPPolicies[129]=
IPPolicies[130]=
IPPolicies[131]=
IPPolicies[132]=
IPPolicies[133]=
IPPolicies[134]=
IPPolicies[135]=
IPPolicies[136]=
IPPolicies[137]=
IPPolicies[138]=
IPPolicies[139]=
IPPolicies[140]=
IPPolicies[141]=
IPPolicies[142]=
IPPolicies[143]=
IPPolicies[144]=
IPPolicies[145]=
IPPolicies[146]=
IPPolicies[147]=
IPPolicies[148]=
IPPolicies[149]=
IPPolicies[150]=
IPPolicies[151]=
IPPolicies[152]=
IPPolicies[153]=
IPPolicies[154]=
IPPolicies[155]=
IPPolicies[156]=
IPPolicies[157]=
IPPolicies[158]=
IPPolicies[159]=
IPPolicies[160]=
IPPolicies[161]=
IPPolicies[162]=
IPPolicies[163]=
IPPolicies[164]=
IPPolicies[165]=
IPPolicies[166]=
IPPolicies[167]=
IPPolicies[168]=
IPPolicies[169]=
IPPolicies[170]=
IPPolicies[171]=
IPPolicies[172]=
IPPolicies[173]=
IPPolicies[174]=
IPPolicies[175]=
IPPolicies[176]=
IPPolicies[177]=
IPPolicies[178]=
IPPolicies[179]=
IPPolicies[180]=
IPPolicies[181]=
IPPolicies[182]=
IPPolicies[183]=
IPPolicies[184]=
IPPolicies[185]=
IPPolicies[186]=
IPPolicies[187]=
IPPolicies[188]=
IPPolicies[189]=
IPPolicies[190]=
IPPolicies[191]=
IPPolicies[192]=
IPPolicies[193]=
IPPolicies[194]=
IPPolicies[195]=
IPPolicies[196]=
IPPolicies[197]=
IPPolicies[198]=
IPPolicies[199]=
IPPolicies[200]=
IPPolicies[201]=
IPPolicies[202]=
IPPolicies[203]=
IPPolicies[204]=
IPPolicies[205]=
IPPolicies[206]=
IPPolicies[207]=
IPPolicies[208]=
IPPolicies[209]=
IPPolicies[210]=
IPPolicies[211]=
IPPolicies[212]=
IPPolicies[213]=
IPPolicies[214]=
IPPolicies[215]=
IPPolicies[216]=
IPPolicies[217]=
IPPolicies[218]=
IPPolicies[219]=
IPPolicies[220]=
IPPolicies[221]=
IPPolicies[222]=
IPPolicies[223]=
IPPolicies[224]=
IPPolicies[225]=
IPPolicies[226]=
IPPolicies[227]=
IPPolicies[228]=
IPPolicies[229]=
IPPolicies[230]=
IPPolicies[231]=
IPPolicies[232]=
IPPolicies[233]=
IPPolicies[234]=
IPPolicies[235]=
IPPolicies[236]=
IPPolicies[237]=
IPPolicies[238]=
IPPolicies[239]=
IPPolicies[240]=
IPPolicies[241]=
IPPolicies[242]=
IPPolicies[243]=
IPPolicies[244]=
IPPolicies[245]=
IPPolicies[246]=
IPPolicies[247]=
IPPolicies[248]=
IPPolicies[249]=
IPPolicies[250]=
IPPolicies[251]=
IPPolicies[252]=
IPPolicies[253]=
IPPolicies[254]=
IPPolicies[255]=
bNoMonsters=False
bHumansOnly=False
bCoopWeaponMode=False
bClassicDeathMessages=False
MinFOV=80.000000
MaxFOV=130.000000
MaxNameChanges=0
NoLockdown=1

[UnrealShare.UnrealGameOptionsMenu]
bCanModifyGore=True

[UBrowser.UBrowserMainClientWindow]
LANTabName=UBrowserLAN
ServerListNames[0]=UBrowserUT
ServerListNames[1]=UBrowserLAN
ServerListNames[2]=UBrowserPopulated
ServerListNames[3]=UBrowserDeathmatch
ServerListNames[4]=UBrowserTeamGames
ServerListNames[5]=UBrowserCTF
ServerListNames[6]=UBrowserDOM
ServerListNames[7]=UBrowserAS
ServerListNames[8]=UBrowserLMS
ServerListNames[9]=UBrowserAll
ServerListNames[10]=None
ServerListNames[11]=None
ServerListNames[12]=None
ServerListNames[13]=None
ServerListNames[14]=None
ServerListNames[15]=None
ServerListNames[16]=None
ServerListNames[17]=None
ServerListNames[18]=None
ServerListNames[19]=None

[UBrowserUT]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,bCompatibleServersOnly=True

[UBrowserLAN]
ListFactories[0]=UBrowser.UBrowserLocalFact,BeaconProduct=ut
URLAppend=?LAN
AutoRefreshTime=10
bNoAutoSort=True

[UBrowserPopulated]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,MinPlayers=1,bCompatibleServersOnly=True

[UBrowserDeathmatch]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,GameType=DeathMatchPlus,bCompatibleServersOnly=True

[UBrowserTeamGames]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,GameType=TeamGamePlus,bCompatibleServersOnly=True

[UBrowserCTF]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,GameType=CTFGame,bCompatibleServersOnly=True

[UBrowserDOM]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,GameType=Domination,bCompatibleServersOnly=True

[UBrowserAS]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,GameType=Assault,bCompatibleServersOnly=True

[UBrowserLMS]
ListFactories[0]=UBrowser.UBrowserSubsetFact,SupersetTag=UBrowserAll,GameType=LastManStanding,bCompatibleServersOnly=True

[UBrowserAll]
ListFactories[0]=UBrowser.UBrowserGSpyFact,MasterServerAddress=unreal.epicgames.com,MasterServerTCPPort=28900,Region=0,GameName=ut
ListFactories[1]=UBrowser.UBrowserGSpyFact,MasterServerAddress=master0.gamespy.com,MasterServerTCPPort=28900,Region=0,GameName=ut
bHidden=True
bFallbackFactories=True

[UTMenu.UTMultiplayerMenu]
OnlineServices[0]=LOCALIZE,MPlayer
OnlineServices[1]=LOCALIZE,Heat
OnlineServices[2]=LOCALIZE,WON

[UTMenu.UTLadder]
bGOTY=true

[UWeb.WebServer]
Applications[0]=UTServerAdmin.UTServerAdmin
ApplicationPaths[0]=/ServerAdmin
Applications[1]=UTServerAdmin.UTImageServer
ApplicationPaths[1]=/images
DefaultApplication=0
bEnabled=False

[UBrowser.UBrowserHTTPClient]
ProxyServerAddress=
ProxyServerPort=

[UTServerAdmin.UTServerAdmin]
AdminUsername=admin
AdminPassword=admin

[WindowPositions]
GameLog=(X=134,Y=134,XL=512,YL=256)
ConfigPageRenderer=(X=5,Y=96,XL=516,YL=280)
ConfigPageDetail=(X=5,Y=96,XL=516,YL=280)
ConfigPageFirstTime=(X=5,Y=96,XL=516,YL=280)
WizardDialog=(X=695,Y=300,XL=530,YL=440)
ConfigPageSafeMode=(X=5,Y=96,XL=516,YL=280)

[Botpack.UTIntro]
CityIntroHUDClass=
bNoMonsters=False
bHumansOnly=False
bCoopWeaponMode=False
bClassicDeathMessages=False
MinFOV=80.000000
MaxFOV=130.000000
MaxNameChanges=0

[UMenu.UMenuRootWindow]
GUIScale=1.000000
LookAndFeelClass=UMenu.UMenuBlueLookAndFeel
ConfiguredGUIScale=1.000000
AutoGUIScale=True

[UTMenu.UTConsole]
SpeechKey=86
SavedPasswords[0]=
SavedPasswords[1]=
SavedPasswords[2]=
SavedPasswords[3]=
SavedPasswords[4]=
SavedPasswords[5]=
SavedPasswords[6]=
SavedPasswords[7]=
SavedPasswords[8]=
SavedPasswords[9]=
RootWindow=UMenu.UMenuRootWindow
MouseScale=0.600000
ShowDesktop=True
bShowConsole=False
UWindowKey=IK_None

[UWindow.WindowConsole]
ConsoleKey=192

[Engine.StatLog]
LocalBatcherURL=../NetGamesUSA.com/ngStats/ngStatsUT.exe
LocalBatcherParams=
LocalStatsURL=../NetGamesUSA.com/ngStats/html/ngStats_Main.html
WorldBatcherURL=../NetGamesUSA.com/ngWorldStats/bin/ngWorldStats.exe
WorldBatcherParams=-d ../NetGamesUSA.com/ngWorldStats/logs -g UT
WorldStatsURL=http://www.netgamesusa.com
LocalLogDir=../Logs
WorldLogDir=../NetGamesUSA.com/ngWorldStats/logs
bLogTypingEvents=False
bWorldBatcherError=False

[UTMenu.UTMenuBotmatchCW]
Map=DM-Liandri.unr
GameType=BotPack.DeathMatchPlus
MutatorList=
bKeepMutators=False

[D3D10Drv.D3D10RenderDevice]
Coronas=True
HighDetailActors=True
VolumetricLighting=True
ShinySurfaces=True
DetailTextures=True
Precache=False
Antialiasing=4
Anisotropy=8
VSync=False
ParallaxOcclusionMapping=False
LODBias=0
BumpMapping=False
ClassicLighting=True
AlphaToCoverage=False
AutoFOV=True
FPSLimit=200
simulateMultipassTexturing=True
unlimitedViewDistance=False

[Botpack.TrophyGame]
CityIntroHUDClass=
bNoMonsters=False
bHumansOnly=False
bCoopWeaponMode=False
bClassicDeathMessages=False
MinFOV=80.000000
MaxFOV=130.000000
MaxNameChanges=0

[Botpack.LadderLoadGame]
CityIntroHUDClass=
bNoMonsters=False
bHumansOnly=False
bCoopWeaponMode=False
bClassicDeathMessages=False
MinFOV=80.000000
MaxFOV=130.000000
MaxNameChanges=0

[SDLDrv.SDLClient]
MacNativeTextToSpeech=False
TextToSpeechFile=
MacKeepAllScreensOn=False
AllowCommandQKeys=False
AllowUnicodeKeys=False
IgnoreUngrabbedMouse=False
IgnoreHat=False
ScaleJBY=0.000000
ScaleJBX=0.000000
StartupFullscreen=True
JoystickHatNumber=0
JoystickNumber=0
UseJoystick=False
ParticleDensity=0
NoFractalAnim=False
NoDynamicLights=False
Decals=True
FrameRateLimit=0.000000
MinDesiredFrameRate=0.000000
NoLighting=False
ScreenFlashes=True
SkinDetail=High
TextureDetail=High
CurvedSurfaces=False
CaptureMouse=True
Brightness=0.600000
MipFactor=1.000000
FullscreenColorBits=32
FullscreenViewportY=1080
FullscreenViewportX=1920
WindowedColorBits=32
WindowedViewportY=1050
WindowedViewportX=1920
VSync=False
FPSLimit=200

[Cluster.ClusterAudioSubsystem]
UseCDMusic=True
UseDigitalMusic=True
CDMusicVolumeFactor=1.000000
MusicVolume=255
SoundVolume=208
EffectsChannels=16

[UMenu.UMenuNetworkClientWindow]
bShownWindow=True

[Botpack.LadderTransition]
CityIntroHUDClass=
bNoMonsters=False
bHumansOnly=False
bCoopWeaponMode=False
bClassicDeathMessages=False
MinFOV=80.000000
MaxFOV=130.000000
MaxNameChanges=0
```

**Closed** 2021-03-10 23:27 UTC
Labels: fixed for 469b, video
