### ISSUE TITLE
[win][469a] OpenAL Audio / Cluster 3D Audio issues / volume too quiet even when set at maximum

### ISSUE THREAD

**Issue by garry-ut99** [OldUnreal/UnrealTournamentPatches#115] opened 2020-10-15 22:08 UTC
As per this incident: https://ut99.org/viewtopic.php?p=123376#p123376

I have no intention of spamming.
Just recreating the issue to keep integrity of the bug tracker.
The original thread shows now 404: https://github.com/OldUnreal/UnrealTournamentPatches/issues/47
Can't restore comments coz nobody remembers them, 
but it was a medium-long thread: 12 comments,
from 3 people experiencing the issue,  OP +  2 other
and the thread / issue has been labeled as `audio`

There have been 4 people experiencing the issue:

> OP (gargul2) : Various volume / sound issues with OpenAL Audio / Cluster 3D Audio issues, I fallback to 3D Galaxy Audio, including weapons volume level issues

and

> zero-khan : https://github.com/OldUnreal/UnrealTournamentPatches/issues/67#issue-713224171 : Another difference: OpenAL audio is much much quieter than Cluster. Cluster is way louder.

and

> raynor : https://ut99.org/viewtopic.php?p=123260#p123260 : My preliminary testing shows that **there is something seriously off with ClusterAudio music volume on different maps.**
DM-Gothic for example has noticeably lower playback volume compared to DM-Pressure or DM-Codex. Galaxy had no such issues.

and

> lumi1776 : https://github.com/OldUnreal/UnrealTournamentPatches/issues/146 :
> In relation to Tactical-ops
> All sound optiions do not work as expected.
> All options AL, Cluster and Galaxy do not give acurate sound location in game especially compared to the old galxay audio
> With cluster you may even loose all sounds entirely related to your player but hear everything else but with no locations. the sound is all around you.
> AL audio cant seem to balance left right and middle accurately
> None can gauge distance or locations
> The old galaxy audio works in 451
> Unfortunately not useable at present
> 
> Thanks guys for your efforts so far :D

**Comment by garry-ut99** [comment] 2021-03-19 13:28
From the 1st comment:

> > raynor : https://ut99.org/viewtopic.php?p=123260#p123260 : My preliminary testing shows that **there is something seriously off with ClusterAudio music volume on different maps.**
> > DM-Gothic for example has noticeably lower playback volume compared to DM-Pressure or DM-Codex. Galaxy had no such issues.

now, after UT 469b patch has been released, raynor says that he stiil has some audio issues:

> raynor : https://ut99.org/viewtopic.php?f=1&t=14127&start=120#p127284 : 469b Cluster audio balance still feels off compared to Galaxy. For example ammo pickup, weapon switching and dodge grunt sounds are considerably quieter compared to weapon firing, powerup pickup or elevator sounds. It is unfortunate there is no option to use Galaxy until such issues are resolved.

**Comment by stijn-volckaert** [comment] 2021-12-13 10:39
We've had this one open for a while but I don't think the remaining issue is going to get fixed. Just to summarize:
1) ALAudio and Galaxy both had spatialization issues in 469a. These got fixed in 469b.
2) We have never been able to reproduce the problem with inconsistent music volumes even when we measured volumes using audacity
3) The sound balance mismatch between Cluster and Galaxy is caused by their respective back-ends. Galaxy uses Carlo Vogelsang's Galaxy Music back-end. Cluster uses FMOD Engine. Both are proprietary back-ends.
4) It is not, nor has it ever been, our intention to offer three audio drivers that have 100% identical audio output. If you do not like ALAudio or Cluster, then feel free to switch back to Galaxy
5) We deprecated Galaxy in 469a because there were some serious issues with its back-end and we couldn't fix them at the time. These issues have since been resolved, so we will remove the deprecation warning in 469c

**Closed by stijn-volckaert** 2021-12-13 10:39 UTC
Labels: wontfix, audio, fixed in the next patch
