### ISSUE TITLE
[469c] Ued: Add Axis orientation option when placing a 2D shape brush

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#1178] opened 2023-01-26 14:40 UTC
When you're placing a 2D shape brush in the viewport, you have no control over which Axis orientation the brush will appear. Right now, 2D shape editor places your brush in a horizontal orientation, it would be nice if you can have control over which orientation the brush is going to be placed in. For the most cases it always needs to be in a vertical orientation.

Possible implementation:
Add the Axis dropdown menu from the SheetBuilder brush into the 2D shape editor window, it could be placed on the empty spot on top right.
![Screenshot_208](https://user-images.githubusercontent.com/58362332/214862742-3cabf8f5-2d4a-4057-a591-92f69f59b4d5.png)

**Comment by SeriousBuggie** [comment] 2023-01-26 15:23
Duplicate of #711

**Closed** 2023-01-26 15:27 UTC
