### ISSUE TITLE
[469c] Demo manager - ScriptWarning

### ISSUE THREAD

**Issue by alsosed** [OldUnreal/UnrealTournamentPatches#1190] opened 2023-02-06 18:42 UTC
Client log:
ScriptWarning: AutoRecorder Transient.AutoRecorder0 (Function udemo.AutoRecorder.NotifyLevelChange:0043) Accessed None 'PlayerReplicationInfo'
ScriptWarning: AutoRecorder Transient.AutoRecorder0 (Function udemo.AutoRecorder.NotifyLevelChange:004B) Attempt to assign variable through None

**Comment by alsosed** [comment] 2023-02-07 06:25
> Possible it need move to https://github.com/stijn-volckaert/udemo
as far as me know, udemo is now part of the patch

**Comment by SeriousBuggie** [comment] 2023-05-13 19:00
Duplicate of #314

**Closed** 2023-11-16 00:08 UTC
Labels: bug, UnrealScript
