### ISSUE TITLE
[469b] UnrealEd crash on 3D preview (Software) on CTF-EpicBoy

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#540] opened 2021-09-07 21:21 UTC
Reproduce:
1. Open UnrealEd with map [ctf-epicboy.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7124401/ctf-epicboy.zip)
2. Use Texture mode in viewport.
3. Use Software render.
4. Search actor `Brush720`.
5. Little rotate to right and go back for make view like this:
![scr_1631048954](https://user-images.githubusercontent.com/70026933/132411907-5d3b0fa6-d17b-45c2-af1d-cf1fad04932a.png)
6. Enable game mode.

Expected result: no crash.
Actual result: crash.

> History: USoftwareRenderDevice::DrawComplexSurface <- URender::DrawFrame <- URender::DrawWorld <- UEditorEngine::Draw <- (Cam=U2Viewport0,Flags=4041 <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- UEditorEngine::Tick
> SE(C0000005) @ 778FA3F5
> fl=0 rec=0 n=0 i[0]=0 i[1]=3eb5aa93
> eax=00000000 ebx=3eb5aa93 ecx=00000000 edx=08030270 esi=000002b9 edi=19868210 eip=778fa3f5
> ebp=779ac9f8 esp=0219e00c cs=0023 ds=002b es=002b fs=0053 gs=002b flags=00010246
>  <- UpdateWorld <- MainLoop

v436 crash, even before enable game mode.
v469b and v469c - crash.

Not sure if same reason or no, UnrealEd able crash with win crash, not UnrealEd crash.

**Comment by NeonKnightOA** [comment] 2021-09-08 13:46
So EpicBoy causes a lot of problems in addition to a very old one that was already fixed (having two Screenshot textures with the same name).

**Comment by stijn-volckaert** [comment] 2021-09-22 10:14
I can't reproduce this. Do you know any other way to trigger this crash?

**Comment by SeriousBuggie** [comment] 2021-10-03 13:42
No. I record video about that. Maybe you see something which help you reproduce crash.
I use v469b here.

https://user-images.githubusercontent.com/70026933/135755995-2970cba2-0575-4a45-a2a7-522c8fc1ca8a.mp4


https://user-images.githubusercontent.com/70026933/135756099-faf0684e-9db0-4f26-a151-be8049bbcf57.mp4



https://user-images.githubusercontent.com/70026933/135756197-6d88356d-a33c-4bf3-9728-5db46d18bc27.mp4

**Comment by stijn-volckaert** [comment] 2022-03-25 14:09
Confirmed duplicate of #764

**Closed by stijn-volckaert** 2022-03-25 14:09 UTC
Labels: bug, duplicate, Windows, rendering, fixed in the next patch
