### ISSUE TITLE
[469a] Relics look strange

### ISSUE THREAD

**Issue by DarkBeemo** [OldUnreal/UnrealTournamentPatches#26] opened 2020-09-24 23:09 UTC
The Relics of Strength and Regeneration have some strange graphical issues, no matter which renderer I use -- they look like they have "holes" in them or something.
![94089300-766f7280-fdd8-11ea-93fd-2cc25b6d42aa](https://user-images.githubusercontent.com/71798183/94208608-db39d400-fe8f-11ea-9b64-a4f364b224f6.jpg)
![94089320-7ec7ad80-fdd8-11ea-87d5-222068a84e6a](https://user-images.githubusercontent.com/71798183/94208613-de34c480-fe8f-11ea-9146-e379ff141a82.jpg)

Version 451 has also given me this problem in the past, where I was also having this problem with a couple of other relics, and the "Nali WarCow" player model. I did not have this problem with 436.

Again, this happens with all renderers (they all work fine for the most part otherwise!). I am using version 469a, but I have also encountered this problem on version 451.

You may also take a look at my game's .ini file -- it may help: [Beemo'sINI.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5279683/Beemo.sINI.zip)

Windows 10 Home Edition, Version 2004
Intel Core i5-9300H @ 2.40 GHz
Intel UHD Graphics 630
NVIDIA GeForce GTX 1650

**Comment by Chamberly** [comment] 2020-09-27 23:46
Looks like the black area ended up as transparent.

**Comment by sn260591** [comment] 2020-09-28 11:04
It looks like this is due to the fact that the `bMasked` property of textures has become more priority over the `Style` property of actors.

**Comment by CacoFFF** [comment] 2020-09-28 12:18
We'll probably have to update Relics.u... if we get the source data (or properly export it)

**Comment by stijn-volckaert** [comment] 2022-10-22 13:37
Confirmed. This is the result of a fix that was originally written for the Linux version of UT and that was merged into the main repository on April 15, 2003. All UT versions since then render the strength and regeneration relics incorrectly.

The fix merges the PolyFlags of every mesh's texture into the PolyFlags applied to the mesh during rendering. Before the fix, the mesh PolyFlags would depend only on the Actor Style and, for LOD Meshes, the PolyFlags of the material.

Rather than reverting this fix, we will just remove the PF_Masked PolyFlag from the Relics textures. We'll include the updated Relics.u in the 469c patch.

**Closed** 2022-10-22 13:56 UTC
Labels: bug, rendering, fixed in the next patch
