### ISSUE TITLE
When trying to start the game it fails to launch.

### ISSUE THREAD

**Issue by AfricHR** [OldUnreal/UnrealTournamentPatches#1453] opened 2023-11-18 15:05 UTC
I've downloaded multiple different versions and release candidates and for all of them when I try to open the game it says "critical error, could not load splash logo: ..\Help\Logo.bmp" and then another line under "History:" and after that its empty. I've tried figuring it out on my own but I've failed. I'm not sure if its a problem on my end or not.

**Comment by SeriousBuggie** [comment] 2023-11-18 15:21
Patch is like addon to original Game. You still need original game for able use patch.
You can't unpack patch to empty folder and run it. You need unpack it into folder with game.

Duplicate of #1247

**Closed by SeriousBuggie** 2023-11-18 15:21 UTC

**Comment by AfricHR** [comment] 2023-11-18 15:26
where can I install the original game now?

**Comment by SeriousBuggie** [comment] 2023-11-18 16:02
You need buy it somewhere. It is out of scope this patch.
