### ISSUE TITLE
[469b] Brush Clip tool misalignment bug

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#580] opened 2021-11-06 22:29 UTC
If you select a brush inside the 3D view port, then select the Brush Clip tool and try to clip it in the 2D viewport, misalignment bug between the clip points and brush points will happen. Here is how to reproduce:

https://user-images.githubusercontent.com/58362332/140625417-aed0d51d-1bad-4d58-98d4-8de033aff741.mp4

Here is the map file for reference:
[BrushClip_Bug.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7491337/BrushClip_Bug.zip)

**Comment by SeriousBuggie** [comment] 2024-04-14 08:03
Can't reproduce on latest test build. Can you reproduce it?
![scr_1713081623](https://github.com/OldUnreal/UnrealTournamentPatches/assets/70026933/9716e35d-d1f8-4bed-a5ec-1d79a3d43a46)

**Comment by SeriousBuggie** [comment] 2024-04-14 12:20
Look like fixed in 469d or 469c. I will mark it as fixed in 469d.

**Closed** 2024-04-14 15:09 UTC
Labels: UnrealEd
