### ISSUE TITLE
[469c] UnrealEd: Assigning sound of pre-loaded sound packages does not work

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#626] opened 2021-12-07 11:20 UTC
Steps to reproduce:
1) Select any sound of a pre-loaded sound package, for example "Female1Voice.F1Boom" (aka ""Female1Voice.(All).F1Boom").
2) select property "AmbientSound" of any existing Actor in map or "SpecialEvent.Sound"
3) press button "use"
v436: expected result: "Sound'Female1Voice.(All).F1boom'" is put into property value field
v469c: nothing happens, property value field stays empty (note: if doing this with another NOT pre-loaded sound package, it works)

**Comment by SeriousBarbie** [comment] 2021-12-07 11:23
Some more tests lead me to the assumption that the brackets () in the name prevent taking over the name.

**Comment by SeriousBuggie** [comment] 2021-12-07 12:09
Duplicate of #518

**Closed** 2021-12-08 10:49 UTC
