### ISSUE TITLE
[469a] The pawns highlight when looking through the scope of a sniper rifle from NaliWeapons3 does not work correctly

### ISSUE THREAD

**Issue by sn260591** [OldUnreal/UnrealTournamentPatches#202] opened 2021-01-31 08:45 UTC
In 469, the cow behind the wall ceased to be translucent, and the corpse became much lighter. 
Test map: [nw3_sniper.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/5899389/nw3_sniper.zip)

### 436:
![436](https://user-images.githubusercontent.com/10724977/106378696-d7770a80-63b7-11eb-8ed7-667368f84662.jpg)

### 469:
![469](https://user-images.githubusercontent.com/10724977/106378709-efe72500-63b7-11eb-9532-dc3900243d38.jpg)

**Comment by Feralidragon** [comment] 2021-02-07 17:37
In the new 469 patch, stuff which is unlit is 2x brighter than in 436, and that is because before unlit stuff was capped at 50% brightness, but not anymore, meaning that now it can go all the way to 100%.

For most things you won't see a big difference, but in the case of NW3 I use a lot of stuff which is unlit, and which I control the brightness through the ScaleGlow property.

In this case, the "heat" vision is performed by rendering the heat-emitting stuff (like the nali cows in your screenshot) as unlit with a completely white texture, using the normal style when you see them directly (opaque) and translucent when they are behind a wall (transparent).

However, since this change, a translucent white texture will be rendered as fully opaque at 100% brightness, unlike before, and that's what's happening there.

What you can do to solve this is to reduce the glow values in the `NWeaponsCfg.ini` file, namely:
```ini
SensedHeatObjects[0]=(HeatObjectType="Pawn",AmountOfHeat=3.000000,bFadingHeat=False)
SensedHeatObjects[1]=(HeatObjectType="TeamCannon",AmountOfHeat=0.750000,bFadingHeat=False)
SensedHeatObjects[2]=(HeatObjectType="sgBuilding",AmountOfHeat=0.750000,bFadingHeat=False)
SensedHeatObjects[3]=(HeatObjectType="Cybot",AmountOfHeat=0.850000,bFadingHeat=False)
SensedHeatObjects[4]=(HeatObjectType="CybotPart",AmountOfHeat=0.850000,bFadingHeat=False)
SensedHeatObjects[5]=(HeatObjectType="CybAttach",AmountOfHeat=0.850000,bFadingHeat=False)
SensedHeatObjects[6]=(HeatObjectType="Carcass",AmountOfHeat=0.900000,bFadingHeat=True)
SensedHeatObjects[7]=(HeatObjectType="WarShell",AmountOfHeat=0.750000,bFadingHeat=False)
SensedHeatObjects[8]=(HeatObjectType="StrangeShell",AmountOfHeat=0.750000,bFadingHeat=False)
SensedHeatObjects[9]=(HeatObjectType="DumbRocket",AmountOfHeat=0.750000,bFadingHeat=False)
SensedHeatObjects[10]=(HeatObjectType="NuclearMissile",AmountOfHeat=0.750000,bFadingHeat=False)
SensedHeatObjects[11]=(HeatObjectType="TranslocatorTarget",AmountOfHeat=0.550000,bFadingHeat=False)
SensedHeatObjects[12]=(HeatObjectType="RTTrans",AmountOfHeat=0.550000,bFadingHeat=False)
```
to 1/2 or 1/3 of the value, like:
```ini
SensedHeatObjects[0]=(HeatObjectType="Pawn",AmountOfHeat=1.000000,bFadingHeat=False)
SensedHeatObjects[1]=(HeatObjectType="TeamCannon",AmountOfHeat=0.400000,bFadingHeat=False)
SensedHeatObjects[2]=(HeatObjectType="sgBuilding",AmountOfHeat=0.400000,bFadingHeat=False)
SensedHeatObjects[3]=(HeatObjectType="Cybot",AmountOfHeat=0.450000,bFadingHeat=False)
SensedHeatObjects[4]=(HeatObjectType="CybotPart",AmountOfHeat=0.450000,bFadingHeat=False)
SensedHeatObjects[5]=(HeatObjectType="CybAttach",AmountOfHeat=0.450000,bFadingHeat=False)
SensedHeatObjects[6]=(HeatObjectType="Carcass",AmountOfHeat=0.350000,bFadingHeat=True)
SensedHeatObjects[7]=(HeatObjectType="WarShell",AmountOfHeat=0.400000,bFadingHeat=False)
SensedHeatObjects[8]=(HeatObjectType="StrangeShell",AmountOfHeat=0.400000,bFadingHeat=False)
SensedHeatObjects[9]=(HeatObjectType="DumbRocket",AmountOfHeat=0.400000,bFadingHeat=False)
SensedHeatObjects[10]=(HeatObjectType="NuclearMissile",AmountOfHeat=0.400000,bFadingHeat=False)
SensedHeatObjects[11]=(HeatObjectType="TranslocatorTarget",AmountOfHeat=0.250000,bFadingHeat=False)
SensedHeatObjects[12]=(HeatObjectType="RTTrans",AmountOfHeat=0.250000,bFadingHeat=False)
```
and you should be able to see everything fairly normalized again.

It's worth to note that this change in the patch was intended, and is also something I have personally struggled with, hence why I tried to overcompensate in the configuration so that stuff like this was rendered at the highest brightness values as possible.

**Comment by sn260591** [comment] 2021-02-08 08:54
@Feralidragon Thanks for the help, the solution works in single player, but the server `unreal://89.163.162.10:8888` ignores the config.

**Comment by Feralidragon** [comment] 2021-02-13 13:43
This is a server-side configuration which is then replicated to clients so they all play with the same settings in the same server, so setting the .ini file in the server should work just fine.

As a matter of fact, I just did the experiment myself, and I set up a dedicated server with that configuration, and then used a different client to connect and play in that server, and the changes I made server-side were correctly replicated to the client as expected (and I tested both cases: original configuration and modified configuration).

So my question to you is: did you set the configuration server-side, or were you trying to set it client-side?
Setting it client-side won't work in multiplayer in this case, only server-side.

**Comment by sn260591** [comment] 2021-02-13 17:13
@Feralidragon I am not the owner of this server. What should I and other players do in this case?

**Comment by Feralidragon** [comment] 2021-02-13 17:54
NW3 has many settings which can be set both server and client side, as long as in my (very subjective) opinion do not influence gameplay.

In this case this setting does influence gameplay, hence why it's a server-only setting, which only the server owner can actually change, as otherwise any player could just make whatever they want to be rendered as having "heat", or having more or less heat than supposed, which would be equivalent to cheating.

Therefore, the only thing you can do is to contact the admins of those servers and ask them to apply the configuration I have shown above in their servers (you can link them to this thread).

One other thing you might do is to open another issue here, referencing this one, to request a new configuration setting in the base game in a future patch to allow you to toggle between unlit behavior (like `bUseOldUnlit`, as an example).

I could also in the future release a NW3 patch to address this issue, by checking the game version the mod is running on and adjust these values accordingly (even because this is not the only thing it affects, I noticed a few other things as well), but that's a pandora box I don't really want to open yet, given that if I do that then players will get the (wrong) impression that the mod is somewhat under active development again and receiving patches again like the base game.

Case in point: a while ago I released a video showing off the NW3 Ultimaprotos explosion at the highest settings (it would crash or be very slow in 436, whereas in 469 is fast and doesn't crash at all), and some people took the wrong impression that I was going to release more UT99 stuff in the future, which is not necessarily true, so although I was going to release more videos, I ceased to due to that, so that's something I need to be somewhat careful about (even years later the mod is far more popular than I had anticipated it to be so far down the road).

Not saying I won't ever fix it, but if I do then that's not the only thing I will fix, and I cannot allocate the kind of time I need to do it right now, meaning that your only options for now is to contact the admins or request the setting I mentioned.

**Comment by sn260591** [comment] 2021-02-14 07:37
> Therefore, the only thing you can do is to contact the admins of those servers and ask them to apply the configuration I have shown above in their servers (you can link them to this thread).

Not suitable in this case as some players still use 436/451.

> One other thing you might do is to open another issue here, referencing this one, to request a new configuration setting in the base game in a future patch to allow you to toggle between unlit behavior (like bUseOldUnlit, as an example).

It looks like this is the best option. I will do so.

**Comment by stijn-volckaert** [comment] 2021-03-13 14:27
I am going to close this issue because the feature request now has its own issue.

**Closed by stijn-volckaert** 2021-03-13 14:27 UTC
Labels: invalid
