### ISSUE TITLE
could not load splash logo: ../help/logo.bmp issue

### ISSUE THREAD

**Issue by pikachuproge** [OldUnreal/UnrealTournamentPatches#1308] opened 2023-06-29 10:17 UTC
when i launch this game it just shows this error right after launching the unreal tournament

**Comment by pikachuproge** [comment] 2023-06-29 10:44
![image](https://github.com/OldUnreal/UnrealTournamentPatches/assets/73906705/555e6adf-54ff-4bce-9cd1-626dd4892609)
here is the image i forgot to put

**Comment by SeriousBuggie** [comment] 2023-06-29 11:19
Duplicate of #1247
And related to #1248

**Comment by stijn-volckaert** [comment] 2023-07-03 12:17
Confirmed duplicate of #1247

**Closed by stijn-volckaert** 2023-07-03 12:17 UTC
