### ISSUE TITLE
Rapidly spinning viewport

### ISSUE THREAD

**Issue by shai-ut99** [OldUnreal/UnrealTournamentPatches#1232] opened 2023-04-13 17:32 UTC
This is something that has only been observed on a very small number of maps in 469 (it doesn't occur using 436), so I don't know what the common denominator is.

However, one example map where you can see this happening is: http://www.i4games.eu/maps/CTF-BT-ConfrontatioNuLLFINAL

If you open this map, and step onto the jump pad in the spawn room, your viewport goes into a sudden, and very fast, spin.

**Comment by stijn-volckaert** [comment] 2023-05-02 08:57
Confirmed duplicate of #728. I pushed a fix for this bug yesterday. The fix will be included in the next preview build for 469d. Come talk to us on Discord if you want access to these previews.

**Closed by stijn-volckaert** 2023-05-02 08:57 UTC
Labels: bug, duplicate, fixed in the next patch
