### ISSUE TITLE
[469b] UnrealED, When you have a maxed out window and close Ued, relaunching Ued will make the window bugged

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#561] opened 2021-10-15 02:04 UTC
Happens on 469c too

https://user-images.githubusercontent.com/58362332/137420755-ec80fef6-7b0b-422f-bcd1-3f2c04863381.mp4

**Comment by BerserkerBG** [comment] 2021-10-15 16:46
Related issue, same concept. WHen you have a maximized viewport in Ued, if you try to minimize and maximize Ued itself, the viewport maximize bug occurs and you have to reset them every time to get fixed (as shown in video).

https://user-images.githubusercontent.com/58362332/137523486-2f744a0e-ad35-4abc-a009-c4fe7db2f550.mp4

**Comment by stijn-volckaert** [comment] 2021-11-19 13:27
This seems to be a duplicate of #66

**Closed** 2021-12-27 13:56 UTC
Labels: bug, duplicate, UnrealEd
