### ISSUE TITLE
Can't quickload.

### ISSUE THREAD

**Issue by CortexReaver** [OldUnreal/UnrealTournamentPatches#1680] opened 2024-12-02 19:51 UTC
While playing a Xidia gold mod I quicksaved in a machine gun room. After that I cannot quicksave anywhere in any mod, game gives me a error:
![02-12-2024 224017](https://github.com/user-attachments/assets/cd482d6a-2a1e-4b17-94f4-56f198551536)

Someone has a very similar problem to what I have: https://www.oldunreal.com/phpBB3/viewtopic.php?t=10255&sid=22566e39cd0c462838a62e16a3b6c0fa&start=25

**Comment by CortexReaver** [comment] 2024-12-03 08:11
So, this is a short demonstration how this bug works: https://youtu.be/zZ77mD7nX5s

Save\loading working perfectly fine, until this specific moment in this mod. After that you cannot save anywhere and quicksave slot become corrupted.

**Comment by SeriousBuggie** [comment] 2024-12-03 08:17
I guess we already fix this for 469e. You can come to discord and ask Anthrax add you to beta tester group so you can test if this issue fixed on 469e.
Full instruction here:
https://ut99.org/ut99.org/viewtopic.php?p=148685#p148685

**Comment by SeriousBuggie** [comment] 2024-12-03 08:23
I will close this one as duplicate of #1446

**Closed by SeriousBuggie** 2024-12-03 08:23 UTC
