### ISSUE TITLE
[469b] Crash after GC with OBJCLEAN if newly spawned actors immediatly destroyed

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#563] opened 2021-10-16 08:13 UTC
Reproduce:
1. Run [dm-!!!!!GC_bug.zip](https://github.com/OldUnreal/UnrealTournamentPatches/files/7357204/dm-.GC_bug.zip)

Expected result: No crash.
Actual result: crash:
```
General protection fault!

History: TickAllActors <- ULevel::Tick <- (NetMode=0) <- TickLevel <- UGameEngine::Tick
SE(C0000005) @ 003A0069
fl=0 rec=0 n=0 i[0]=8 i[1]=3a0069
eax=003a0069 ebx=013d1d2c ecx=0d7ed0b4 edx=0d7ed0b4 esi=0d9e14a4 edi=0df63490 eip=003a0069
ebp=0115f2d4 esp=0115f214 cs=0023 ds=002b es=002b fs=0053 gs=002b flags=00010202
 <- UpdateWorld <- MainLoop
```

Issue exists for v436, v469b, v469c [preview].

Code for make crash:
```
class Gidra expands Actor;

var() int items;

function Spawned() {
    Default.items++;
}

function Tick(float Delta) {
    local int i;
    if (Default.items > 1)    
        return;
    for (i = 0; i < 1000; i++)
        Spawn(Class).Destroy();
    GC();        
}

function GC() {
    ConsoleCommand("OBJ GARBAGE");
    ConsoleCommand("OBJCLEAN");
    ConsoleCommand("FLUSH");
}
```

Explanation:
During Tick some actors created and immediately destroyed. Actors created during Tick call go to linked list for tick them later.
Later walk on this list call Tick for each Actor. If Actor deleted (bDeleteMe = true), then tick not called. 
But OBJCLEAN free actor memory. So linked list try call tick on freed memory.
OBJCLEAN called during Tick. (Timer originally, which called from Tick too). So OBJCLEAN run in middle of Tick and some stuff handle in this Tick after GC.

**Comment by an-eternity** [comment] 2021-10-17 13:54
Now when i try to recall all the related occurrences from the past that i forgotten, it appears it was not only 1 crash on "ObjClean" with v469b, but more...

This case reported here at June 2 with v469b was exactly the same crash, and a 'ShockProj' class projectile was also involved there: https://www.oldunreal.com/phpBB3/viewtopic.php?p=98430#p98430
Somehow we managed to reproduce it several times back then, but it was just a good luck and then all the further attempts to reproduce it failed, "traces" were lost and the case was abandoned and forgotten...

Few days ago this crash appeared again during fixing/debugging of another map, and already with v469c (for the first time).
In that map were 2 'ScriptedPawn' classes in one huge location together - one of them spawns a 'ShockProj' class projectile, another one spawns a modified 'ShockProj' projectile class that is able to interact with normal 'ShockProj' class projectiles and to destroy them.
Moreover - that modified 'ShockProj' projectile class had LifeSpan==0 and bBounce==True (and by the way, big thanks these great minds at least guessed to remove "bNetTemporary=False" from defaultproperties in their mod after copy-paste from the original 'ShockProj' script). Of course with LifeSpan==0 a whole location gets spammed with 10-th's thousands of these projectiles in a few minutes, that makes server non-responsible. For that reason we set LifeSpan to 600 seconds in order to keep at least ~15000 projectiles existing in every single moment, so that server is able to be functioning at normal tickrate value as long as we need. With such condition this crash, in most of the cases, happened within 60-70 minutes, and in a very rare cases it happened in a few minutes. "ObjClean", as usually, was called after every 3.5 minutes.

Though a way to reproduce this crash was finally found, it was unknown how and why this happens.
Once again thanks to Buggie for discovery of this GC bug in the native part and for the detailed explanation and the script that triggers this GC crash instantly. Now we know why exactly this crash happens.

So, for the latest case it was a coincidence of at least 4 occurrences and in the following order:
1. 'ShockProj' class projectile spawns.
2. Its ProcessTouch()->Explode() functions called (as a result of collision with another projectile).
3. "ObjClean" console command executed.
4. All 3 occurrences happen one after another in one same Tick cycle.

For all the time we test it with "ObjClean" (which is almost one year already) this crash happened only with projectiles.
But there is also "Level.Game.IsRelevant()" where, depending on many other factors, many actors with bGameRelevant==False may get spawned and destroyed in one Tick cycle. So this is one else potential case for this crash. I suppose we still didn't have crash this way only because its probability is relatively low...
Probably there might be some else cases where actors get spawned and destroyed in the same Tick cycle, and so may trigger this crash if happen with "ObjClean" in same Tick cycle...

![ut99_GC-crash-discover_211017](https://user-images.githubusercontent.com/72374425/137627887-2817d311-2834-4957-be55-70c387ae5ea3.png)

**Comment by SeriousBuggie** [comment] 2021-10-17 16:10
For crash happen need next steps:
1. Spawn and immediately destroy at least one actor.
2. Call GC + OBJCLEAN in same iteration. This mean call it before engine call Tick on destroyed actor.

So if some conditions not met, issue not happen.
For example destroy actor after first tick, or after GC.

**Comment by an-eternity** [comment] 2021-10-17 16:58
Since Tick() and Timer() is not safe to use for GC calls until this problem is fixed in the native part, a question appears - is there another Events which are safe to use for GC calls?
I tried to test this in Destroyed() Event, but it crashes anyway.

**Comment by SeriousBuggie** [comment] 2021-10-18 05:44
No any safe place, because all events called inside Tick.

As I see, no any way call `OBJCLEAN` without possible crash. So better avoid it until issue not fixed.
Maybe possible exists some heavy hacks for that but this can lead to another problems and stop work at any moment.

**Comment by Marco888** [comment] 2021-10-18 05:50
Eh wouldnt it be best to make it enable a flag which tells it to use forced CleanupDestroyed on the end of tick. Otherwise there is no safe way to deal with it..

**Comment by an-eternity** [comment] 2021-10-18 12:27
> for (i = 0; i < 128; i++)		Spawn(Class).Destroy();
Yes, it works... Makes cleanup same as ObjClean, but with no crash.
Nice temporal solution, can use it until ObjClean is fixed.

> Maybe possible exists some heavy hacks for that but this can lead to another problems and stop work at any moment.
In past days i was thinking of some fixes that would delay GC call if potentially possible Spawn/Destroy occurrence in the same Tick cycle detected, added some of them in "Level.Game.IsRelevant()", but it is practically impossible to cover all the cases this way, there are many classes that bypass this function (bGameRelevant==True or another reasons...)
Also, thought to set bProjTarget==False for all 'Projectile' classes loaded in the level, which is also not good idea...
Better to use method of 128 bDeleteMe instead...

**Comment by SeriousBuggie** [comment] 2021-10-18 16:54
Destroyed actor still valid actor with set bDeleteMe flag. Tick and other event on it not called. In other terms it complete same actor as before and access to it is safe.

Destroyed actor not in global actors lists, so not appear as result from iterators. At least must not appear.

**Comment by SeriousBuggie** [comment] 2022-06-15 07:15
Confirmed, fixed (no crash) for latest v469c preview.

**Closed** 2022-06-20 09:41 UTC
Labels: bug
