### ISSUE TITLE
[469c] Demo Manager / Chat Diamond window opens screwed/minimized

### ISSUE THREAD

**Issue by garry-ut99** [OldUnreal/UnrealTournamentPatches#1264] opened 2023-05-25 12:54 UTC
Not sure which issue tracker should it be reported to, as not sure whether the reason is UT99 or Demo Manager.
Occasionally when I want to open Demo Manager from menu, it opens screwed/minimized: [SCREENSHOOT](https://github.com/OldUnreal/UnrealTournamentPatches/assets/72945564/8b657c4a-5421-4bd3-b143-bd2e2f063b23)
In that case I need to open it again or several times until it finally appears properly: [SCREENSHOOT](https://github.com/OldUnreal/UnrealTournamentPatches/assets/72945564/0d0ae350-61c3-41fa-aa7f-6d93515dc21c)

**Comment by SeriousBuggie** [comment] 2023-05-25 13:06
Duplicate of stijn-volckaert/udemo/issues/28

**Comment by garry-ut99** [comment] 2023-05-25 13:08
Oh, ok, I missed it, despite I searched for 'demo' phrase to avoid duplicates.

**Comment by garry-ut99** [comment] 2023-08-13 16:05
The same issue happens on 469c with ChatDiamond mutator :
- https://github.com/OldUnreal/UnrealTournamentPatches/issues/1347), 

which opens it's window while LONDON server is switching levels, and sometimes it opens outside the screen,
I'm not sure whether it's a bug in ChatDiamond or in the game iself:

![bug22](https://github.com/stijn-volckaert/udemo/assets/72945564/95efa9fa-d8a9-4465-8eaf-db6a367f6715)

**Comment by SeriousBuggie** [comment] 2023-08-20 11:01
Issues with udemo and ChatDiamond, not belong to problems with game itself. It is issues with this mods, and must be addressed to these mods.

**Closed by SeriousBuggie** 2023-08-20 11:01 UTC
