### ISSUE TITLE
Collision of Mover18 in MH-Forever-Fix-2.unr broken

### ISSUE THREAD

**Issue by SeriousBarbie** [OldUnreal/UnrealTournamentPatches#1652] opened 2024-10-16 22:34 UTC
Mover18 does not work with UT OldUnreal-UTPatch469e-Windows-test745 on local play; with UT v436 it works.
[Download map on DU](http://www.destinationunreal.com/modules.php?name=maps&file=viewmap&id=647) (I can also upload the map somewhere.) 
![MH-Forever-Fix-2-Mover18](https://github.com/user-attachments/assets/61304010-6461-434c-9d4b-7360b84da6b6)

```
--- Mover Mover18 ---
  bTriggerOnceOnly=True
  KeyPos(1)=(X=-16.000000)
  BasePos=(X=1808.000000,Y=464.000000,Z=-1216.000000)
  SavedPos=(X=-12345.000000,Y=-12345.000000,Z=-12345.000000)
  SavedRot=(Pitch=123,Yaw=456,Roll=789)
  MainScale=(SheerAxis=SHEER_ZX)
  PostScale=(SheerAxis=SHEER_ZX)
  Level=LevelInfo'MyLevel.LevelInfo0'
  Tag="Mover"
  Event="stoned"
  Region=(Zone=WaterZone'MyLevel.WaterZone5',iLeaf=2612,ZoneNumber=20)
  Location=(X=1808.000000,Y=464.000000,Z=-1216.000000)
  OldLocation=(X=1808.000000,Y=464.000000,Z=-1216.000000)
  bSelected=True
 Begin Brush Name=Model1524
    Begin PolyList
       Begin Polygon Texture=Dark1 Link=0
          Origin   +00023.999996,+00015.999977,+00007.999993
          Normal   +00000.000000,+00000.000000,+00001.000000
          TextureU +00000.000000,-00001.000000,+00000.000000
          TextureV +00001.000000,+00000.000000,-00000.000000
          Vertex   +00023.999996,+00015.999977,+00007.999993
          Vertex   -00024.000000,+00015.999975,+00007.999993
          Vertex   -00023.999996,-00015.999977,+00007.999993
          Vertex   +00024.000000,-00015.999975,+00007.999993
       End Polygon
       Begin Polygon Texture=Dark1 Link=1
          Origin   +00024.000000,-00015.999975,+00007.999993
          Normal   +00000.000000,-00001.000000,+00000.000000
          TextureU +00000.000000,+00000.000000,-00001.000000
          TextureV +00001.000000,+00000.000000,+00000.000000
          Vertex   +00024.000000,-00015.999975,+00007.999993
          Vertex   -00023.999996,-00015.999977,+00007.999993
          Vertex   -00023.999996,-00015.999977,-00007.999993
          Vertex   +00024.000000,-00015.999975,-00007.999993
       End Polygon
       Begin Polygon Texture=Dark1 Link=2
          Origin   +00024.000000,-00015.999975,-00007.999993
          Normal   +00000.000000,+00000.000000,-00001.000000
          TextureU -00000.000000,+00001.000000,+00000.000000
          TextureV +00001.000000,+00000.000000,+00000.000000
          Vertex   +00024.000000,-00015.999975,-00007.999993
          Vertex   -00023.999996,-00015.999977,-00007.999993
          Vertex   -00024.000000,+00015.999975,-00007.999993
          Vertex   +00023.999996,+00015.999977,-00007.999993
       End Polygon
       Begin Polygon Texture=Dark1 Link=3
          Origin   +00023.999996,+00015.999977,-00007.999993
          Normal   -00000.000000,+00001.000000,+00000.000000
          TextureU +00000.000000,-00000.000000,+00001.000000
          TextureV +00001.000000,+00000.000000,+00000.000000
          Vertex   +00023.999996,+00015.999977,-00007.999993
          Vertex   -00024.000000,+00015.999975,-00007.999993
          Vertex   -00024.000000,+00015.999975,+00007.999993
          Vertex   +00023.999996,+00015.999977,+00007.999993
       End Polygon
       Begin Polygon Texture=Dark1 Link=4
          Origin   -00023.999996,-00015.999977,+00007.999993
          Normal   -00001.000000,-00000.000000,+00000.000000
          TextureU +00000.000000,-00000.000000,-00001.000000
          TextureV +00000.000000,-00001.000000,+00000.000000
          Vertex   -00023.999996,-00015.999977,+00007.999993
          Vertex   -00024.000000,+00015.999975,+00007.999993
          Vertex   -00024.000000,+00015.999975,-00007.999993
          Vertex   -00023.999996,-00015.999977,-00007.999993
       End Polygon
       Begin Polygon Texture=DSWITCH4 Link=5
          Origin   +00023.999996,+00015.999977,+00007.999993
          Normal   +00001.000000,+00000.000000,+00000.000000
          TextureU +00000.000000,+00000.000000,-00001.000000
          TextureV -00000.000000,+00001.000000,+00000.000000
          Vertex   +00023.999996,+00015.999977,+00007.999993
          Vertex   +00024.000000,-00015.999975,+00007.999993
          Vertex   +00024.000000,-00015.999975,-00007.999993
          Vertex   +00023.999996,+00015.999977,-00007.999993
       End Polygon
    End PolyList
 End Brush
  Brush=Model'MyLevel.Model1524'
  PrePivot=(X=24.000067,Y=0.000001,Z=8.000007)
  CollisionRadius=10.000000
  CollisionHeight=10.000000
  Name="Mover18"

```

**Comment by SeriousBuggie** [comment] 2024-10-17 04:22
Here map with small edits: [MH-Forever-Fix-2_test.zip](https://github.com/user-attachments/files/17406024/MH-Forever-Fix-2_test.zip)

Button located in water, below player start.

**Comment by SeriousBuggie** [comment] 2024-10-17 04:27
I can confirm bug with 469e - mover can't be pushed.
However on 469d it act weird. Like there no collision at all and you collide with something far before actual mover. Way outside mover bounding box.
That sound as broken mover.

And if you rebuild movers on 469e, then mover act as should.

**Comment by SeriousBuggie** [comment] 2024-10-17 04:30
Also if you goes on 469d from right side to left, from wall, mover not collide either.
It collide only if you goes forward to it, or from left to right near wall.

**Comment by SeriousBarbie** [comment] 2024-10-17 09:57
If this is a singular issue I would not mess around with broken maps; I'd just rebuild and then publish it. But what about the holy backward compatibility then? :-P

**Comment by SeriousBuggie** [comment] 2024-10-17 10:23
We will talk with team internally about that.
However sometimes need draw line. Which bug considered as need maintain, and which no.

**Comment by SeriousBuggie** [comment] 2024-10-17 14:56
Here how collision happen on 469d:

https://github.com/user-attachments/assets/20a8ef07-2d12-4bdc-909b-204522066491

From right side not collide.
From left front and bottom collide with brush when far away from it.

**Comment by SeriousBuggie** [comment] 2024-10-18 21:46
Mover bugged. It created from default cube 256x256x256, and later vertex edit to smaller size - 48x32x16.

So mover use two bounding box. Outer is 48x32x16 and internal one 256x256x256. Normally they must match.

Collision hash implementation can't handle this properly. So on this mover collide only few planes from inner box (big one).
That be left one and front one. And even they collide partially.

If all planes collide properly on big box, button will be able push from top via ground. 

that how really look collision model of this mover:
![img](https://github.com/user-attachments/assets/599c02ac-f39f-4593-83cc-cd311697a2b9)
![img](https://github.com/user-attachments/assets/0b99b668-4534-4c77-86cf-ac74982afb07)
![img](https://github.com/user-attachments/assets/60878a34-f4cd-42c0-bac1-dd56fad72847)
![img](https://github.com/user-attachments/assets/0017297c-8ee5-4136-b8d2-16f9547ae857)

Detail of implementation of collision hash make collide only few planes of it.
So this is broken map, which need be fixed.

**Comment by SeriousBuggie** [comment] 2024-10-19 07:36
Pushed fix, which you can test on test build 769.
Can be turned off by set [Engine.GameEngine] FixUpMoversBoundingBox to False.

However this fix discover true nature of this movers - big huge cube 256x256x256.
We can't reproduce bugged behavior of FCollisionHash, which can be:
- walls which not pass hitscan, but pass projectile and players
- walls which not pass hitscan and projectiles.but pass players
- shoot inside this box immediately blown projectile.
- shoot into mover make effects appear not on wall, but on virtual wall, but only if trace end on mover.
- walls which work in one way (can make trap)
- from 5 reachable walls, only 2 collide with player. 

In exact this case there only few walls which collide with player, and this walls can change during mover movement.

**Comment by SeriousBarbie** [comment] 2024-10-19 08:33
I'll fix that map.

**Comment by SeriousBuggie** [comment] 2024-11-10 19:02
Improve fix for broken movers. 
Now fix support 3 values for Engine.GameEngine.FixUpMoversBoundingBox (set in ini as number):

0 - None
1 - Full
2 - pre-469e (default)

However if you disable octree via set Engine.GameEngine.UseOctreeCollisionHash to False, then 2 (pre-469e) will act as 0 (none).

Add warning on save map with broken movers.

![scr_1731264410](https://github.com/user-attachments/assets/0599a8ff-b18f-4b5e-9a46-1a1178c0f951)

**Comment by SeriousBuggie** [comment] 2024-11-11 02:25
With latest fix collision size of bugged button in fix mode (pre-469e), goes be enough moderate.
Even not collide from top. It visible, but you can't touch it. 

![scr_1731291804](https://github.com/user-attachments/assets/afdb71de-f5d4-4b44-bdec-a2cdaf08a76c)
![scr_1731291815](https://github.com/user-attachments/assets/40490f66-2d06-4195-8a75-310a9ef4e401)

**Closed** 2024-12-05 06:50 UTC
Labels: bug, collision, internal-fam
