### ISSUE TITLE
can no longer reach : Evil's Freestyle Sniper Deathmatch

### ISSUE THREAD

**Issue by kairos63** [OldUnreal/UnrealTournamentPatches#1311] opened 2023-07-02 00:29 UTC
Does anyone have an idea why i can no longer access server:
 [-=][-=NFR=-][=-Evil's Freestyle Sniper Deathmatch]

It was working fine for years.
Now i get Connection failed:
Can't find file for package ACEv12e_C.

Thanks in advance for any tips ;)

**Comment by stijn-volckaert** [comment] 2023-07-03 12:11
duplicate of #1293

**Closed by stijn-volckaert** 2023-07-03 12:11 UTC
