### ISSUE TITLE
[469b] Aspect ratio-independent weapon rendering

### ISSUE THREAD

**Issue by bjb43** [OldUnreal/UnrealTournamentPatches#496] opened 2021-07-20 19:42 UTC
Hi, first thanks a lot for your great work!

Would it be possible to include proper widescreen support (e.g. what has been done here https://github.com/alexstrout/foxWSFix-UT99) in order to have a proper weapon size and scaling in widescreen resolutions?

Thanks a lot

**Comment by alexstrout** [comment] 2022-08-15 00:16
Quick note: It would also be nice to patch the MuzzleScale and FlashO in the weapons to also be aspect-correct. See these lines for how the above widescreen fix is patching these on the fly: https://github.com/alexstrout/foxWSFix-UT99/blob/master/Classes/foxUTConsole.uc#L129-L137

Also, thank you OldUnreal patch contributors! I would never install UT'99 without 'em. :)

**Comment by stijn-volckaert** [comment] 2023-12-25 11:14
This is a duplicate of #111. We are planning to implement this feature in the next patch

**Closed by stijn-volckaert** 2023-12-25 11:14 UTC
Labels: duplicate, enhancement, UnrealScript
