### ISSUE TITLE
D3D9 & Patch 469A crashes on certain maps

### ISSUE THREAD

**Issue by OMA-Bite-Me** [OldUnreal/UnrealTournamentPatches#110] opened 2020-10-15 03:18 UTC
Hi,
It seems there is a problem with some maps.  I crashed as a new map started on the server and got the first screenshot.  When joining back to the same server in that same map, i crashed and got the second screen shot.

I am running Win 10 Pro and UT v469a
Intel 6800k CPU
Nvidia 1080

Original screenshot:
![image](https://user-images.githubusercontent.com/59076225/96072812-1cac1680-0e73-11eb-891f-6fa7261327ed.png)

Second crash when joining back to the same server with the same map:
![image](https://user-images.githubusercontent.com/59076225/96072845-33eb0400-0e73-11eb-97a7-41d1f292d914.png)

I also joined another server after restarting and had no problem.  I then tried to join the original server running the same map as previous crash and crashed again with the exact same GPF.

So I have a backup folder of my UT with patch 436.  I reverted to playing from that folder and had no problems.  Both with D3D9.

Thanks

**Comment by SeriousBuggie** [comment] 2020-10-15 08:33
Duplicate of #21 which too started by you.

**Comment by AtifArshad1995** [comment] 2020-10-15 09:28
I am having such issue as well when trying to launch CTF-EpicBoy

**Comment by OMA-Bite-Me** [comment] 2020-10-15 12:07
My bad,  this  looked different according to the actual error text.  I will check more thoroughly next time

**Closed** 2020-10-15 16:33 UTC
Labels: duplicate, fixed in the next patch
