### ISSUE TITLE
[469a][UEd] constant CPU use when idle

### ISSUE THREAD

**Issue by Dr-Flay** [OldUnreal/UnrealTournamentPatches#69] opened 2020-10-02 06:13 UTC
This may be finally when this can be fixed ! (almost forgot about this)
UEd is always busy doing nothing, when doing nothing.

With sound enabled in UEd there is constant activity visible in Process Explorer / Taskmanager.
The amount has varied a little between systems, but on this test PC (intel i5 3320M) UEd averages 15% CPU use.

My solution has always been to edit with the sound off and enable only if I need to.
With small maps it would not be very noticeable, but when working on a big complex map or when building the lighting and final render etc. it can add extra time to complete.

This is also noticeable with Unreal UEd.

**Comment by stijn-volckaert** [comment] 2020-10-03 11:11
UEd uses ~1% CPU while idle on my machine. Can you give me more specific steps to follow to get it to use 15%?

**Comment by Dr-Flay** [comment] 2020-10-04 02:53
I have the defaults in place as supplied in the new default.ini so it is using OpenGL and OpenAL (I also tested Cluster and Galaxy and see the same activity)
I have made a point of not tweaking the settings at all, apart from adding new masterserver info.
This is fresh GoG install with BP4 and the fixes for BP1 and 4.
1 mod installed. ChaosUT

The only step required is to load UEd and then look at the task info in Process Explorer.
I guess all we can do for the moment is ask others to comment on the CPU use they see.
The elevated CPU has been noticeable on every PC I have edited on, each with different version of windows and a different sound chip so I assume this is not isolated.
![UEd-CPU](https://user-images.githubusercontent.com/43873202/95005430-7c433000-05f0-11eb-96dd-a28dd1f85771.jpg)

**Comment by SeriousBuggie** [comment] 2020-10-04 03:52
Close all viewports, except one. Switch modes in it and watch CPU load. Try all modes. Firstly without game mode, secondly with.

For me results next:
Any 3D view without game mode = 2.5%
Any 3D view with game mode = 11.0%
Any planar view without game mode = 12.4%.
Any planar view with game mode = 12.6%.

I use software render.

So I think it is caused by planar view viewports.

If I use OpenGL render all same except game mode. Here full table:
![scr_1601783431](https://user-images.githubusercontent.com/70026933/95006505-f8983c00-060d-11eb-9c00-f8a2a1719c20.png)

**Comment by Dr-Flay** [comment] 2020-10-04 20:18
If I want to kill the idle CPU use, all I need to do is set audio in UEd to False.
This is audio chain related, not GFX.
With audio disabled I get no more than 0.20% no matter what renderers are used in UEd.

**Comment by racing-online** [comment] 2020-10-05 05:20
> So I think it is caused by planar view viewports.

Same here.
Also, planar view causes this only if set at the first view port - CPU load raises up to 7-8%. When set at another view ports it's 1-2% or below. This is with game mode turned off.
If game mode is turned on, with D3D9 render, CPU load is 9-11% and 3-4% - with and without planar view set at the first view port.
This effect disappears if audio is disabled.

**Comment by stijn-volckaert** [comment] 2020-10-05 22:50
Thanks, this will be fixed in 469b.

**Comment by SeriousBuggie** [comment] 2020-11-05 14:25
Fixed in v469b. Confirmed.

In some way. Only when game mode is off. If game mode is on, load is high.

Somewhere now in game mode load higher rather then before.

**Closed** 2021-03-10 23:26 UTC
Labels: UnrealEd, bug, fixed for 469b
