### ISSUE TITLE
[469c-RC4] Duplicate lines

### ISSUE THREAD

**Issue by osminogig** [OldUnreal/UnrealTournamentPatches#1101] opened 2022-10-26 16:27 UTC
**Installed on a clean UT (demo) + 436
It turns out this :**

![Снимок2](https://user-images.githubusercontent.com/12220671/198079965-18361ab9-d506-4ec1-9a40-59443e45c7b6.png)
![Снимок1](https://user-images.githubusercontent.com/12220671/198079995-649cf111-b935-4d1f-826b-9bdedd55aaa7.png)

**Comment by SeriousBuggie** [comment] 2022-10-26 19:45
Duplicate of #1021

**Closed** 2022-10-27 06:12 UTC
