### ISSUE TITLE
[469a] Another D3D9 Crash

### ISSUE THREAD

**Issue by OMA-Bite-Me** [OldUnreal/UnrealTournamentPatches#21] opened 2020-09-24 15:13 UTC
Hi,
First of all, great job getting this patch released.  It's amazing that 20+ years later people are still playing this game and working on development!

All was basically running smooth with only 1 crash.
![image](https://user-images.githubusercontent.com/59076225/94164273-d3117280-fe56-11ea-967e-5620451fc812.png)

I tried restarting, but I got this one next before even getting into the GUI:
![image](https://user-images.githubusercontent.com/59076225/94164323-e91f3300-fe56-11ea-9ba1-926522b76486.png)

Eventually I got a windows firewall popup that needed to be clicked off.  After that, all was well again.  Not sure if this is fixable or not, but thought I should pass it on.

**Comment by OMA-Bite-Me** [comment] 2020-09-24 15:26
OS: Windows 10 Professional
Version:  Patched to V469a

Running at 1440p on an ultrawide monitor

**Comment by stijn-volckaert** [comment] 2020-09-24 15:51
These look like similar crashes. D3D9Drv appears to be trying to convert an invalid texture to RGBA8888 format. Will look into it!

**Comment by stijn-volckaert** [comment] 2020-09-25 14:20
This is almost certainly a duplicate of issue #9 . I'm going to mark it as duplicate for now. Please test this again when the next build arrives.

**Comment by OMA-Bite-Me** [comment] 2020-09-25 20:21
Ok, thanks.  I was not sure if it was the same or not as that one did not
mention the windows firewall.

**Comment by Chamberly** [comment] 2020-09-26 02:21
A lot of time when there are the new .exe that has not been enabled through the firewall the Windows OS will ask you to whitelist it or deny it. That's on the OS itself, while the .exe in v469a is a new one compared to v436.

**Comment by SeriousBuggie** [comment] 2020-10-04 01:33
Same crash on another map:
https://unrealarchive.org/maps/unreal-tournament/monster-hunt/H/mh-htd-liandricorp-part2_6691e428.html
```
---------------------------
Critical Error
---------------------------
General protection fault!
History: ConvertP8_RGBA8888 <- WriteTexture <- UD3D9RenderDevice::SetTexture <- UD3D9RenderDevice::PrecacheTexture 
<- NormalTexture <- (MH-HTD-LiandriCorp-Part2.Particles.ParticleSkin1) <- URender::Precache <- UGameEngine::Draw 
<- UWindowsViewport::Repaint <- UWindowsClient::Tick <- ClientTick <- UGameEngine::Tick <- UpdateWorld <- MainLoop
---------------------------
ОК   
---------------------------
```
Waiting for 469b.

**Closed** 2021-03-10 23:28 UTC
Labels: bug, duplicate, rendering, fixed in the next patch
