### ISSUE TITLE
Unrealed cancel button doesn't work

### ISSUE THREAD

**Issue by zero-khan** [OldUnreal/UnrealTournamentPatches#141] opened 2020-10-28 04:41 UTC
When you click to close the editor, if you click CANCEL, it doesn't cancel and closes either way.

When you save the map and then click to open another map, it always ask to save again.

**Comment by SeriousBuggie** [comment] 2020-10-28 05:45
> When you click to close the editor, if you click CANCEL, it doesn't cancel and closes either way.

Please use search before create issue. Duplicate of https://github.com/OldUnreal/UnrealTournamentPatches/issues/8.

> When you save the map and then click to open another map, it always ask to save again.

Please do not mix different issues into one. Make separate issues,

Also if you export map to t3d you see field TimeSeconds in LevelInfo, which constantly increased every-time. So map always changed. Even if you save it 1 seconds ago.

**Closed** 2020-10-28 06:11 UTC
