### ISSUE TITLE
[win][469a] XOpenGL blue artefact when switch weapons

### ISSUE THREAD

**Issue by SeriousBuggie** [OldUnreal/UnrealTournamentPatches#38] opened 2020-09-25 05:32 UTC
Reproduce:
1. Start UT.
2. Start Practice mode on Deck16.
3. Start game.
4. Console - `loaded` - enter
5. Switch to Flak.
6. Alt fire.
7. Switch to Enforcer.

Expected result: no blue flashes.
Actual result: Blue flashes when weapon model switched to enforcer.
![ezgif-3-75f5dfa14b8b](https://user-images.githubusercontent.com/70026933/94229934-7c18a580-ff09-11ea-8835-c1f6d6705bb4.gif)
![utb1 mp4_snapshot_00 03](https://user-images.githubusercontent.com/70026933/94229693-f09f1480-ff08-11ea-9f94-3423d6f4d379.png)
![utb1 mp4_snapshot_00 03_](https://user-images.githubusercontent.com/70026933/94229701-f4cb3200-ff08-11ea-9a21-28b83fe8514c.png)

System: Window 7 x64.
Windows Theme: Standard.
Video: 1920x1080 Intel HD Graphics 4000.
Two monitors 1920x1080 each. Expanded desktop.

XOpenGL related entries in the UT.log:
```
Log: Bound to XOpenGLDrv.dll
Dev: XOpenGL: SetRes
Log: XOpenGL: Fullscreen NewX 1920 NewY 1080
Log: ChangeDisplaySettings with RefreshRate: 1920x1080, 60 Hz
Log: XOpenGL: Creating new OpenGL context.
Init: XOpenGL: Successfully initialized.
Init: XOpenGL: DesiredColorBits: 32
Init: XOpenGL: DesiredDepthBits: 24
Init: XOpenGL: Setting PixelFormat: 16
Init: GL_VENDOR     : Intel
Init: GL_RENDERER   : Intel(R) HD Graphics 4000
Init: GL_VERSION    : 3.3.0 - Build 10.18.10.4226
Init: GL_SHADING_LANGUAGE_VERSION    : 3.30 - Build 10.18.10.4226
Init: OpenGL 3.3 context initialized!
Log: XOpenGL: OpenGL debugging disabled.
Log: XOpenGL: WGL_EXT_swap_control found.
Log: XOpenGL: WGL_EXT_swap_control_tear found.
Log: XOpenGL: MaxTextureImageUnits: 16
Log: XOpenGL: MaxImageUnits: 0
Warning: OpenGL debugging extension not found!
Log: XOpenGL: MaxCombinedTextureImageUnits: 96
Log: XOpenGL: MaxElementsVertices: 1048576
Log: XOpenGL: MaxUniformBufferBindings: 70
Log: XOpenGL: MaxDualSourceDrawBuffers: 1
Log: XOpenGL: MaxTextureSize: 16384
Log: XOpenGL: MaxAnisotropy = (4.000000/16.000000)
Log: XOpenGL: NumAASamples: (4/8)
Log: XOpenGL: GL_NUM_EXTENSIONS found: 187
Log: XOpenGL: GL_MAX_CLIP_DISTANCES found: 8
Log: XOpenGL: Flush
Log: XOpenGL: Setting VSync: On
Log: XOpenGL: SyncToDraw disabled
Log: XOpenGL: No compiler messages for xopengl/DrawSimple.vert
Log: XOpenGL: No compiler messages for xopengl/DrawSimple.frag
Log: XOpenGL: No compiler messages for xopengl/DrawTile.vert
Log: XOpenGL: No compiler messages for xopengl/DrawTile.geo
Log: XOpenGL: No compiler messages for xopengl/DrawTile.frag
Log: XOpenGL: No compiler messages for xopengl/DrawGouraud.vert
Log: XOpenGL: No compiler messages for xopengl/DrawGouraud.geo
Log: XOpenGL: No compiler messages for xopengl/DrawGouraud.frag
Log: XOpenGL: No compiler messages for xopengl/DrawComplexSinglePass.vert
Log: XOpenGL: No compiler messages for xopengl/DrawComplexSinglePass.frag
Log: XOpenGL: No linker messages for DrawSimpleProg
Log: XOpenGL: No linker messages for DrawTileProg
Log: XOpenGL: No linker messages for DrawComplexProg
Log: XOpenGL: No linker messages for DrawGouraudProg
Dev: XOpenGL: invalid or unused shader var (UniformBlockIndex) DistanceFogParams in DrawSimpleProg
Dev: XOpenGL: invalid or unused shader var (UniformBlockIndex) DistanceFogParams in DrawTileProg
Dev: XOpenGL: invalid or unused shader var (UniformBlockIndex) StaticLightInfo in DrawSimpleProg
Dev: XOpenGL: invalid or unused shader var (UniformBlockIndex) StaticLightInfo in DrawTileProg
Dev: XOpenGL: invalid or unused shader var (UniformBlockIndex) GlobalCoords in DrawSimpleProg
Dev: XOpenGL: invalid or unused shader var (UniformBlockIndex) GlobalCoords in DrawTileProg
Dev: XOpenGL: invalid or unused shader var (UniformLocation) TexCoords in DrawTile
Dev: XOpenGL: invalid or unused shader var (UniformLocation) bHitTesting in DrawTile
Dev: XOpenGL: invalid or unused shader var (UniformLocation) HitDrawColor in DrawTile
Dev: XOpenGL: invalid or unused shader var (UniformLocation) TexNum in DrawTile
Dev: XOpenGL: invalid or unused shader var (UniformLocation) RendMap in DrawComplexSinglePass
Dev: XOpenGL: invalid or unused shader var (UniformLocation) bHitTesting in DrawComplexSinglePass
Dev: XOpenGL: invalid or unused shader var (UniformLocation) DrawColor in DrawComplexSinglePass
Dev: XOpenGL: invalid or unused shader var (UniformLocation) FogParams.FogColor in DrawComplexSinglePass
Dev: XOpenGL: invalid or unused shader var (UniformLocation) FogParams.FogStart in DrawComplexSinglePass
Dev: XOpenGL: invalid or unused shader var (UniformLocation) FogParams.FogEnd in DrawComplexSinglePass
Dev: XOpenGL: invalid or unused shader var (UniformLocation) FogParams.FogDensity in DrawComplexSinglePass
Dev: XOpenGL: invalid or unused shader var (UniformLocation) FogParams.FogMode in DrawComplexSinglePass
Dev: XOpenGL: invalid or unused shader var (UniformLocation) LightPos in DrawComplexSinglePass
Dev: XOpenGL: invalid or unused shader var (UniformLocation) FogMode in DrawComplexSinglePass
Dev: XOpenGL: invalid or unused shader var (UniformLocation) TexNum in DrawComplexSinglePass
Dev: XOpenGL: invalid or unused shader var (UniformLocation) Texture7 in DrawComplexSinglePass
Dev: XOpenGL: invalid or unused shader var (UniformLocation) RendMap in DrawGouraud
Dev: XOpenGL: invalid or unused shader var (UniformLocation) bHitTesting in DrawGouraud
Dev: XOpenGL: invalid or unused shader var (UniformLocation) LightPos in DrawGouraud
Dev: XOpenGL: invalid or unused shader var (UniformLocation) Texture4 in DrawGouraud
Dev: XOpenGL: invalid or unused shader var (UniformLocation) Texture5 in DrawGouraud
Dev: XOpenGL: invalid or unused shader var (UniformLocation) Texture6 in DrawGouraud
Dev: XOpenGL: invalid or unused shader var (UniformLocation) Texture7 in DrawGouraud
```

**Comment by stijn-volckaert** [comment] 2020-09-25 12:37
Cannot reproduce. I'll try again when you've posted your XOpenGLDrv settings.

**Comment by SeriousBuggie** [comment] 2020-09-25 13:06
```
[XOpenGLDrv.XOpenGLRenderDevice]
AlwaysMipmap=False
ShareLists=True
DetailTextures=True
MacroTextures=True
BumpMaps=True
DescFlags=0
Description=Intel(R) HD Graphics 4000
Coronas=True
ShinySurfaces=True
VolumetricLighting=True
RefreshRate=60
UseSinglePass=True
UseTrilinear=True
UsePrecache=True
NoFiltering=False
LODBias=0.000000
GammaCorrectScreenshots=True
GammaOffsetScreenshots=0.700000
MaxAnisotropy=4.000000
HighDetailActors=True
UseOpenGLDebug=False
DebugLevel=1
UseAA=True
NumAASamples=4
VSync=On
NoAATiles=True
UseBufferInvalidation=False
NoBuffering=False
GenerateMipMaps=False
OpenGLVersion=Core
NoDrawSimple=False
NoDrawTile=False
NoDrawGouraudList=False
NoDrawGouraud=False
NoDrawComplexSurface=False
UseHWClipping=False
UseHWLighting=False
UseBindlessTextures=False
SyncToDraw=False
UsePersistentBuffers=False
UseVSync=On
```

**Comment by stijn-volckaert** [comment] 2020-09-25 13:08
Still cannot reproduce

**Comment by SeriousBuggie** [comment] 2020-09-25 13:15
In windowed mode glitch appear too. On OpenGL render glitch not appear at all. How this possible?

**Comment by SeriousBuggie** [comment] 2020-09-25 13:37
Also this glitch happen not stable if simply switch from Flak to Enforcer. Need make AltFire.   
Because AltFire produce smoke. If smoke disappear glitch can not happen anymore.   
PrimaryFire not trigger glitch.    
But on some places on map (I do not find any correlation) glitch happen very stable and not need smoke for reproduce it.

**Comment by CacoFFF** [comment] 2020-09-26 13:16
> 
> 
> In windowed mode glitch appear too. On OpenGL render glitch not appear at all. How this possible?

Because UTGLR OpenGL is rendering without shader code... or with ARB Fragment program shader code.
XOpenGL uses GLSL.

**Comment by stijn-volckaert** [comment] 2020-09-28 22:23
I suspect this is the same issue as #44 and #29. This should be fixed in 469b.

**Comment by SeriousBuggie** [comment] 2020-11-05 14:03
Fixed in v469b. Confirmed.

**Closed** 2021-03-10 23:27 UTC
Labels: fixed for 469b, video
