### ISSUE TITLE
[469b] Ued - add possible feature Maximize/Minimize viewport when double click on header.

### ISSUE THREAD

**Issue by BerserkerBG** [OldUnreal/UnrealTournamentPatches#872] opened 2022-06-17 12:05 UTC
An idea when you double click on the header of a view port to maximize/minimize it. Alternatively, it could have the mazimize/minimize Icon button on top right of viewports, resembling windows functionality:
![Screenshot_2222](https://user-images.githubusercontent.com/58362332/174294390-86d5c874-2849-4974-af31-164e0a15c173.png)

Or perhaps have both?

**Comment by SeriousBuggie** [comment] 2022-06-17 12:21
Duplicate of #562
Started by you, BTW ;-)

**Comment by BerserkerBG** [comment] 2022-06-17 12:41
duplicate

**Closed** 2022-06-17 12:41 UTC
